package model.view;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 10 14:49:40 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ApprovalHoldCheckVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ApprovalHoldCheckVOImpl() {
    }
}

