package model.view;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 25 11:36:49 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BuAccParamsValidateVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public BuAccParamsValidateVOImpl() {
    }
}

