package model.view;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 16 11:37:10 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DoAttachmentsPrintVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ContractChargeId,
        ContractLineId,
        CategoryDescription,
        Quantity;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int CONTRACTCHARGEID = AttributesEnum.ContractChargeId.index();
    public static final int CONTRACTLINEID = AttributesEnum.ContractLineId.index();
    public static final int CATEGORYDESCRIPTION = AttributesEnum.CategoryDescription.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DoAttachmentsPrintVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute ContractChargeId.
     * @return the ContractChargeId
     */
    public Number getContractChargeId() {
        return (Number) getAttributeInternal(CONTRACTCHARGEID);
    }

    /**
     * Gets the attribute value for the calculated attribute ContractLineId.
     * @return the ContractLineId
     */
    public Number getContractLineId() {
        return (Number) getAttributeInternal(CONTRACTLINEID);
    }

    /**
     * Gets the attribute value for the calculated attribute CategoryDescription.
     * @return the CategoryDescription
     */
    public String getCategoryDescription() {
        return (String) getAttributeInternal(CATEGORYDESCRIPTION);
    }

    /**
     * Gets the attribute value for the calculated attribute Quantity.
     * @return the Quantity
     */
    public Number getQuantity() {
        return (Number) getAttributeInternal(QUANTITY);
    }
}

