package model.view;

import model.entity.XxadsDocumentSequenceEOImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 14 17:03:29 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DocumentSequenceUpdateVORowImpl extends ViewRowImpl {


    public static final int ENTITY_XXADSDOCUMENTSEQUENCEEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        BuId,
        CreatedBy,
        CreationDate,
        CurrentSeqNum,
        DocSequenceId,
        DocumentCode,
        EffectiveFrom,
        EffectiveTo,
        LastUpdateDate,
        LastUpdatedBy,
        ObjectVersionNumber,
        StartingSeqNum,
        DivFlexValueId,
        DivisionCode;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BUID = AttributesEnum.BuId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CURRENTSEQNUM = AttributesEnum.CurrentSeqNum.index();
    public static final int DOCSEQUENCEID = AttributesEnum.DocSequenceId.index();
    public static final int DOCUMENTCODE = AttributesEnum.DocumentCode.index();
    public static final int EFFECTIVEFROM = AttributesEnum.EffectiveFrom.index();
    public static final int EFFECTIVETO = AttributesEnum.EffectiveTo.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int OBJECTVERSIONNUMBER = AttributesEnum.ObjectVersionNumber.index();
    public static final int STARTINGSEQNUM = AttributesEnum.StartingSeqNum.index();
    public static final int DIVFLEXVALUEID = AttributesEnum.DivFlexValueId.index();
    public static final int DIVISIONCODE = AttributesEnum.DivisionCode.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DocumentSequenceUpdateVORowImpl() {
    }

    /**
     * Gets XxadsDocumentSequenceEO entity object.
     * @return the XxadsDocumentSequenceEO
     */
    public XxadsDocumentSequenceEOImpl getXxadsDocumentSequenceEO() {
        return (XxadsDocumentSequenceEOImpl) getEntity(ENTITY_XXADSDOCUMENTSEQUENCEEO);
    }

    /**
     * Gets the attribute value for BU_ID using the alias name BuId.
     * @return the BU_ID
     */
    public Number getBuId() {
        return (Number) getAttributeInternal(BUID);
    }

    /**
     * Sets <code>value</code> as attribute value for BU_ID using the alias name BuId.
     * @param value value to set the BU_ID
     */
    public void setBuId(Number value) {
        setAttributeInternal(BUID, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for CURRENT_SEQ_NUM using the alias name CurrentSeqNum.
     * @return the CURRENT_SEQ_NUM
     */
    public Number getCurrentSeqNum() {
        return (Number) getAttributeInternal(CURRENTSEQNUM);
    }

    /**
     * Sets <code>value</code> as attribute value for CURRENT_SEQ_NUM using the alias name CurrentSeqNum.
     * @param value value to set the CURRENT_SEQ_NUM
     */
    public void setCurrentSeqNum(Number value) {
        setAttributeInternal(CURRENTSEQNUM, value);
    }

    /**
     * Gets the attribute value for DOC_SEQUENCE_ID using the alias name DocSequenceId.
     * @return the DOC_SEQUENCE_ID
     */
    public Number getDocSequenceId() {
        return (Number) getAttributeInternal(DOCSEQUENCEID);
    }

    /**
     * Sets <code>value</code> as attribute value for DOC_SEQUENCE_ID using the alias name DocSequenceId.
     * @param value value to set the DOC_SEQUENCE_ID
     */
    public void setDocSequenceId(Number value) {
        setAttributeInternal(DOCSEQUENCEID, value);
    }

    /**
     * Gets the attribute value for DOCUMENT_CODE using the alias name DocumentCode.
     * @return the DOCUMENT_CODE
     */
    public String getDocumentCode() {
        return (String) getAttributeInternal(DOCUMENTCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for DOCUMENT_CODE using the alias name DocumentCode.
     * @param value value to set the DOCUMENT_CODE
     */
    public void setDocumentCode(String value) {
        setAttributeInternal(DOCUMENTCODE, value);
    }

    /**
     * Gets the attribute value for EFFECTIVE_FROM using the alias name EffectiveFrom.
     * @return the EFFECTIVE_FROM
     */
    public Date getEffectiveFrom() {
        return (Date) getAttributeInternal(EFFECTIVEFROM);
    }

    /**
     * Sets <code>value</code> as attribute value for EFFECTIVE_FROM using the alias name EffectiveFrom.
     * @param value value to set the EFFECTIVE_FROM
     */
    public void setEffectiveFrom(Date value) {
        setAttributeInternal(EFFECTIVEFROM, value);
    }

    /**
     * Gets the attribute value for EFFECTIVE_TO using the alias name EffectiveTo.
     * @return the EFFECTIVE_TO
     */
    public Date getEffectiveTo() {
        return (Date) getAttributeInternal(EFFECTIVETO);
    }

    /**
     * Sets <code>value</code> as attribute value for EFFECTIVE_TO using the alias name EffectiveTo.
     * @param value value to set the EFFECTIVE_TO
     */
    public void setEffectiveTo(Date value) {
        setAttributeInternal(EFFECTIVETO, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Gets the attribute value for OBJECT_VERSION_NUMBER using the alias name ObjectVersionNumber.
     * @return the OBJECT_VERSION_NUMBER
     */
    public Number getObjectVersionNumber() {
        return (Number) getAttributeInternal(OBJECTVERSIONNUMBER);
    }

    /**
     * Gets the attribute value for STARTING_SEQ_NUM using the alias name StartingSeqNum.
     * @return the STARTING_SEQ_NUM
     */
    public Number getStartingSeqNum() {
        return (Number) getAttributeInternal(STARTINGSEQNUM);
    }

    /**
     * Sets <code>value</code> as attribute value for STARTING_SEQ_NUM using the alias name StartingSeqNum.
     * @param value value to set the STARTING_SEQ_NUM
     */
    public void setStartingSeqNum(Number value) {
        setAttributeInternal(STARTINGSEQNUM, value);
    }

    /**
     * Gets the attribute value for DIV_FLEX_VALUE_ID using the alias name DivFlexValueId.
     * @return the DIV_FLEX_VALUE_ID
     */
    public Number getDivFlexValueId() {
        return (Number) getAttributeInternal(DIVFLEXVALUEID);
    }

    /**
     * Sets <code>value</code> as attribute value for DIV_FLEX_VALUE_ID using the alias name DivFlexValueId.
     * @param value value to set the DIV_FLEX_VALUE_ID
     */
    public void setDivFlexValueId(Number value) {
        setAttributeInternal(DIVFLEXVALUEID, value);
    }

    /**
     * Gets the attribute value for DIVISION_CODE using the alias name DivisionCode.
     * @return the DIVISION_CODE
     */
    public String getDivisionCode() {
        return (String) getAttributeInternal(DIVISIONCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for DIVISION_CODE using the alias name DivisionCode.
     * @param value value to set the DIVISION_CODE
     */
    public void setDivisionCode(String value) {
        setAttributeInternal(DIVISIONCODE, value);
    }
}

