package model.view;

import java.sql.Timestamp;

import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 11 11:56:29 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DOHdrReportVORowImpl extends ViewRowImpl {


    public static final int ENTITY_XXADSDEPLOYMENTORDERREPORTHD1 = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        CustomerName,
        DoId,
        DocumentDate,
        LpoReference,
        SiteContactNumber,
        SiteContactPerson,
        QuotationReference,
        Address,
        DoNumber,
        DOLinesReportVO;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CUSTOMERNAME = AttributesEnum.CustomerName.index();
    public static final int DOID = AttributesEnum.DoId.index();
    public static final int DOCUMENTDATE = AttributesEnum.DocumentDate.index();
    public static final int LPOREFERENCE = AttributesEnum.LpoReference.index();
    public static final int SITECONTACTNUMBER = AttributesEnum.SiteContactNumber.index();
    public static final int SITECONTACTPERSON = AttributesEnum.SiteContactPerson.index();
    public static final int QUOTATIONREFERENCE = AttributesEnum.QuotationReference.index();
    public static final int ADDRESS = AttributesEnum.Address.index();
    public static final int DONUMBER = AttributesEnum.DoNumber.index();
    public static final int DOLINESREPORTVO = AttributesEnum.DOLinesReportVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DOHdrReportVORowImpl() {
    }

    /**
     * Gets XxadsDeploymentOrderReportHd1 entity object.
     * @return the XxadsDeploymentOrderReportHd1
     */
    public EntityImpl getXxadsDeploymentOrderReportHd1() {
        return (EntityImpl) getEntity(ENTITY_XXADSDEPLOYMENTORDERREPORTHD1);
    }

    /**
     * Gets the attribute value for CUSTOMER_NAME using the alias name CustomerName.
     * @return the CUSTOMER_NAME
     */
    public String getCustomerName() {
        return (String) getAttributeInternal(CUSTOMERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMER_NAME using the alias name CustomerName.
     * @param value value to set the CUSTOMER_NAME
     */
    public void setCustomerName(String value) {
        setAttributeInternal(CUSTOMERNAME, value);
    }

    /**
     * Gets the attribute value for DO_ID using the alias name DoId.
     * @return the DO_ID
     */
    public Number getDoId() {
        return (Number) getAttributeInternal(DOID);
    }

    /**
     * Sets <code>value</code> as attribute value for DO_ID using the alias name DoId.
     * @param value value to set the DO_ID
     */
    public void setDoId(Number value) {
        setAttributeInternal(DOID, value);
    }

    /**
     * Gets the attribute value for DOCUMENT_DATE using the alias name DocumentDate.
     * @return the DOCUMENT_DATE
     */
    public Date getDocumentDate() {
        return (Date) getAttributeInternal(DOCUMENTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for DOCUMENT_DATE using the alias name DocumentDate.
     * @param value value to set the DOCUMENT_DATE
     */
    public void setDocumentDate(Date value) {
        setAttributeInternal(DOCUMENTDATE, value);
    }

    /**
     * Gets the attribute value for LPO_REFERENCE using the alias name LpoReference.
     * @return the LPO_REFERENCE
     */
    public String getLpoReference() {
        return (String) getAttributeInternal(LPOREFERENCE);
    }

    /**
     * Sets <code>value</code> as attribute value for LPO_REFERENCE using the alias name LpoReference.
     * @param value value to set the LPO_REFERENCE
     */
    public void setLpoReference(String value) {
        setAttributeInternal(LPOREFERENCE, value);
    }

    /**
     * Gets the attribute value for SITE_CONTACT_NUMBER using the alias name SiteContactNumber.
     * @return the SITE_CONTACT_NUMBER
     */
    public String getSiteContactNumber() {
        return (String) getAttributeInternal(SITECONTACTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for SITE_CONTACT_NUMBER using the alias name SiteContactNumber.
     * @param value value to set the SITE_CONTACT_NUMBER
     */
    public void setSiteContactNumber(String value) {
        setAttributeInternal(SITECONTACTNUMBER, value);
    }

    /**
     * Gets the attribute value for SITE_CONTACT_PERSON using the alias name SiteContactPerson.
     * @return the SITE_CONTACT_PERSON
     */
    public String getSiteContactPerson() {
        return (String) getAttributeInternal(SITECONTACTPERSON);
    }

    /**
     * Sets <code>value</code> as attribute value for SITE_CONTACT_PERSON using the alias name SiteContactPerson.
     * @param value value to set the SITE_CONTACT_PERSON
     */
    public void setSiteContactPerson(String value) {
        setAttributeInternal(SITECONTACTPERSON, value);
    }

    /**
     * Gets the attribute value for QUOTATION_REFERENCE using the alias name QuotationReference.
     * @return the QUOTATION_REFERENCE
     */
    public String getQuotationReference() {
        return (String) getAttributeInternal(QUOTATIONREFERENCE);
    }

    /**
     * Sets <code>value</code> as attribute value for QUOTATION_REFERENCE using the alias name QuotationReference.
     * @param value value to set the QUOTATION_REFERENCE
     */
    public void setQuotationReference(String value) {
        setAttributeInternal(QUOTATIONREFERENCE, value);
    }

    /**
     * Gets the attribute value for ADDRESS using the alias name Address.
     * @return the ADDRESS
     */
    public String getAddress() {
        return (String) getAttributeInternal(ADDRESS);
    }

    /**
     * Sets <code>value</code> as attribute value for ADDRESS using the alias name Address.
     * @param value value to set the ADDRESS
     */
    public void setAddress(String value) {
        setAttributeInternal(ADDRESS, value);
    }

    /**
     * Gets the attribute value for DO_NUMBER using the alias name DoNumber.
     * @return the DO_NUMBER
     */
    public String getDoNumber() {
        return (String) getAttributeInternal(DONUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for DO_NUMBER using the alias name DoNumber.
     * @param value value to set the DO_NUMBER
     */
    public void setDoNumber(String value) {
        setAttributeInternal(DONUMBER, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link DOLinesReportVO.
     */
    public RowIterator getDOLinesReportVO() {
        return (RowIterator) getAttributeInternal(DOLINESREPORTVO);
    }
}

