package model.view;

import java.math.BigDecimal;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 06 12:15:32 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class QuoteReportLinesVORowImpl extends ViewRowImpl {


    public static final int ENTITY_XXADSQUOTATIONREPORTLINESEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Amount,
        Capacity,
        Description,
        MinChargeValue,
        Model,
        Quantity,
        QuotationId,
        QuoteLineId,
        RentalRate,
        UnitPrice,
        Uom,
        CategoryId,
        MobilizationValue,
        NoOfDays,
        NoOfHours,
        PerPeriodTaxAmount,
        PerPeriodTotalAmount,
        PerPeriodUnitRate,
        PeriodIdentifier,
        TaxRatePercent,
        QuoteReportChargesVO;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int AMOUNT = AttributesEnum.Amount.index();
    public static final int CAPACITY = AttributesEnum.Capacity.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int MINCHARGEVALUE = AttributesEnum.MinChargeValue.index();
    public static final int MODEL = AttributesEnum.Model.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int QUOTATIONID = AttributesEnum.QuotationId.index();
    public static final int QUOTELINEID = AttributesEnum.QuoteLineId.index();
    public static final int RENTALRATE = AttributesEnum.RentalRate.index();
    public static final int UNITPRICE = AttributesEnum.UnitPrice.index();
    public static final int UOM = AttributesEnum.Uom.index();
    public static final int CATEGORYID = AttributesEnum.CategoryId.index();
    public static final int MOBILIZATIONVALUE = AttributesEnum.MobilizationValue.index();
    public static final int NOOFDAYS = AttributesEnum.NoOfDays.index();
    public static final int NOOFHOURS = AttributesEnum.NoOfHours.index();
    public static final int PERPERIODTAXAMOUNT = AttributesEnum.PerPeriodTaxAmount.index();
    public static final int PERPERIODTOTALAMOUNT = AttributesEnum.PerPeriodTotalAmount.index();
    public static final int PERPERIODUNITRATE = AttributesEnum.PerPeriodUnitRate.index();
    public static final int PERIODIDENTIFIER = AttributesEnum.PeriodIdentifier.index();
    public static final int TAXRATEPERCENT = AttributesEnum.TaxRatePercent.index();
    public static final int QUOTEREPORTCHARGESVO = AttributesEnum.QuoteReportChargesVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public QuoteReportLinesVORowImpl() {
    }
}

