package model.view;

import model.entity.XxadsRentalContractEOImpl;
import model.entity.XxadsRentalContractLinesEOImpl;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Raw;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 01 15:07:46 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RentalContractLinesVORowImpl extends ViewRowImpl {


    public static final int ENTITY_XXADSRENTALCONTRACTLINESEO = 0;
    public static final int ENTITY_XXADSRENTALCONTRACTEO = 1;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ActiveFlag,
        CategoryId,
        ContractId,
        ContractLineId,
        CreatedBy,
        CreationDate,
        FuelOption,
        HiringBasisRuleId,
        LastUpdateDate,
        LastUpdatedBy,
        LineNum,
        LineValue,
        MasterContractId,
        MasterContractLineId,
        MinChargeUnit,
        MinChargeValue,
        MobilizationRequired,
        ObjectVersionNumber,
        OffHireDate,
        OnHireDate,
        OperatorOption,
        Ot1Rate,
        Ot2Rate,
        ParentContractId,
        ParentContractLineId,
        Quantity,
        ReferenceId,
        ReferenceLineId,
        ReferenceLineNum,
        Remarks,
        RentalType,
        Shift,
        StandardRate,
        TransRentalType,
        TransCategory,
        TransCategoryDescription,
        TransHiringBasis,
        TransFixedVariable,
        TransOperatorOption,
        TransFuelOption,
        TransMobilizationRequired,
        TransShift,
        TransMinChargeUnit,
        TransReferenceNumber,
        TransHdrSrcBuId,
        SrcBuId,
        ContractId1,
        TransHdrContractSource,
        ContractSource,
        TransHdrSrcDivFlexValId,
        SrcDivFlexValId,
        MasterRefLineId,
        TaskId,
        ExpenditureTypeId,
        TransTask,
        TransExpenditureDesc,
        TransSetId,
        ProjectId,
        TransTotalAmount,
        UnitRate,
        TransNoofDays,
        TransStandardHours,
        TaxRateId,
        TaxRateCode,
        TaxRatePercent,
        VatTaxAmount,
        TransNetAmount,
        TransProjectId,
        CategoryDescription,
        LookupsLOV1,
        RentalTypeBasedCategoryLOV1,
        HiringBasisLOVVO1,
        OptionsLOVVO1,
        OptionsLOVVO2,
        LookupsLOV2,
        LookupsLOV3,
        QuoteChargeableUnitLovVO1,
        LookupsLOV4,
        TasksLOV1,
        ExpenditureTypesLOV1,
        TaxCodesLOV1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ACTIVEFLAG = AttributesEnum.ActiveFlag.index();
    public static final int CATEGORYID = AttributesEnum.CategoryId.index();
    public static final int CONTRACTID = AttributesEnum.ContractId.index();
    public static final int CONTRACTLINEID = AttributesEnum.ContractLineId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int FUELOPTION = AttributesEnum.FuelOption.index();
    public static final int HIRINGBASISRULEID = AttributesEnum.HiringBasisRuleId.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LINENUM = AttributesEnum.LineNum.index();
    public static final int LINEVALUE = AttributesEnum.LineValue.index();
    public static final int MASTERCONTRACTID = AttributesEnum.MasterContractId.index();
    public static final int MASTERCONTRACTLINEID = AttributesEnum.MasterContractLineId.index();
    public static final int MINCHARGEUNIT = AttributesEnum.MinChargeUnit.index();
    public static final int MINCHARGEVALUE = AttributesEnum.MinChargeValue.index();
    public static final int MOBILIZATIONREQUIRED = AttributesEnum.MobilizationRequired.index();
    public static final int OBJECTVERSIONNUMBER = AttributesEnum.ObjectVersionNumber.index();
    public static final int OFFHIREDATE = AttributesEnum.OffHireDate.index();
    public static final int ONHIREDATE = AttributesEnum.OnHireDate.index();
    public static final int OPERATOROPTION = AttributesEnum.OperatorOption.index();
    public static final int OT1RATE = AttributesEnum.Ot1Rate.index();
    public static final int OT2RATE = AttributesEnum.Ot2Rate.index();
    public static final int PARENTCONTRACTID = AttributesEnum.ParentContractId.index();
    public static final int PARENTCONTRACTLINEID = AttributesEnum.ParentContractLineId.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int REFERENCEID = AttributesEnum.ReferenceId.index();
    public static final int REFERENCELINEID = AttributesEnum.ReferenceLineId.index();
    public static final int REFERENCELINENUM = AttributesEnum.ReferenceLineNum.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int RENTALTYPE = AttributesEnum.RentalType.index();
    public static final int SHIFT = AttributesEnum.Shift.index();
    public static final int STANDARDRATE = AttributesEnum.StandardRate.index();
    public static final int TRANSRENTALTYPE = AttributesEnum.TransRentalType.index();
    public static final int TRANSCATEGORY = AttributesEnum.TransCategory.index();
    public static final int TRANSCATEGORYDESCRIPTION = AttributesEnum.TransCategoryDescription.index();
    public static final int TRANSHIRINGBASIS = AttributesEnum.TransHiringBasis.index();
    public static final int TRANSFIXEDVARIABLE = AttributesEnum.TransFixedVariable.index();
    public static final int TRANSOPERATOROPTION = AttributesEnum.TransOperatorOption.index();
    public static final int TRANSFUELOPTION = AttributesEnum.TransFuelOption.index();
    public static final int TRANSMOBILIZATIONREQUIRED = AttributesEnum.TransMobilizationRequired.index();
    public static final int TRANSSHIFT = AttributesEnum.TransShift.index();
    public static final int TRANSMINCHARGEUNIT = AttributesEnum.TransMinChargeUnit.index();
    public static final int TRANSREFERENCENUMBER = AttributesEnum.TransReferenceNumber.index();
    public static final int TRANSHDRSRCBUID = AttributesEnum.TransHdrSrcBuId.index();
    public static final int SRCBUID = AttributesEnum.SrcBuId.index();
    public static final int CONTRACTID1 = AttributesEnum.ContractId1.index();
    public static final int TRANSHDRCONTRACTSOURCE = AttributesEnum.TransHdrContractSource.index();
    public static final int CONTRACTSOURCE = AttributesEnum.ContractSource.index();
    public static final int TRANSHDRSRCDIVFLEXVALID = AttributesEnum.TransHdrSrcDivFlexValId.index();
    public static final int SRCDIVFLEXVALID = AttributesEnum.SrcDivFlexValId.index();
    public static final int MASTERREFLINEID = AttributesEnum.MasterRefLineId.index();
    public static final int TASKID = AttributesEnum.TaskId.index();
    public static final int EXPENDITURETYPEID = AttributesEnum.ExpenditureTypeId.index();
    public static final int TRANSTASK = AttributesEnum.TransTask.index();
    public static final int TRANSEXPENDITUREDESC = AttributesEnum.TransExpenditureDesc.index();
    public static final int TRANSSETID = AttributesEnum.TransSetId.index();
    public static final int PROJECTID = AttributesEnum.ProjectId.index();
    public static final int TRANSTOTALAMOUNT = AttributesEnum.TransTotalAmount.index();
    public static final int UNITRATE = AttributesEnum.UnitRate.index();
    public static final int TRANSNOOFDAYS = AttributesEnum.TransNoofDays.index();
    public static final int TRANSSTANDARDHOURS = AttributesEnum.TransStandardHours.index();
    public static final int TAXRATEID = AttributesEnum.TaxRateId.index();
    public static final int TAXRATECODE = AttributesEnum.TaxRateCode.index();
    public static final int TAXRATEPERCENT = AttributesEnum.TaxRatePercent.index();
    public static final int VATTAXAMOUNT = AttributesEnum.VatTaxAmount.index();
    public static final int TRANSNETAMOUNT = AttributesEnum.TransNetAmount.index();
    public static final int TRANSPROJECTID = AttributesEnum.TransProjectId.index();
    public static final int CATEGORYDESCRIPTION = AttributesEnum.CategoryDescription.index();
    public static final int LOOKUPSLOV1 = AttributesEnum.LookupsLOV1.index();
    public static final int RENTALTYPEBASEDCATEGORYLOV1 = AttributesEnum.RentalTypeBasedCategoryLOV1.index();
    public static final int HIRINGBASISLOVVO1 = AttributesEnum.HiringBasisLOVVO1.index();
    public static final int OPTIONSLOVVO1 = AttributesEnum.OptionsLOVVO1.index();
    public static final int OPTIONSLOVVO2 = AttributesEnum.OptionsLOVVO2.index();
    public static final int LOOKUPSLOV2 = AttributesEnum.LookupsLOV2.index();
    public static final int LOOKUPSLOV3 = AttributesEnum.LookupsLOV3.index();
    public static final int QUOTECHARGEABLEUNITLOVVO1 = AttributesEnum.QuoteChargeableUnitLovVO1.index();
    public static final int LOOKUPSLOV4 = AttributesEnum.LookupsLOV4.index();
    public static final int TASKSLOV1 = AttributesEnum.TasksLOV1.index();
    public static final int EXPENDITURETYPESLOV1 = AttributesEnum.ExpenditureTypesLOV1.index();
    public static final int TAXCODESLOV1 = AttributesEnum.TaxCodesLOV1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public RentalContractLinesVORowImpl() {
    }

    /**
     * Gets XxadsRentalContractLinesEO entity object.
     * @return the XxadsRentalContractLinesEO
     */
    public XxadsRentalContractLinesEOImpl getXxadsRentalContractLinesEO() {
        return (XxadsRentalContractLinesEOImpl) getEntity(ENTITY_XXADSRENTALCONTRACTLINESEO);
    }

    /**
     * Gets XxadsRentalContractEO entity object.
     * @return the XxadsRentalContractEO
     */
    public XxadsRentalContractEOImpl getXxadsRentalContractEO() {
        return (XxadsRentalContractEOImpl) getEntity(ENTITY_XXADSRENTALCONTRACTEO);
    }

    /**
     * Gets the attribute value for ACTIVE_FLAG using the alias name ActiveFlag.
     * @return the ACTIVE_FLAG
     */
    public String getActiveFlag() {
        return (String) getAttributeInternal(ACTIVEFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTIVE_FLAG using the alias name ActiveFlag.
     * @param value value to set the ACTIVE_FLAG
     */
    public void setActiveFlag(String value) {
        setAttributeInternal(ACTIVEFLAG, value);
    }

    /**
     * Gets the attribute value for CATEGORY_ID using the alias name CategoryId.
     * @return the CATEGORY_ID
     */
    public Number getCategoryId() {
        return (Number) getAttributeInternal(CATEGORYID);
    }

    /**
     * Sets <code>value</code> as attribute value for CATEGORY_ID using the alias name CategoryId.
     * @param value value to set the CATEGORY_ID
     */
    public void setCategoryId(Number value) {
        setAttributeInternal(CATEGORYID, value);
    }

    /**
     * Gets the attribute value for CONTRACT_ID using the alias name ContractId.
     * @return the CONTRACT_ID
     */
    public Number getContractId() {
        return (Number) getAttributeInternal(CONTRACTID);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_ID using the alias name ContractId.
     * @param value value to set the CONTRACT_ID
     */
    public void setContractId(Number value) {
        setAttributeInternal(CONTRACTID, value);
    }

    /**
     * Gets the attribute value for CONTRACT_LINE_ID using the alias name ContractLineId.
     * @return the CONTRACT_LINE_ID
     */
    public Number getContractLineId() {
        return (Number) getAttributeInternal(CONTRACTLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_LINE_ID using the alias name ContractLineId.
     * @param value value to set the CONTRACT_LINE_ID
     */
    public void setContractLineId(Number value) {
        setAttributeInternal(CONTRACTLINEID, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for FUEL_OPTION using the alias name FuelOption.
     * @return the FUEL_OPTION
     */
    public String getFuelOption() {
        return (String) getAttributeInternal(FUELOPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for FUEL_OPTION using the alias name FuelOption.
     * @param value value to set the FUEL_OPTION
     */
    public void setFuelOption(String value) {
        setAttributeInternal(FUELOPTION, value);
    }

    /**
     * Gets the attribute value for HIRING_BASIS_RULE_ID using the alias name HiringBasisRuleId.
     * @return the HIRING_BASIS_RULE_ID
     */
    public Number getHiringBasisRuleId() {
        return (Number) getAttributeInternal(HIRINGBASISRULEID);
    }

    /**
     * Sets <code>value</code> as attribute value for HIRING_BASIS_RULE_ID using the alias name HiringBasisRuleId.
     * @param value value to set the HIRING_BASIS_RULE_ID
     */
    public void setHiringBasisRuleId(Number value) {
        setAttributeInternal(HIRINGBASISRULEID, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Gets the attribute value for LINE_NUM using the alias name LineNum.
     * @return the LINE_NUM
     */
    public Number getLineNum() {
        return (Number) getAttributeInternal(LINENUM);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_NUM using the alias name LineNum.
     * @param value value to set the LINE_NUM
     */
    public void setLineNum(Number value) {
        setAttributeInternal(LINENUM, value);
    }

    /**
     * Gets the attribute value for LINE_VALUE using the alias name LineValue.
     * @return the LINE_VALUE
     */
    public Number getLineValue() {
        return (Number) getAttributeInternal(LINEVALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_VALUE using the alias name LineValue.
     * @param value value to set the LINE_VALUE
     */
    public void setLineValue(Number value) {
        
        oracle.jbo.domain.Number zero = new oracle.jbo.domain.Number(0);
        Long days = 0L;
        if(getOnHireDate()!= null && getOffHireDate()!= null){
            days = (getOffHireDate().getValue().getTime() - getOnHireDate().getValue().getTime())/(1000*24*60*60);
            days = days + 1L;
        }
        
        oracle.jbo.domain.Number val = ((((getUnitRate() != null ? getUnitRate(): zero))
                                            .multiply((getQuantity() != null ? getQuantity(): zero))
                                        )
                                            .divide((getTransNoofDays() != null && getTransNoofDays() != zero ? getTransNoofDays(): new Number(1)))
                                       )
                                            .multiply(days);
        setAttributeInternal(LINEVALUE, val);
        setVatTaxAmount(new oracle.jbo.domain.Number(0));
    }

    /**
     * Gets the attribute value for MASTER_CONTRACT_ID using the alias name MasterContractId.
     * @return the MASTER_CONTRACT_ID
     */
    public Number getMasterContractId() {
        return (Number) getAttributeInternal(MASTERCONTRACTID);
    }

    /**
     * Sets <code>value</code> as attribute value for MASTER_CONTRACT_ID using the alias name MasterContractId.
     * @param value value to set the MASTER_CONTRACT_ID
     */
    public void setMasterContractId(Number value) {
        setAttributeInternal(MASTERCONTRACTID, value);
    }

    /**
     * Gets the attribute value for MASTER_CONTRACT_LINE_ID using the alias name MasterContractLineId.
     * @return the MASTER_CONTRACT_LINE_ID
     */
    public Number getMasterContractLineId() {
        return (Number) getAttributeInternal(MASTERCONTRACTLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for MASTER_CONTRACT_LINE_ID using the alias name MasterContractLineId.
     * @param value value to set the MASTER_CONTRACT_LINE_ID
     */
    public void setMasterContractLineId(Number value) {
        setAttributeInternal(MASTERCONTRACTLINEID, value);
    }

    /**
     * Gets the attribute value for MIN_CHARGE_UNIT using the alias name MinChargeUnit.
     * @return the MIN_CHARGE_UNIT
     */
    public String getMinChargeUnit() {
        return (String) getAttributeInternal(MINCHARGEUNIT);
    }

    /**
     * Sets <code>value</code> as attribute value for MIN_CHARGE_UNIT using the alias name MinChargeUnit.
     * @param value value to set the MIN_CHARGE_UNIT
     */
    public void setMinChargeUnit(String value) {
        setAttributeInternal(MINCHARGEUNIT, value);
    }

    /**
     * Gets the attribute value for MIN_CHARGE_VALUE using the alias name MinChargeValue.
     * @return the MIN_CHARGE_VALUE
     */
    public Number getMinChargeValue() {
        return (Number) getAttributeInternal(MINCHARGEVALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for MIN_CHARGE_VALUE using the alias name MinChargeValue.
     * @param value value to set the MIN_CHARGE_VALUE
     */
    public void setMinChargeValue(Number value) {
        setAttributeInternal(MINCHARGEVALUE, value);
    }

    /**
     * Gets the attribute value for MOBILIZATION_REQUIRED using the alias name MobilizationRequired.
     * @return the MOBILIZATION_REQUIRED
     */
    public String getMobilizationRequired() {
        return (String) getAttributeInternal(MOBILIZATIONREQUIRED);
    }

    /**
     * Sets <code>value</code> as attribute value for MOBILIZATION_REQUIRED using the alias name MobilizationRequired.
     * @param value value to set the MOBILIZATION_REQUIRED
     */
    public void setMobilizationRequired(String value) {
        setAttributeInternal(MOBILIZATIONREQUIRED, value);
    }

    /**
     * Gets the attribute value for OBJECT_VERSION_NUMBER using the alias name ObjectVersionNumber.
     * @return the OBJECT_VERSION_NUMBER
     */
    public Number getObjectVersionNumber() {
        return (Number) getAttributeInternal(OBJECTVERSIONNUMBER);
    }

    /**
     * Gets the attribute value for OFF_HIRE_DATE using the alias name OffHireDate.
     * @return the OFF_HIRE_DATE
     */
    public Date getOffHireDate() {
        return (Date) getAttributeInternal(OFFHIREDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for OFF_HIRE_DATE using the alias name OffHireDate.
     * @param value value to set the OFF_HIRE_DATE
     */
    public void setOffHireDate(Date value) {
        setAttributeInternal(OFFHIREDATE, value);
        setLineValue(new oracle.jbo.domain.Number(0));
    }

    /**
     * Gets the attribute value for ON_HIRE_DATE using the alias name OnHireDate.
     * @return the ON_HIRE_DATE
     */
    public Date getOnHireDate() {
        return (Date) getAttributeInternal(ONHIREDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for ON_HIRE_DATE using the alias name OnHireDate.
     * @param value value to set the ON_HIRE_DATE
     */
    public void setOnHireDate(Date value) {
        setAttributeInternal(ONHIREDATE, value);
        setLineValue(new oracle.jbo.domain.Number(0));
    }

    /**
     * Gets the attribute value for OPERATOR_OPTION using the alias name OperatorOption.
     * @return the OPERATOR_OPTION
     */
    public String getOperatorOption() {
        return (String) getAttributeInternal(OPERATOROPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for OPERATOR_OPTION using the alias name OperatorOption.
     * @param value value to set the OPERATOR_OPTION
     */
    public void setOperatorOption(String value) {
        setAttributeInternal(OPERATOROPTION, value);
    }

    /**
     * Gets the attribute value for OT1_RATE using the alias name Ot1Rate.
     * @return the OT1_RATE
     */
    public Number getOt1Rate() {
        return (Number) getAttributeInternal(OT1RATE);
    }

    /**
     * Sets <code>value</code> as attribute value for OT1_RATE using the alias name Ot1Rate.
     * @param value value to set the OT1_RATE
     */
    public void setOt1Rate(Number value) {
        setAttributeInternal(OT1RATE, value);
    }

    /**
     * Gets the attribute value for OT2_RATE using the alias name Ot2Rate.
     * @return the OT2_RATE
     */
    public Number getOt2Rate() {
        return (Number) getAttributeInternal(OT2RATE);
    }

    /**
     * Sets <code>value</code> as attribute value for OT2_RATE using the alias name Ot2Rate.
     * @param value value to set the OT2_RATE
     */
    public void setOt2Rate(Number value) {
        setAttributeInternal(OT2RATE, value);
    }

    /**
     * Gets the attribute value for PARENT_CONTRACT_ID using the alias name ParentContractId.
     * @return the PARENT_CONTRACT_ID
     */
    public Number getParentContractId() {
        return (Number) getAttributeInternal(PARENTCONTRACTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PARENT_CONTRACT_ID using the alias name ParentContractId.
     * @param value value to set the PARENT_CONTRACT_ID
     */
    public void setParentContractId(Number value) {
        setAttributeInternal(PARENTCONTRACTID, value);
    }

    /**
     * Gets the attribute value for PARENT_CONTRACT_LINE_ID using the alias name ParentContractLineId.
     * @return the PARENT_CONTRACT_LINE_ID
     */
    public Number getParentContractLineId() {
        return (Number) getAttributeInternal(PARENTCONTRACTLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for PARENT_CONTRACT_LINE_ID using the alias name ParentContractLineId.
     * @param value value to set the PARENT_CONTRACT_LINE_ID
     */
    public void setParentContractLineId(Number value) {
        setAttributeInternal(PARENTCONTRACTLINEID, value);
    }

    /**
     * Gets the attribute value for QUANTITY using the alias name Quantity.
     * @return the QUANTITY
     */
    public Number getQuantity() {
        return (Number) getAttributeInternal(QUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for QUANTITY using the alias name Quantity.
     * @param value value to set the QUANTITY
     */
    public void setQuantity(Number value) {
        setAttributeInternal(QUANTITY, value);
        setLineValue(new oracle.jbo.domain.Number(0));
    }

    /**
     * Gets the attribute value for REFERENCE_ID using the alias name ReferenceId.
     * @return the REFERENCE_ID
     */
    public Number getReferenceId() {
        return (Number) getAttributeInternal(REFERENCEID);
    }

    /**
     * Sets <code>value</code> as attribute value for REFERENCE_ID using the alias name ReferenceId.
     * @param value value to set the REFERENCE_ID
     */
    public void setReferenceId(Number value) {
        setAttributeInternal(REFERENCEID, value);
    }

    /**
     * Gets the attribute value for REFERENCE_LINE_ID using the alias name ReferenceLineId.
     * @return the REFERENCE_LINE_ID
     */
    public Number getReferenceLineId() {
        return (Number) getAttributeInternal(REFERENCELINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for REFERENCE_LINE_ID using the alias name ReferenceLineId.
     * @param value value to set the REFERENCE_LINE_ID
     */
    public void setReferenceLineId(Number value) {
        setAttributeInternal(REFERENCELINEID, value);
    }

    /**
     * Gets the attribute value for REFERENCE_LINE_NUM using the alias name ReferenceLineNum.
     * @return the REFERENCE_LINE_NUM
     */
    public Number getReferenceLineNum() {
        return (Number) getAttributeInternal(REFERENCELINENUM);
    }

    /**
     * Sets <code>value</code> as attribute value for REFERENCE_LINE_NUM using the alias name ReferenceLineNum.
     * @param value value to set the REFERENCE_LINE_NUM
     */
    public void setReferenceLineNum(Number value) {
        setAttributeInternal(REFERENCELINENUM, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for RENTAL_TYPE using the alias name RentalType.
     * @return the RENTAL_TYPE
     */
    public String getRentalType() {
        return (String) getAttributeInternal(RENTALTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for RENTAL_TYPE using the alias name RentalType.
     * @param value value to set the RENTAL_TYPE
     */
    public void setRentalType(String value) {
        setAttributeInternal(RENTALTYPE, value);
    }

    /**
     * Gets the attribute value for SHIFT using the alias name Shift.
     * @return the SHIFT
     */
    public String getShift() {
        return (String) getAttributeInternal(SHIFT);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIFT using the alias name Shift.
     * @param value value to set the SHIFT
     */
    public void setShift(String value) {
        setAttributeInternal(SHIFT, value);
    }

    /**
     * Gets the attribute value for STANDARD_RATE using the alias name StandardRate.
     * @return the STANDARD_RATE
     */
    public Number getStandardRate() {
        return (Number) getAttributeInternal(STANDARDRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for STANDARD_RATE using the alias name StandardRate.
     * @param value value to set the STANDARD_RATE
     */
    public void setStandardRate(Number value) {
        setAttributeInternal(STANDARDRATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransRentalType.
     * @return the TransRentalType
     */
    public String getTransRentalType() {
        return (String) getAttributeInternal(TRANSRENTALTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransRentalType.
     * @param value value to set the  TransRentalType
     */
    public void setTransRentalType(String value) {
        setAttributeInternal(TRANSRENTALTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransCategory.
     * @return the TransCategory
     */
    public String getTransCategory() {
        return (String) getAttributeInternal(TRANSCATEGORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransCategory.
     * @param value value to set the  TransCategory
     */
    public void setTransCategory(String value) {
        setAttributeInternal(TRANSCATEGORY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransCategoryDescription.
     * @return the TransCategoryDescription
     */
    public String getTransCategoryDescription() {
        return (String) getAttributeInternal(TRANSCATEGORYDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransCategoryDescription.
     * @param value value to set the  TransCategoryDescription
     */
    public void setTransCategoryDescription(String value) {
        setAttributeInternal(TRANSCATEGORYDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransHiringBasis.
     * @return the TransHiringBasis
     */
    public String getTransHiringBasis() {
        return (String) getAttributeInternal(TRANSHIRINGBASIS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransHiringBasis.
     * @param value value to set the  TransHiringBasis
     */
    public void setTransHiringBasis(String value) {
        setAttributeInternal(TRANSHIRINGBASIS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransFixedVariable.
     * @return the TransFixedVariable
     */
    public String getTransFixedVariable() {
        return (String) getAttributeInternal(TRANSFIXEDVARIABLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransFixedVariable.
     * @param value value to set the  TransFixedVariable
     */
    public void setTransFixedVariable(String value) {
        setAttributeInternal(TRANSFIXEDVARIABLE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransOperatorOption.
     * @return the TransOperatorOption
     */
    public String getTransOperatorOption() {
        return (String) getAttributeInternal(TRANSOPERATOROPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransOperatorOption.
     * @param value value to set the  TransOperatorOption
     */
    public void setTransOperatorOption(String value) {
        setAttributeInternal(TRANSOPERATOROPTION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransFuelOption.
     * @return the TransFuelOption
     */
    public String getTransFuelOption() {
        return (String) getAttributeInternal(TRANSFUELOPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransFuelOption.
     * @param value value to set the  TransFuelOption
     */
    public void setTransFuelOption(String value) {
        setAttributeInternal(TRANSFUELOPTION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransMobilizationRequired.
     * @return the TransMobilizationRequired
     */
    public String getTransMobilizationRequired() {
        return (String) getAttributeInternal(TRANSMOBILIZATIONREQUIRED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransMobilizationRequired.
     * @param value value to set the  TransMobilizationRequired
     */
    public void setTransMobilizationRequired(String value) {
        setAttributeInternal(TRANSMOBILIZATIONREQUIRED, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransShift.
     * @return the TransShift
     */
    public String getTransShift() {
        return (String) getAttributeInternal(TRANSSHIFT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransShift.
     * @param value value to set the  TransShift
     */
    public void setTransShift(String value) {
        setAttributeInternal(TRANSSHIFT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransMinChargeUnit.
     * @return the TransMinChargeUnit
     */
    public String getTransMinChargeUnit() {
        return (String) getAttributeInternal(TRANSMINCHARGEUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransMinChargeUnit.
     * @param value value to set the  TransMinChargeUnit
     */
    public void setTransMinChargeUnit(String value) {
        setAttributeInternal(TRANSMINCHARGEUNIT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransReferenceNumber.
     * @return the TransReferenceNumber
     */
    public String getTransReferenceNumber() {
        return (String) getAttributeInternal(TRANSREFERENCENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransReferenceNumber.
     * @param value value to set the  TransReferenceNumber
     */
    public void setTransReferenceNumber(String value) {
        setAttributeInternal(TRANSREFERENCENUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransHdrSrcBuId.
     * @return the TransHdrSrcBuId
     */
    public Number getTransHdrSrcBuId() {
        if(getAttributeInternal(TRANSHDRSRCBUID) == null){
            return getSrcBuId();
        }
        return (Number) getAttributeInternal(TRANSHDRSRCBUID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransHdrSrcBuId.
     * @param value value to set the  TransHdrSrcBuId
     */
    public void setTransHdrSrcBuId(Number value) {
        setAttributeInternal(TRANSHDRSRCBUID, value);
    }

    /**
     * Gets the attribute value for SRC_BU_ID using the alias name SrcBuId.
     * @return the SRC_BU_ID
     */
    public Number getSrcBuId() {
        return (Number) getAttributeInternal(SRCBUID);
    }

    /**
     * Sets <code>value</code> as attribute value for SRC_BU_ID using the alias name SrcBuId.
     * @param value value to set the SRC_BU_ID
     */
    public void setSrcBuId(Number value) {
        setAttributeInternal(SRCBUID, value);
    }

    /**
     * Gets the attribute value for CONTRACT_ID using the alias name ContractId1.
     * @return the CONTRACT_ID
     */
    public Number getContractId1() {
        return (Number) getAttributeInternal(CONTRACTID1);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_ID using the alias name ContractId1.
     * @param value value to set the CONTRACT_ID
     */
    public void setContractId1(Number value) {
        setAttributeInternal(CONTRACTID1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransHdrContractSource.
     * @return the TransHdrContractSource
     */
    public String getTransHdrContractSource() {
        if(getAttributeInternal(TRANSHDRCONTRACTSOURCE) == null){
            return getContractSource();
        }
        return (String) getAttributeInternal(TRANSHDRCONTRACTSOURCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransHdrContractSource.
     * @param value value to set the  TransHdrContractSource
     */
    public void setTransHdrContractSource(String value) {
        setAttributeInternal(TRANSHDRCONTRACTSOURCE, value);
    }

    /**
     * Gets the attribute value for CONTRACT_SOURCE using the alias name ContractSource.
     * @return the CONTRACT_SOURCE
     */
    public String getContractSource() {
        return (String) getAttributeInternal(CONTRACTSOURCE);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_SOURCE using the alias name ContractSource.
     * @param value value to set the CONTRACT_SOURCE
     */
    public void setContractSource(String value) {
        setAttributeInternal(CONTRACTSOURCE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransHdrSrcDivFlexValId.
     * @return the TransHdrSrcDivFlexValId
     */
    public Number getTransHdrSrcDivFlexValId() {
        if(getAttributeInternal(TRANSHDRSRCDIVFLEXVALID) == null){
            return getSrcDivFlexValId();
        }
        return (Number) getAttributeInternal(TRANSHDRSRCDIVFLEXVALID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransHdrSrcDivFlexValId.
     * @param value value to set the  TransHdrSrcDivFlexValId
     */
    public void setTransHdrSrcDivFlexValId(Number value) {
        setAttributeInternal(TRANSHDRSRCDIVFLEXVALID, value);
    }

    /**
     * Gets the attribute value for SRC_DIV_FLEX_VAL_ID using the alias name SrcDivFlexValId.
     * @return the SRC_DIV_FLEX_VAL_ID
     */
    public Number getSrcDivFlexValId() {
        return (Number) getAttributeInternal(SRCDIVFLEXVALID);
    }

    /**
     * Sets <code>value</code> as attribute value for SRC_DIV_FLEX_VAL_ID using the alias name SrcDivFlexValId.
     * @param value value to set the SRC_DIV_FLEX_VAL_ID
     */
    public void setSrcDivFlexValId(Number value) {
        setAttributeInternal(SRCDIVFLEXVALID, value);
    }

    /**
     * Gets the attribute value for MASTER_REF_LINE_ID using the alias name MasterRefLineId.
     * @return the MASTER_REF_LINE_ID
     */
    public Number getMasterRefLineId() {
        return (Number) getAttributeInternal(MASTERREFLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for MASTER_REF_LINE_ID using the alias name MasterRefLineId.
     * @param value value to set the MASTER_REF_LINE_ID
     */
    public void setMasterRefLineId(Number value) {
        setAttributeInternal(MASTERREFLINEID, value);
    }
        
    /**
         * Gets the attribute value for the calculated attribute TransTotalAmount.
         * @return the TransTotalAmount
         */
        public Number getTransTotalAmount() {
            return (Number) getAttributeInternal(TRANSTOTALAMOUNT);
        }

        /**
         * Sets <code>value</code> as the attribute value for the calculated attribute TransTotalAmount.
         * @param value value to set the  TransTotalAmount
         */
        public void setTransTotalAmount(Number value) {
            setAttributeInternal(TRANSTOTALAMOUNT, value);
        }

    /**
     * Gets the attribute value for UNIT_RATE using the alias name UnitRate.
     * @return the UNIT_RATE
     */
    public Number getUnitRate() {
        return (Number) getAttributeInternal(UNITRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for UNIT_RATE using the alias name UnitRate.
     * @param value value to set the UNIT_RATE
     */
    public void setUnitRate(Number value) {
        setAttributeInternal(UNITRATE, value);
        setLineValue(new oracle.jbo.domain.Number(0));
    }

    /**
     * Gets the attribute value for the calculated attribute TransNoofHours.
     * @return the TransNoofHours
     */
    public Number getTransNoofDays() {
        return (Number) getAttributeInternal(TRANSNOOFDAYS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransNoofHours.
     * @param value value to set the  TransNoofHours
     */
    public void setTransNoofDays(Number value) {
        setAttributeInternal(TRANSNOOFDAYS, value);
        setLineValue(new oracle.jbo.domain.Number(0));
    }

    /**
     * Gets the attribute value for the calculated attribute TransStandardHours.
     * @return the TransStandardHours
     */
    public Number getTransStandardHours() {
        return (Number) getAttributeInternal(TRANSSTANDARDHOURS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransStandardHours.
     * @param value value to set the  TransStandardHours
     */
    public void setTransStandardHours(Number value) {
        setAttributeInternal(TRANSSTANDARDHOURS, value);
    }

    /**
     * Gets the attribute value for TAX_RATE_ID using the alias name TaxRateId.
     * @return the TAX_RATE_ID
     */
    public Number getTaxRateId() {
        return (Number) getAttributeInternal(TAXRATEID);
    }

    /**
     * Sets <code>value</code> as attribute value for TAX_RATE_ID using the alias name TaxRateId.
     * @param value value to set the TAX_RATE_ID
     */
    public void setTaxRateId(Number value) {
        setAttributeInternal(TAXRATEID, value);
    }

    /**
     * Gets the attribute value for TAX_RATE_CODE using the alias name TaxRateCode.
     * @return the TAX_RATE_CODE
     */
    public String getTaxRateCode() {
        return (String) getAttributeInternal(TAXRATECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for TAX_RATE_CODE using the alias name TaxRateCode.
     * @param value value to set the TAX_RATE_CODE
     */
    public void setTaxRateCode(String value) {
        setAttributeInternal(TAXRATECODE, value);
    }

    /**
     * Gets the attribute value for TAX_RATE_PERCENT using the alias name TaxRatePercent.
     * @return the TAX_RATE_PERCENT
     */
    public Number getTaxRatePercent() {
        return (Number) getAttributeInternal(TAXRATEPERCENT);
    }

    /**
     * Sets <code>value</code> as attribute value for TAX_RATE_PERCENT using the alias name TaxRatePercent.
     * @param value value to set the TAX_RATE_PERCENT
     */
    public void setTaxRatePercent(Number value) {
        setAttributeInternal(TAXRATEPERCENT, value);
        setVatTaxAmount(new oracle.jbo.domain.Number(0));
    }

    /**
     * Gets the attribute value for VAT_TAX_AMOUNT using the alias name VatTaxAmount.
     * @return the VAT_TAX_AMOUNT
     */
    public Number getVatTaxAmount() {
        return (Number) getAttributeInternal(VATTAXAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for VAT_TAX_AMOUNT using the alias name VatTaxAmount.
     * @param value value to set the VAT_TAX_AMOUNT
     */
    public void setVatTaxAmount(Number value) {
        oracle.jbo.domain.Number zero = new oracle.jbo.domain.Number(0);
        oracle.jbo.domain.Number val = ((getTaxRatePercent() != null ? getTaxRatePercent(): zero).divide(100)
                                            .multiply(getLineValue() != null ? getLineValue(): zero));
        setAttributeInternal(VATTAXAMOUNT, val);
    }

    /**
     * Gets the attribute value for the calculated attribute TransNetAmount.
     * @return the TransNetAmount
     */
    public Number getTransNetAmount() {
        return (Number) getAttributeInternal(TRANSNETAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransNetAmount.
     * @param value value to set the  TransNetAmount
     */
    public void setTransNetAmount(Number value) {
        setAttributeInternal(TRANSNETAMOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransProjectId.
     * @return the TransProjectId
     */
    public Number getTransProjectId() {
        if(getProjectId()!= null){
            return getProjectId();
        }
        return (Number) getAttributeInternal(TRANSPROJECTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransProjectId.
     * @param value value to set the  TransProjectId
     */
    public void setTransProjectId(Number value) {
        setAttributeInternal(TRANSPROJECTID, value);
    }


    /**
     * Gets the attribute value for CATEGORY_DESCRIPTION using the alias name CategoryDescription.
     * @return the CATEGORY_DESCRIPTION
     */
    public String getCategoryDescription() {
        return (String) getAttributeInternal(CATEGORYDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for CATEGORY_DESCRIPTION using the alias name CategoryDescription.
     * @param value value to set the CATEGORY_DESCRIPTION
     */
    public void setCategoryDescription(String value) {
        setAttributeInternal(CATEGORYDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for TASK_ID using the alias name TaskId.
     * @return the TASK_ID
     */
    public Number getTaskId() {
        return (Number) getAttributeInternal(TASKID);
    }

    /**
     * Sets <code>value</code> as attribute value for TASK_ID using the alias name TaskId.
     * @param value value to set the TASK_ID
     */
    public void setTaskId(Number value) {
        setAttributeInternal(TASKID, value);
    }

    /**
     * Gets the attribute value for EXPENDITURE_TYPE_ID using the alias name ExpenditureTypeId.
     * @return the EXPENDITURE_TYPE_ID
     */
    public Number getExpenditureTypeId() {
        return (Number) getAttributeInternal(EXPENDITURETYPEID);
    }

    /**
     * Sets <code>value</code> as attribute value for EXPENDITURE_TYPE_ID using the alias name ExpenditureTypeId.
     * @param value value to set the EXPENDITURE_TYPE_ID
     */
    public void setExpenditureTypeId(Number value) {
        setAttributeInternal(EXPENDITURETYPEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransTask.
     * @return the TransTask
     */
    public String getTransTask() {
        return (String) getAttributeInternal(TRANSTASK);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransTask.
     * @param value value to set the  TransTask
     */
    public void setTransTask(String value) {
        setAttributeInternal(TRANSTASK, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransExpenditureDesc.
     * @return the TransExpenditureDesc
     */
    public String getTransExpenditureDesc() {
        return (String) getAttributeInternal(TRANSEXPENDITUREDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransExpenditureDesc.
     * @param value value to set the  TransExpenditureDesc
     */
    public void setTransExpenditureDesc(String value) {
        setAttributeInternal(TRANSEXPENDITUREDESC, value);
    }


    /**
     * Gets the attribute value for the calculated attribute TransSetId.
     * @return the TransSetId
     */
    public Number getTransSetId() {
        return (Number) getAttributeInternal(TRANSSETID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransSetId.
     * @param value value to set the  TransSetId
     */
    public void setTransSetId(Number value) {
        setAttributeInternal(TRANSSETID, value);
    }

    /**
     * Gets the attribute value for PROJECT_ID using the alias name ProjectId.
     * @return the PROJECT_ID
     */
    public Number getProjectId() {
        return (Number) getAttributeInternal(PROJECTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROJECT_ID using the alias name ProjectId.
     * @param value value to set the PROJECT_ID
     */
    public void setProjectId(Number value) {
        setAttributeInternal(PROJECTID, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LookupsLOV1.
     */
    public RowSet getLookupsLOV1() {
        return (RowSet) getAttributeInternal(LOOKUPSLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> RentalTypeBasedCategoryLOV1.
     */
    public RowSet getRentalTypeBasedCategoryLOV1() {
        return (RowSet) getAttributeInternal(RENTALTYPEBASEDCATEGORYLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> HiringBasisLOVVO1.
     */
    public RowSet getHiringBasisLOVVO1() {
        return (RowSet) getAttributeInternal(HIRINGBASISLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> OptionsLOVVO1.
     */
    public RowSet getOptionsLOVVO1() {
        return (RowSet) getAttributeInternal(OPTIONSLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> OptionsLOVVO2.
     */
    public RowSet getOptionsLOVVO2() {
        return (RowSet) getAttributeInternal(OPTIONSLOVVO2);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LookupsLOV2.
     */
    public RowSet getLookupsLOV2() {
        return (RowSet) getAttributeInternal(LOOKUPSLOV2);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LookupsLOV3.
     */
    public RowSet getLookupsLOV3() {
        return (RowSet) getAttributeInternal(LOOKUPSLOV3);
    }

    /**
     * Gets the view accessor <code>RowSet</code> QuoteChargeableUnitLovVO1.
     */
    public RowSet getQuoteChargeableUnitLovVO1() {
        return (RowSet) getAttributeInternal(QUOTECHARGEABLEUNITLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LookupsLOV4.
     */
    public RowSet getLookupsLOV4() {
        return (RowSet) getAttributeInternal(LOOKUPSLOV4);
    }

    /**
     * Gets the view accessor <code>RowSet</code> TasksLOV1.
     */
    public RowSet getTasksLOV1() {
        return (RowSet) getAttributeInternal(TASKSLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ExpenditureTypesLOV1.
     */
    public RowSet getExpenditureTypesLOV1() {
        return (RowSet) getAttributeInternal(EXPENDITURETYPESLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> TaxCodesLOV1.
     */
    public RowSet getTaxCodesLOV1() {
        return (RowSet) getAttributeInternal(TAXCODESLOV1);
    }
}

