package model.view;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 10 17:18:01 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SystemOptionsVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SystemOptionsVOImpl() {
    }
}

