package model.view;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Feb 09 15:30:34 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TermsCondsTemplateVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public TermsCondsTemplateVOImpl() {
    }
}

