package model.view;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 26 12:49:17 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TsSlipNumberValidateVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public TsSlipNumberValidateVOImpl() {
    }
}

