package model.view;

import model.entity.XxadsWeekOffsEOImpl;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 12 10:26:31 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WeekOffDaysVORowImpl extends ViewRowImpl {


    public static final int ENTITY_XXADSWEEKOFFSEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        BuId,
        CreatedBy,
        CreationDate,
        LastUpdateDate,
        LastUpdatedBy,
        ObjectVersionNumber,
        WeekOffDay,
        WeekOffFlag,
        WeekOffId,
        TransWeekOffFlag,
        WeekDaysLOV1,
        LookupsLOV1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BUID = AttributesEnum.BuId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int OBJECTVERSIONNUMBER = AttributesEnum.ObjectVersionNumber.index();
    public static final int WEEKOFFDAY = AttributesEnum.WeekOffDay.index();
    public static final int WEEKOFFFLAG = AttributesEnum.WeekOffFlag.index();
    public static final int WEEKOFFID = AttributesEnum.WeekOffId.index();
    public static final int TRANSWEEKOFFFLAG = AttributesEnum.TransWeekOffFlag.index();
    public static final int WEEKDAYSLOV1 = AttributesEnum.WeekDaysLOV1.index();
    public static final int LOOKUPSLOV1 = AttributesEnum.LookupsLOV1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public WeekOffDaysVORowImpl() {
    }

    /**
     * Gets XxadsWeekOffsEO entity object.
     * @return the XxadsWeekOffsEO
     */
    public XxadsWeekOffsEOImpl getXxadsWeekOffsEO() {
        return (XxadsWeekOffsEOImpl) getEntity(ENTITY_XXADSWEEKOFFSEO);
    }

    /**
     * Gets the attribute value for BU_ID using the alias name BuId.
     * @return the BU_ID
     */
    public Number getBuId() {
        return (Number) getAttributeInternal(BUID);
    }

    /**
     * Sets <code>value</code> as attribute value for BU_ID using the alias name BuId.
     * @param value value to set the BU_ID
     */
    public void setBuId(Number value) {
        setAttributeInternal(BUID, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Gets the attribute value for OBJECT_VERSION_NUMBER using the alias name ObjectVersionNumber.
     * @return the OBJECT_VERSION_NUMBER
     */
    public Number getObjectVersionNumber() {
        return (Number) getAttributeInternal(OBJECTVERSIONNUMBER);
    }

    /**
     * Gets the attribute value for WEEK_OFF_DAY using the alias name WeekOffDay.
     * @return the WEEK_OFF_DAY
     */
    public String getWeekOffDay() {
        return (String) getAttributeInternal(WEEKOFFDAY);
    }

    /**
     * Sets <code>value</code> as attribute value for WEEK_OFF_DAY using the alias name WeekOffDay.
     * @param value value to set the WEEK_OFF_DAY
     */
    public void setWeekOffDay(String value) {
        setAttributeInternal(WEEKOFFDAY, value);
    }

    /**
     * Gets the attribute value for WEEK_OFF_FLAG using the alias name WeekOffFlag.
     * @return the WEEK_OFF_FLAG
     */
    public String getWeekOffFlag() {
        return (String) getAttributeInternal(WEEKOFFFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for WEEK_OFF_FLAG using the alias name WeekOffFlag.
     * @param value value to set the WEEK_OFF_FLAG
     */
    public void setWeekOffFlag(String value) {
        setAttributeInternal(WEEKOFFFLAG, value);
    }

    /**
     * Gets the attribute value for WEEK_OFF_ID using the alias name WeekOffId.
     * @return the WEEK_OFF_ID
     */
    public Number getWeekOffId() {
        return (Number) getAttributeInternal(WEEKOFFID);
    }

    /**
     * Sets <code>value</code> as attribute value for WEEK_OFF_ID using the alias name WeekOffId.
     * @param value value to set the WEEK_OFF_ID
     */
    public void setWeekOffId(Number value) {
        setAttributeInternal(WEEKOFFID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransWeekOffFlag.
     * @return the TransWeekOffFlag
     */
    public String getTransWeekOffFlag() {
        return (String) getAttributeInternal(TRANSWEEKOFFFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransWeekOffFlag.
     * @param value value to set the  TransWeekOffFlag
     */
    public void setTransWeekOffFlag(String value) {
        setAttributeInternal(TRANSWEEKOFFFLAG, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> WeekDaysLOV1.
     */
    public RowSet getWeekDaysLOV1() {
        return (RowSet) getAttributeInternal(WEEKDAYSLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LookupsLOV1.
     */
    public RowSet getLookupsLOV1() {
        return (RowSet) getAttributeInternal(LOOKUPSLOV1);
    }
}

