package model.applicationModule.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 10 17:58:42 IST 2022
// ---------------------------------------------------------------------
public interface SetupAM extends ApplicationModule {
    void addSystemOptions();

    String validateSystemBU();

    String saveSystemOptions();

    String LookUpTypeValueChange();

    void addLokupLine();

    String DeleteLookupLine();

    String lookUpCodeValueChange();

    void createTransWeekExceptionDaysSearch();

    String searchWeekExceptionDays();

    void addExceptionDay();

    void addSpecialWorkingDays();


    String deleteExceptionDay();

    String deleteSpecialWorkingDay();

    String deleteSystemOption();


    String validateExceptionDate();

    void refreshData();

    String addAssetCategory();

    String deleteAssetCategory();

    String createTransBuRow();

    String assetCategoryValueChangeList();

    String addAssetAttribute();

    String deleteAssetAttribute();

    String repCategoryAdd();

    String repCategoryDelete();

    String assetAttributeValueChangeList();

    String repCategoryValueChangeList();

    String createHiringBasisRule();

    String deleteHiringBasisRule();

    String fixedVariableChange();

    String hiringBasisHoursChange();

    String saveHiringBasisRule();

    String saveWeekExceptionDays();

    String validateSpEndDate();

    String validateSpStartDate();

    String createTransBuEmpCatRow();

    String addEmpCategory();

    String deleteEmployeeCategory();

    String hiringBasisDaysChange();

    String hiringBasisChange();

    void createTransAccessSecuritySearch();

    String deleteLookupType();

    String addEmpRepCat();

    String deleteEmpRepCat();

    String addEmpAsstCat();

    String deleteEmpAsstCatMap();

    String acctParamsReqBuChange();

    String acctParamsSetupTypeChange();

    String createAccountingParam();

    String createGroupCustomerMap();

    String createAccParamsTransSearch();

    String searchBuAccountingParams();

    String empCatCodeValChList();

    String repCatValChList();

    String astCatValChList();

    String createRentalRate();

    String searchBuRentalMaster();

    String insertTransRentalMasterRow();

    String rentalMasterUniquenes();

    void addAccessSecurity();

    String accParamsEndDateChange();

    String grpCustEndDateChange();

    String deleteUserSecurity();

    String resetAccessSecuritySearch();

    String searchAccessSecurity();


    String saveAccessSecurity();

    String addSecurityRole();

    String createAsset();

    String editAsset();

    String assetCertTypeChange();

    String assetHierAttchDtChange();

    String assetMasterCategoryChange();

    String assetOperShiftChange();

    String createAssetHierarchy();

    String validateStartDate();

    String duplicatesWarning();

    String createTransAssetSearch();

    String resetAssetSearch();

    String searchAssets();

    String setAssetSearch();

    String assetBuChange();

    String assetSearchBuChange();

    String validateEndDate();

    String validateCustomerType();

    String validateCustomerTypeValues();

    String assetAccessoryTypeChange();
    
    String createTransEmpMasterSearch();

    String deleteEmployee();

    String empSourceChange();

    String resetEmpSearch();

    String searchEmpMaster();

    void resetRentalSearch();

    void searchRentalRates();

    String saveRentalRates();

    String validateAssetRentalHrs();

    String addNewDocSeq();

    String deleteDocSeq();

    String validateSeqDates();

    String validateDocument();

    String validateHiringBasis();

    String empEffectiveFromChange();

    String empEffectiveToChange();

    String validateInternalEmpDuplicates();

    void addNewEmp();

    String validateHiredEmpDuplicates();

    String empNameChange();

    String empCertificateSubTypeChange();

    String empCertFromDateChange();

    String empCertToDateChange();

    String saveEmployee();

    String updateCurrSequence();

    String empCatHrsChange();

    String rentalTypeChange();

    String createTemplate();

    void searchTemplate();

    void createTransTemplateSearch();

    void setCurrentTransTemplateRow();

    String checkDuplicateTemplate();

    String rentalRateUnitRateChange();

    String createDivisionAccMap();

    String startDateDivisonAccMap();

    String endDateDivAccMap();

    String saveStartDateDivisonAccMap();

    String createTransHiringBasisSearch();

    String hbrSearchBuChange();

    String hbrSearchDivChange();

    String TemplateSearchBuChange();

    String templateBuChange();

    String createTransDocumentSeqSearch();

    String dsSearchBuChange();

    String dsSearchDivChange();

    String createDocumentSequence();

    String validateSeqenceDates();

    String saveDocumentSequence();

    String deleteDocumentSeq();

    String updateCurrSeq();

    String validateDocumentSeq();
}

