package model.lov;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 02 10:05:31 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ASFlexValuesLOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ASFlexValuesLOVImpl() {
    }
}

