package model.lov;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 02 18:04:54 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmpCategoryLovVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        EmpCategoryId,
        BuId,
        EmpCategoryCode,
        Description;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int EMPCATEGORYID = AttributesEnum.EmpCategoryId.index();
    public static final int BUID = AttributesEnum.BuId.index();
    public static final int EMPCATEGORYCODE = AttributesEnum.EmpCategoryCode.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();

    /**
     * This is the default constructor (do not remove).
     */
    public EmpCategoryLovVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute EmpCategoryId.
     * @return the EmpCategoryId
     */
    public BigDecimal getEmpCategoryId() {
        return (BigDecimal) getAttributeInternal(EMPCATEGORYID);
    }

    /**
     * Gets the attribute value for the calculated attribute BuId.
     * @return the BuId
     */
    public BigDecimal getBuId() {
        return (BigDecimal) getAttributeInternal(BUID);
    }

    /**
     * Gets the attribute value for the calculated attribute EmpCategoryCode.
     * @return the EmpCategoryCode
     */
    public String getEmpCategoryCode() {
        return (String) getAttributeInternal(EMPCATEGORYCODE);
    }

    /**
     * Gets the attribute value for the calculated attribute Description.
     * @return the Description
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }
}

