package model.lov;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 29 11:15:46 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class QuotationLineTypeLOVVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public QuotationLineTypeLOVVOImpl() {
    }
}

