package model.lov;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 16 12:17:08 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ReqBuBasedProjectLovVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        BuId,
        CarryingOutOrganizationId,
        Description,
        EndDate,
        ProjectCurrencyCode,
        ProjectId,
        CodeDesc,
        ProjectNumber,
        ProjectName,
        ProjectStatusCode,
        StartDate,
        TemplateFlag;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BUID = AttributesEnum.BuId.index();
    public static final int CARRYINGOUTORGANIZATIONID = AttributesEnum.CarryingOutOrganizationId.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int ENDDATE = AttributesEnum.EndDate.index();
    public static final int PROJECTCURRENCYCODE = AttributesEnum.ProjectCurrencyCode.index();
    public static final int PROJECTID = AttributesEnum.ProjectId.index();
    public static final int CODEDESC = AttributesEnum.CodeDesc.index();
    public static final int PROJECTNUMBER = AttributesEnum.ProjectNumber.index();
    public static final int PROJECTNAME = AttributesEnum.ProjectName.index();
    public static final int PROJECTSTATUSCODE = AttributesEnum.ProjectStatusCode.index();
    public static final int STARTDATE = AttributesEnum.StartDate.index();
    public static final int TEMPLATEFLAG = AttributesEnum.TemplateFlag.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ReqBuBasedProjectLovVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute BuId.
     * @return the BuId
     */
    public oracle.jbo.domain.Number getBuId() {
        return (oracle.jbo.domain.Number) getAttributeInternal(BUID);
    }

    /**
     * Gets the attribute value for the calculated attribute CarryingOutOrganizationId.
     * @return the CarryingOutOrganizationId
     */
    public Number getCarryingOutOrganizationId() {
        return (Number) getAttributeInternal(CARRYINGOUTORGANIZATIONID);
    }

    /**
     * Gets the attribute value for the calculated attribute Description.
     * @return the Description
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Gets the attribute value for the calculated attribute EndDate.
     * @return the EndDate
     */
    public Date getEndDate() {
        return (Date) getAttributeInternal(ENDDATE);
    }

    /**
     * Gets the attribute value for the calculated attribute ProjectCurrencyCode.
     * @return the ProjectCurrencyCode
     */
    public String getProjectCurrencyCode() {
        return (String) getAttributeInternal(PROJECTCURRENCYCODE);
    }

    /**
     * Gets the attribute value for the calculated attribute ProjectId.
     * @return the ProjectId
     */
    public Number getProjectId() {
        return (Number) getAttributeInternal(PROJECTID);
    }

    /**
     * Gets the attribute value for the calculated attribute CodeDesc.
     * @return the CodeDesc
     */
    public String getCodeDesc() {
        return (String) getAttributeInternal(CODEDESC);
    }

    /**
     * Gets the attribute value for the calculated attribute ProjectNumber.
     * @return the ProjectNumber
     */
    public String getProjectNumber() {
        return (String) getAttributeInternal(PROJECTNUMBER);
    }

    /**
     * Gets the attribute value for the calculated attribute ProjectName.
     * @return the ProjectName
     */
    public String getProjectName() {
        return (String) getAttributeInternal(PROJECTNAME);
    }

    /**
     * Gets the attribute value for the calculated attribute ProjectStatusCode.
     * @return the ProjectStatusCode
     */
    public String getProjectStatusCode() {
        return (String) getAttributeInternal(PROJECTSTATUSCODE);
    }

    /**
     * Gets the attribute value for the calculated attribute StartDate.
     * @return the StartDate
     */
    public Date getStartDate() {
        return (Date) getAttributeInternal(STARTDATE);
    }

    /**
     * Gets the attribute value for the calculated attribute TemplateFlag.
     * @return the TemplateFlag
     */
    public String getTemplateFlag() {
        return (String) getAttributeInternal(TEMPLATEFLAG);
    }
}

