package model.lov;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 17 11:36:59 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TasksLOVRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        TaskNumber,
        ChargeableFlag,
        ProjectId,
        TaskId,
        TaskName,
        BuId,
        ProjectId1,
        BuId1,
        SetId;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int TASKNUMBER = AttributesEnum.TaskNumber.index();
    public static final int CHARGEABLEFLAG = AttributesEnum.ChargeableFlag.index();
    public static final int PROJECTID = AttributesEnum.ProjectId.index();
    public static final int TASKID = AttributesEnum.TaskId.index();
    public static final int TASKNAME = AttributesEnum.TaskName.index();
    public static final int BUID = AttributesEnum.BuId.index();
    public static final int PROJECTID1 = AttributesEnum.ProjectId1.index();
    public static final int BUID1 = AttributesEnum.BuId1.index();
    public static final int SETID = AttributesEnum.SetId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TasksLOVRowImpl() {
    }
}

