package model.entity;

import java.math.BigDecimal;

import java.sql.Timestamp;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.NClobDomain;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 11 15:38:10 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxadsAssetRequestEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        RequestId,
        RequestNumber,
        RequestType,
        RequestorBuId,
        SourceBuId,
        SrcDivision,
        SrcDivFlexValueId,
        SrcDivFlexValSetId,
        RequestedDate,
        RequestorId,
        CustomerType,
        ProjectId,
        Division,
        DivFlexValueId,
        DivFlexValueSetId,
        DepartmentName,
        DepartmentCode,
        DeptFlexValueId,
        DeptFlexValueSetId,
        CustomerId,
        CustSiteId,
        SiteUseId,
        PreparedOn,
        PreparedBy,
        RequestStatus,
        ApprovedDate,
        Note,
        SubmittedBy,
        SubmittedDate,
        CreationDate,
        CreatedBy,
        LastUpdateDate,
        LastUpdatedBy,
        ObjectVersionNumber,
        XxadsAssetRequestLinesEO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    private static final byte USERNAME_HISTORY_TYPE = 13;


    public static final int REQUESTID = AttributesEnum.RequestId.index();
    public static final int REQUESTNUMBER = AttributesEnum.RequestNumber.index();
    public static final int REQUESTTYPE = AttributesEnum.RequestType.index();
    public static final int REQUESTORBUID = AttributesEnum.RequestorBuId.index();
    public static final int SOURCEBUID = AttributesEnum.SourceBuId.index();
    public static final int SRCDIVISION = AttributesEnum.SrcDivision.index();
    public static final int SRCDIVFLEXVALUEID = AttributesEnum.SrcDivFlexValueId.index();
    public static final int SRCDIVFLEXVALSETID = AttributesEnum.SrcDivFlexValSetId.index();
    public static final int REQUESTEDDATE = AttributesEnum.RequestedDate.index();
    public static final int REQUESTORID = AttributesEnum.RequestorId.index();
    public static final int CUSTOMERTYPE = AttributesEnum.CustomerType.index();
    public static final int PROJECTID = AttributesEnum.ProjectId.index();
    public static final int DIVISION = AttributesEnum.Division.index();
    public static final int DIVFLEXVALUEID = AttributesEnum.DivFlexValueId.index();
    public static final int DIVFLEXVALUESETID = AttributesEnum.DivFlexValueSetId.index();
    public static final int DEPARTMENTNAME = AttributesEnum.DepartmentName.index();
    public static final int DEPARTMENTCODE = AttributesEnum.DepartmentCode.index();
    public static final int DEPTFLEXVALUEID = AttributesEnum.DeptFlexValueId.index();
    public static final int DEPTFLEXVALUESETID = AttributesEnum.DeptFlexValueSetId.index();
    public static final int CUSTOMERID = AttributesEnum.CustomerId.index();
    public static final int CUSTSITEID = AttributesEnum.CustSiteId.index();
    public static final int SITEUSEID = AttributesEnum.SiteUseId.index();
    public static final int PREPAREDON = AttributesEnum.PreparedOn.index();
    public static final int PREPAREDBY = AttributesEnum.PreparedBy.index();
    public static final int REQUESTSTATUS = AttributesEnum.RequestStatus.index();
    public static final int APPROVEDDATE = AttributesEnum.ApprovedDate.index();
    public static final int NOTE = AttributesEnum.Note.index();
    public static final int SUBMITTEDBY = AttributesEnum.SubmittedBy.index();
    public static final int SUBMITTEDDATE = AttributesEnum.SubmittedDate.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int OBJECTVERSIONNUMBER = AttributesEnum.ObjectVersionNumber.index();
    public static final int XXADSASSETREQUESTLINESEO = AttributesEnum.XxadsAssetRequestLinesEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxadsAssetRequestEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.entity.XxadsAssetRequestEO");
    }

    @Override
    protected Object getHistoryContextForAttribute(AttributeDefImpl attr) {
        if (attr.getHistoryKind() == USERNAME_HISTORY_TYPE) {
                // Custom History type logic goes here
                return (String)((Map)ADFContext.getCurrent().getSessionScope().get("userMap")).get("UserName");
        }
        return super.getHistoryContextForAttribute(attr);
    }


    /**
     * Gets the attribute value for RequestId, using the alias name RequestId.
     * @return the value of RequestId
     */
    public oracle.jbo.domain.Number getRequestId() {
        return (oracle.jbo.domain.Number) getAttributeInternal(REQUESTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RequestId.
     * @param value value to set the RequestId
     */
    public void setRequestId(oracle.jbo.domain.Number value) {
        setAttributeInternal(REQUESTID, value);
    }

    /**
     * Gets the attribute value for RequestNumber, using the alias name RequestNumber.
     * @return the value of RequestNumber
     */
    public String getRequestNumber() {
        return (String) getAttributeInternal(REQUESTNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for RequestNumber.
     * @param value value to set the RequestNumber
     */
    public void setRequestNumber(String value) {
        setAttributeInternal(REQUESTNUMBER, value);
    }

    /**
     * Gets the attribute value for RequestType, using the alias name RequestType.
     * @return the value of RequestType
     */
    public String getRequestType() {
        return (String) getAttributeInternal(REQUESTTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for RequestType.
     * @param value value to set the RequestType
     */
    public void setRequestType(String value) {
        setAttributeInternal(REQUESTTYPE, value);
    }

    /**
     * Gets the attribute value for RequestorBuId, using the alias name RequestorBuId.
     * @return the value of RequestorBuId
     */
    public Number getRequestorBuId() {
        return (Number) getAttributeInternal(REQUESTORBUID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RequestorBuId.
     * @param value value to set the RequestorBuId
     */
    public void setRequestorBuId(Number value) {
        setAttributeInternal(REQUESTORBUID, value);
    }

    /**
     * Gets the attribute value for SourceBuId, using the alias name SourceBuId.
     * @return the value of SourceBuId
     */
    public Number getSourceBuId() {
        return (Number) getAttributeInternal(SOURCEBUID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SourceBuId.
     * @param value value to set the SourceBuId
     */
    public void setSourceBuId(Number value) {
        setAttributeInternal(SOURCEBUID, value);
    }

    /**
     * Gets the attribute value for SrcDivision, using the alias name SrcDivision.
     * @return the value of SrcDivision
     */
    public String getSrcDivision() {
        return (String) getAttributeInternal(SRCDIVISION);
    }

    /**
     * Sets <code>value</code> as the attribute value for SrcDivision.
     * @param value value to set the SrcDivision
     */
    public void setSrcDivision(String value) {
        setAttributeInternal(SRCDIVISION, value);
    }

    /**
     * Gets the attribute value for SrcDivFlexValueId, using the alias name SrcDivFlexValueId.
     * @return the value of SrcDivFlexValueId
     */
    public Number getSrcDivFlexValueId() {
        return (Number) getAttributeInternal(SRCDIVFLEXVALUEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SrcDivFlexValueId.
     * @param value value to set the SrcDivFlexValueId
     */
    public void setSrcDivFlexValueId(Number value) {
        setAttributeInternal(SRCDIVFLEXVALUEID, value);
    }

    /**
     * Gets the attribute value for SrcDivFlexValSetId, using the alias name SrcDivFlexValSetId.
     * @return the value of SrcDivFlexValSetId
     */
    public Number getSrcDivFlexValSetId() {
        return (Number) getAttributeInternal(SRCDIVFLEXVALSETID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SrcDivFlexValSetId.
     * @param value value to set the SrcDivFlexValSetId
     */
    public void setSrcDivFlexValSetId(Number value) {
        setAttributeInternal(SRCDIVFLEXVALSETID, value);
    }

    /**
     * Gets the attribute value for RequestedDate, using the alias name RequestedDate.
     * @return the value of RequestedDate
     */
    public Date getRequestedDate() {
        return (Date) getAttributeInternal(REQUESTEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for RequestedDate.
     * @param value value to set the RequestedDate
     */
    public void setRequestedDate(Date value) {
        setAttributeInternal(REQUESTEDDATE, value);
    }

    /**
     * Gets the attribute value for RequestorId, using the alias name RequestorId.
     * @return the value of RequestorId
     */
    public Number getRequestorId() {
        return (Number) getAttributeInternal(REQUESTORID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RequestorId.
     * @param value value to set the RequestorId
     */
    public void setRequestorId(Number value) {
        setAttributeInternal(REQUESTORID, value);
    }

    /**
     * Gets the attribute value for CustomerType, using the alias name CustomerType.
     * @return the value of CustomerType
     */
    public String getCustomerType() {
        return (String) getAttributeInternal(CUSTOMERTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustomerType.
     * @param value value to set the CustomerType
     */
    public void setCustomerType(String value) {
        setAttributeInternal(CUSTOMERTYPE, value);
    }

    /**
     * Gets the attribute value for ProjectId, using the alias name ProjectId.
     * @return the value of ProjectId
     */
    public Number getProjectId() {
        return (Number) getAttributeInternal(PROJECTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProjectId.
     * @param value value to set the ProjectId
     */
    public void setProjectId(Number value) {
        setAttributeInternal(PROJECTID, value);
    }

    /**
     * Gets the attribute value for Division, using the alias name Division.
     * @return the value of Division
     */
    public String getDivision() {
        return (String) getAttributeInternal(DIVISION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Division.
     * @param value value to set the Division
     */
    public void setDivision(String value) {
        setAttributeInternal(DIVISION, value);
    }

    /**
     * Gets the attribute value for DivFlexValueId, using the alias name DivFlexValueId.
     * @return the value of DivFlexValueId
     */
    public Number getDivFlexValueId() {
        return (Number) getAttributeInternal(DIVFLEXVALUEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DivFlexValueId.
     * @param value value to set the DivFlexValueId
     */
    public void setDivFlexValueId(Number value) {
        setAttributeInternal(DIVFLEXVALUEID, value);
    }

    /**
     * Gets the attribute value for DivFlexValueSetId, using the alias name DivFlexValueSetId.
     * @return the value of DivFlexValueSetId
     */
    public Number getDivFlexValueSetId() {
        return (Number) getAttributeInternal(DIVFLEXVALUESETID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DivFlexValueSetId.
     * @param value value to set the DivFlexValueSetId
     */
    public void setDivFlexValueSetId(Number value) {
        setAttributeInternal(DIVFLEXVALUESETID, value);
    }

    /**
     * Gets the attribute value for DepartmentName, using the alias name DepartmentName.
     * @return the value of DepartmentName
     */
    public String getDepartmentName() {
        return (String) getAttributeInternal(DEPARTMENTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for DepartmentName.
     * @param value value to set the DepartmentName
     */
    public void setDepartmentName(String value) {
        setAttributeInternal(DEPARTMENTNAME, value);
    }

    /**
     * Gets the attribute value for DepartmentCode, using the alias name DepartmentCode.
     * @return the value of DepartmentCode
     */
    public String getDepartmentCode() {
        return (String) getAttributeInternal(DEPARTMENTCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DepartmentCode.
     * @param value value to set the DepartmentCode
     */
    public void setDepartmentCode(String value) {
        setAttributeInternal(DEPARTMENTCODE, value);
    }

    /**
     * Gets the attribute value for DeptFlexValueId, using the alias name DeptFlexValueId.
     * @return the value of DeptFlexValueId
     */
    public Number getDeptFlexValueId() {
        return (Number) getAttributeInternal(DEPTFLEXVALUEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeptFlexValueId.
     * @param value value to set the DeptFlexValueId
     */
    public void setDeptFlexValueId(Number value) {
        setAttributeInternal(DEPTFLEXVALUEID, value);
    }

    /**
     * Gets the attribute value for DeptFlexValueSetId, using the alias name DeptFlexValueSetId.
     * @return the value of DeptFlexValueSetId
     */
    public Number getDeptFlexValueSetId() {
        return (Number) getAttributeInternal(DEPTFLEXVALUESETID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeptFlexValueSetId.
     * @param value value to set the DeptFlexValueSetId
     */
    public void setDeptFlexValueSetId(Number value) {
        setAttributeInternal(DEPTFLEXVALUESETID, value);
    }

    /**
     * Gets the attribute value for CustomerId, using the alias name CustomerId.
     * @return the value of CustomerId
     */
    public Number getCustomerId() {
        return (Number) getAttributeInternal(CUSTOMERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustomerId.
     * @param value value to set the CustomerId
     */
    public void setCustomerId(Number value) {
        setAttributeInternal(CUSTOMERID, value);
    }

    /**
     * Gets the attribute value for CustSiteId, using the alias name CustSiteId.
     * @return the value of CustSiteId
     */
    public Number getCustSiteId() {
        return (Number) getAttributeInternal(CUSTSITEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustSiteId.
     * @param value value to set the CustSiteId
     */
    public void setCustSiteId(Number value) {
        setAttributeInternal(CUSTSITEID, value);
    }

    /**
     * Gets the attribute value for SiteUseId, using the alias name SiteUseId.
     * @return the value of SiteUseId
     */
    public Number getSiteUseId() {
        return (Number) getAttributeInternal(SITEUSEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SiteUseId.
     * @param value value to set the SiteUseId
     */
    public void setSiteUseId(Number value) {
        setAttributeInternal(SITEUSEID, value);
    }

    /**
     * Gets the attribute value for PreparedOn, using the alias name PreparedOn.
     * @return the value of PreparedOn
     */
    public Date getPreparedOn() {
        return (Date) getAttributeInternal(PREPAREDON);
    }

    /**
     * Sets <code>value</code> as the attribute value for PreparedOn.
     * @param value value to set the PreparedOn
     */
    public void setPreparedOn(Date value) {
        setAttributeInternal(PREPAREDON, value);
    }

    /**
     * Gets the attribute value for PreparedBy, using the alias name PreparedBy.
     * @return the value of PreparedBy
     */
    public String getPreparedBy() {
        return (String) getAttributeInternal(PREPAREDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for PreparedBy.
     * @param value value to set the PreparedBy
     */
    public void setPreparedBy(String value) {
        setAttributeInternal(PREPAREDBY, value);
    }

    /**
     * Gets the attribute value for RequestStatus, using the alias name RequestStatus.
     * @return the value of RequestStatus
     */
    public String getRequestStatus() {
        return (String) getAttributeInternal(REQUESTSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for RequestStatus.
     * @param value value to set the RequestStatus
     */
    public void setRequestStatus(String value) {
        setAttributeInternal(REQUESTSTATUS, value);
    }

    /**
     * Gets the attribute value for ApprovedDate, using the alias name ApprovedDate.
     * @return the value of ApprovedDate
     */
    public Date getApprovedDate() {
        return (Date) getAttributeInternal(APPROVEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ApprovedDate.
     * @param value value to set the ApprovedDate
     */
    public void setApprovedDate(Date value) {
        setAttributeInternal(APPROVEDDATE, value);
    }

    /**
     * Gets the attribute value for Note, using the alias name Note.
     * @return the value of Note
     */
    public String getNote() {
        return (String) getAttributeInternal(NOTE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Note.
     * @param value value to set the Note
     */
    public void setNote(String value) {
        setAttributeInternal(NOTE, value);
    }

    /**
     * Gets the attribute value for SubmittedBy, using the alias name SubmittedBy.
     * @return the value of SubmittedBy
     */
    public String getSubmittedBy() {
        return (String) getAttributeInternal(SUBMITTEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for SubmittedBy.
     * @param value value to set the SubmittedBy
     */
    public void setSubmittedBy(String value) {
        setAttributeInternal(SUBMITTEDBY, value);
    }

    /**
     * Gets the attribute value for SubmittedDate, using the alias name SubmittedDate.
     * @return the value of SubmittedDate
     */
    public Date getSubmittedDate() {
        return (Date) getAttributeInternal(SUBMITTEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SubmittedDate.
     * @param value value to set the SubmittedDate
     */
    public void setSubmittedDate(Date value) {
        setAttributeInternal(SUBMITTEDDATE, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }


    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }


    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the value of LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }


    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }


    /**
     * Gets the attribute value for ObjectVersionNumber, using the alias name ObjectVersionNumber.
     * @return the value of ObjectVersionNumber
     */
    public Number getObjectVersionNumber() {
        return (Number) getAttributeInternal(OBJECTVERSIONNUMBER);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getXxadsAssetRequestLinesEO() {
        return (RowIterator) getAttributeInternal(XXADSASSETREQUESTLINESEO);
    }


    /**
     * @param requestId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number requestId) {
        return new Key(new Object[] { requestId });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        SequenceImpl seq = new SequenceImpl("XXADS_ASSET_REQUEST_S",getDBTransaction());
        setRequestId(seq.getSequenceNumber());
        //        setAttachmentCode("PROBATION CONFIRMATION");
    }
}

