package model.entity;

import java.math.BigDecimal;

import java.sql.Timestamp;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 31 09:42:19 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxadsBillingOperatorsEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        OperatorLineId,
        HeaderId,
        TsLineId,
        RentalType,
        EmployeeId,
        OperatorStdHours,
        OperatorOt1Hours,
        OperatorOt2Hours,
        OperatorStdRate,
        OperatorOt1Rate,
        OperatorOt2Rate,
        OperatorGrossAmt,
        OperatorDiscountAmt,
        CreationDate,
        CreatedBy,
        LastUpdateDate,
        LastUpdatedBy,
        ObjectVersionNumber,
        XxadsBillingHdrEO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int OPERATORLINEID = AttributesEnum.OperatorLineId.index();
    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int TSLINEID = AttributesEnum.TsLineId.index();
    public static final int RENTALTYPE = AttributesEnum.RentalType.index();
    public static final int EMPLOYEEID = AttributesEnum.EmployeeId.index();
    public static final int OPERATORSTDHOURS = AttributesEnum.OperatorStdHours.index();
    public static final int OPERATOROT1HOURS = AttributesEnum.OperatorOt1Hours.index();
    public static final int OPERATOROT2HOURS = AttributesEnum.OperatorOt2Hours.index();
    public static final int OPERATORSTDRATE = AttributesEnum.OperatorStdRate.index();
    public static final int OPERATOROT1RATE = AttributesEnum.OperatorOt1Rate.index();
    public static final int OPERATOROT2RATE = AttributesEnum.OperatorOt2Rate.index();
    public static final int OPERATORGROSSAMT = AttributesEnum.OperatorGrossAmt.index();
    public static final int OPERATORDISCOUNTAMT = AttributesEnum.OperatorDiscountAmt.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int OBJECTVERSIONNUMBER = AttributesEnum.ObjectVersionNumber.index();
    public static final int XXADSBILLINGHDREO = AttributesEnum.XxadsBillingHdrEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxadsBillingOperatorsEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.entity.XxadsBillingOperatorsEO");
    }


    /**
     * Gets the attribute value for OperatorLineId, using the alias name OperatorLineId.
     * @return the value of OperatorLineId
     */
    public oracle.jbo.domain.Number getOperatorLineId() {
        return (oracle.jbo.domain.Number) getAttributeInternal(OPERATORLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OperatorLineId.
     * @param value value to set the OperatorLineId
     */
    public void setOperatorLineId(oracle.jbo.domain.Number value) {
        setAttributeInternal(OPERATORLINEID, value);
    }

    /**
     * Gets the attribute value for HeaderId, using the alias name HeaderId.
     * @return the value of HeaderId
     */
    public Number getHeaderId() {
        return (Number) getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for HeaderId.
     * @param value value to set the HeaderId
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for TsLineId, using the alias name TsLineId.
     * @return the value of TsLineId
     */
    public Number getTsLineId() {
        return (Number) getAttributeInternal(TSLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for TsLineId.
     * @param value value to set the TsLineId
     */
    public void setTsLineId(Number value) {
        setAttributeInternal(TSLINEID, value);
    }

    /**
     * Gets the attribute value for RentalType, using the alias name RentalType.
     * @return the value of RentalType
     */
    public String getRentalType() {
        return (String) getAttributeInternal(RENTALTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for RentalType.
     * @param value value to set the RentalType
     */
    public void setRentalType(String value) {
        setAttributeInternal(RENTALTYPE, value);
    }

    /**
     * Gets the attribute value for EmployeeId, using the alias name EmployeeId.
     * @return the value of EmployeeId
     */
    public Number getEmployeeId() {
        return (Number) getAttributeInternal(EMPLOYEEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for EmployeeId.
     * @param value value to set the EmployeeId
     */
    public void setEmployeeId(Number value) {
        setAttributeInternal(EMPLOYEEID, value);
    }

    /**
     * Gets the attribute value for OperatorStdHours, using the alias name OperatorStdHours.
     * @return the value of OperatorStdHours
     */
    public Number getOperatorStdHours() {
        return (Number) getAttributeInternal(OPERATORSTDHOURS);
    }

    /**
     * Sets <code>value</code> as the attribute value for OperatorStdHours.
     * @param value value to set the OperatorStdHours
     */
    public void setOperatorStdHours(Number value) {
        setAttributeInternal(OPERATORSTDHOURS, value);
    }

    /**
     * Gets the attribute value for OperatorOt1Hours, using the alias name OperatorOt1Hours.
     * @return the value of OperatorOt1Hours
     */
    public Number getOperatorOt1Hours() {
        return (Number) getAttributeInternal(OPERATOROT1HOURS);
    }

    /**
     * Sets <code>value</code> as the attribute value for OperatorOt1Hours.
     * @param value value to set the OperatorOt1Hours
     */
    public void setOperatorOt1Hours(Number value) {
        setAttributeInternal(OPERATOROT1HOURS, value);
    }

    /**
     * Gets the attribute value for OperatorOt2Hours, using the alias name OperatorOt2Hours.
     * @return the value of OperatorOt2Hours
     */
    public Number getOperatorOt2Hours() {
        return (Number) getAttributeInternal(OPERATOROT2HOURS);
    }

    /**
     * Sets <code>value</code> as the attribute value for OperatorOt2Hours.
     * @param value value to set the OperatorOt2Hours
     */
    public void setOperatorOt2Hours(Number value) {
        setAttributeInternal(OPERATOROT2HOURS, value);
    }

    /**
     * Gets the attribute value for OperatorStdRate, using the alias name OperatorStdRate.
     * @return the value of OperatorStdRate
     */
    public Number getOperatorStdRate() {
        return (Number) getAttributeInternal(OPERATORSTDRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for OperatorStdRate.
     * @param value value to set the OperatorStdRate
     */
    public void setOperatorStdRate(Number value) {
        setAttributeInternal(OPERATORSTDRATE, value);
    }

    /**
     * Gets the attribute value for OperatorOt1Rate, using the alias name OperatorOt1Rate.
     * @return the value of OperatorOt1Rate
     */
    public Number getOperatorOt1Rate() {
        return (Number) getAttributeInternal(OPERATOROT1RATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for OperatorOt1Rate.
     * @param value value to set the OperatorOt1Rate
     */
    public void setOperatorOt1Rate(Number value) {
        setAttributeInternal(OPERATOROT1RATE, value);
    }

    /**
     * Gets the attribute value for OperatorOt2Rate, using the alias name OperatorOt2Rate.
     * @return the value of OperatorOt2Rate
     */
    public Number getOperatorOt2Rate() {
        return (Number) getAttributeInternal(OPERATOROT2RATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for OperatorOt2Rate.
     * @param value value to set the OperatorOt2Rate
     */
    public void setOperatorOt2Rate(Number value) {
        setAttributeInternal(OPERATOROT2RATE, value);
    }

    /**
     * Gets the attribute value for OperatorGrossAmt, using the alias name OperatorGrossAmt.
     * @return the value of OperatorGrossAmt
     */
    public Number getOperatorGrossAmt() {
        return (Number) getAttributeInternal(OPERATORGROSSAMT);
    }

    /**
     * Sets <code>value</code> as the attribute value for OperatorGrossAmt.
     * @param value value to set the OperatorGrossAmt
     */
    public void setOperatorGrossAmt(Number value) {
        setAttributeInternal(OPERATORGROSSAMT, value);
    }

    /**
     * Gets the attribute value for OperatorDiscountAmt, using the alias name OperatorDiscountAmt.
     * @return the value of OperatorDiscountAmt
     */
    public Number getOperatorDiscountAmt() {
        return (Number) getAttributeInternal(OPERATORDISCOUNTAMT);
    }

    /**
     * Sets <code>value</code> as the attribute value for OperatorDiscountAmt.
     * @param value value to set the OperatorDiscountAmt
     */
    public void setOperatorDiscountAmt(Number value) {
        setAttributeInternal(OPERATORDISCOUNTAMT, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }


    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }


    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the value of LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }


    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }


    /**
     * Gets the attribute value for ObjectVersionNumber, using the alias name ObjectVersionNumber.
     * @return the value of ObjectVersionNumber
     */
    public Number getObjectVersionNumber() {
        return (Number) getAttributeInternal(OBJECTVERSIONNUMBER);
    }


    /**
     * @return the associated entity XxadsBillingHdrEOImpl.
     */
    public XxadsBillingHdrEOImpl getXxadsBillingHdrEO() {
        return (XxadsBillingHdrEOImpl) getAttributeInternal(XXADSBILLINGHDREO);
    }

    /**
     * Sets <code>value</code> as the associated entity XxadsBillingHdrEOImpl.
     */
    public void setXxadsBillingHdrEO(XxadsBillingHdrEOImpl value) {
        setAttributeInternal(XXADSBILLINGHDREO, value);
    }


    /**
     * @param operatorLineId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number operatorLineId) {
        return new Key(new Object[] { operatorLineId });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        SequenceImpl seq = new SequenceImpl("XXADS_BILLING_OPERATORS_S",getDBTransaction());
        setOperatorLineId(seq.getSequenceNumber());
    }
    
    private static final byte USERNAME_HISTORY_TYPE =13;
    
    @Override
    protected Object getHistoryContextForAttribute(AttributeDefImpl attr) {
        if (attr.getHistoryKind() == USERNAME_HISTORY_TYPE) {
            // Custom History type logic goes here
            return (String) ((Map)ADFContext.getCurrent().getSessionScope().get("userMap")).get("UserName");
        }
        return super.getHistoryContextForAttribute(attr);
    }
}

