package model.lov;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 14 12:42:34 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AllocationAssetNumberLOVRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        AssetId,
        AssetNumber,
        AssetDescription;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AllocationAssetNumberLOVRowImpl.AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AllocationAssetNumberLOVRowImpl.AttributesEnum.firstIndex() + AllocationAssetNumberLOVRowImpl.AttributesEnum
                                                                                                                .staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AllocationAssetNumberLOVRowImpl.AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int ASSETID = AttributesEnum.AssetId.index();
    public static final int ASSETNUMBER = AttributesEnum.AssetNumber.index();
    public static final int ASSETDESCRIPTION = AttributesEnum.AssetDescription.index();

    /**
     * This is the default constructor (do not remove).
     */
    public AllocationAssetNumberLOVRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute AssetId.
     * @return the AssetId
     */
    public BigDecimal getAssetId() {
        return (BigDecimal) getAttributeInternal(ASSETID);
    }

    /**
     * Gets the attribute value for the calculated attribute AssetNumber.
     * @return the AssetNumber
     */
    public String getAssetNumber() {
        return (String) getAttributeInternal(ASSETNUMBER);
    }

    /**
     * Gets the attribute value for the calculated attribute AssetDescription.
     * @return the AssetDescription
     */
    public String getAssetDescription() {
        return (String) getAttributeInternal(ASSETDESCRIPTION);
    }
}

