package model.lov;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 19 16:54:31 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MasterOrganizationLOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MasterOrganizationLOVImpl() {
    }
}

