package model.lov;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 14 12:12:19 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ReqTypeBasedCustomerLOVRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        CustomerName,
        CustomerNumber,
        CustAccountId;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int CUSTOMERNAME = AttributesEnum.CustomerName.index();
    public static final int CUSTOMERNUMBER = AttributesEnum.CustomerNumber.index();
    public static final int CUSTACCOUNTID = AttributesEnum.CustAccountId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ReqTypeBasedCustomerLOVRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute CustomerName.
     * @return the CustomerName
     */
    public String getCustomerName() {
        return (String) getAttributeInternal(CUSTOMERNAME);
    }

    /**
     * Gets the attribute value for the calculated attribute CustomerNumber.
     * @return the CustomerNumber
     */
    public String getCustomerNumber() {
        return (String) getAttributeInternal(CUSTOMERNUMBER);
    }

    /**
     * Gets the attribute value for the calculated attribute CustAccountId.
     * @return the CustAccountId
     */
    public BigDecimal getCustAccountId() {
        return (BigDecimal) getAttributeInternal(CUSTACCOUNTID);
    }
}

