package model.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 20 15:59:22 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StaticSourceLovVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public StaticSourceLovVOImpl() {
    }
}

