package model.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 19 14:34:15 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StaticSegmentNumsLOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public StaticSegmentNumsLOVImpl() {
    }
}

