package model.lov;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 07 18:08:15 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TaxCodesLOVRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        TaxRateId,
        Tax,
        TaxRateCode,
        TaxRegimeCode,
        PercentageRate,
        TaxJurisdictionCode;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int TAXRATEID = AttributesEnum.TaxRateId.index();
    public static final int TAX = AttributesEnum.Tax.index();
    public static final int TAXRATECODE = AttributesEnum.TaxRateCode.index();
    public static final int TAXREGIMECODE = AttributesEnum.TaxRegimeCode.index();
    public static final int PERCENTAGERATE = AttributesEnum.PercentageRate.index();
    public static final int TAXJURISDICTIONCODE = AttributesEnum.TaxJurisdictionCode.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TaxCodesLOVRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute TaxRateId.
     * @return the TaxRateId
     */
    public BigDecimal getTaxRateId() {
        return (BigDecimal) getAttributeInternal(TAXRATEID);
    }

    /**
     * Gets the attribute value for the calculated attribute Tax.
     * @return the Tax
     */
    public String getTax() {
        return (String) getAttributeInternal(TAX);
    }

    /**
     * Gets the attribute value for the calculated attribute TaxRateCode.
     * @return the TaxRateCode
     */
    public String getTaxRateCode() {
        return (String) getAttributeInternal(TAXRATECODE);
    }

    /**
     * Gets the attribute value for the calculated attribute TaxRegimeCode.
     * @return the TaxRegimeCode
     */
    public String getTaxRegimeCode() {
        return (String) getAttributeInternal(TAXREGIMECODE);
    }

    /**
     * Gets the attribute value for the calculated attribute PercentageRate.
     * @return the PercentageRate
     */
    public BigDecimal getPercentageRate() {
        return (BigDecimal) getAttributeInternal(PERCENTAGERATE);
    }

    /**
     * Gets the attribute value for the calculated attribute TaxJurisdictionCode.
     * @return the TaxJurisdictionCode
     */
    public String getTaxJurisdictionCode() {
        return (String) getAttributeInternal(TAXJURISDICTIONCODE);
    }
}

