package model.searchview;

import model.entity.XxadsAssetRequestEOImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 14 11:23:31 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AssetRequestSearchVORowImpl extends ViewRowImpl {


    public static final int ENTITY_XXADSASSETREQUESTEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ApprovedDate,
        CreatedBy,
        CreationDate,
        CustSiteId,
        CustomerId,
        CustomerType,
        DepartmentCode,
        DepartmentName,
        DeptFlexValueId,
        DeptFlexValueSetId,
        DivFlexValueId,
        DivFlexValueSetId,
        Division,
        LastUpdateDate,
        LastUpdatedBy,
        Note,
        ObjectVersionNumber,
        PreparedBy,
        PreparedOn,
        ProjectId,
        RequestId,
        RequestNumber,
        RequestStatus,
        RequestType,
        RequestedDate,
        RequestorBuId,
        RequestorId,
        SiteUseId,
        SourceBuId,
        SrcDivFlexValSetId,
        SrcDivFlexValueId,
        SrcDivision,
        SubmittedBy,
        SubmittedDate,
        TransRequesterBuName,
        TransSourceBuName,
        TransStatus,
        TransCustomerType,
        TransCustName,
        TransCustSiteName,
        TransProject,
        TransRequestNumber;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int APPROVEDDATE = AttributesEnum.ApprovedDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CUSTSITEID = AttributesEnum.CustSiteId.index();
    public static final int CUSTOMERID = AttributesEnum.CustomerId.index();
    public static final int CUSTOMERTYPE = AttributesEnum.CustomerType.index();
    public static final int DEPARTMENTCODE = AttributesEnum.DepartmentCode.index();
    public static final int DEPARTMENTNAME = AttributesEnum.DepartmentName.index();
    public static final int DEPTFLEXVALUEID = AttributesEnum.DeptFlexValueId.index();
    public static final int DEPTFLEXVALUESETID = AttributesEnum.DeptFlexValueSetId.index();
    public static final int DIVFLEXVALUEID = AttributesEnum.DivFlexValueId.index();
    public static final int DIVFLEXVALUESETID = AttributesEnum.DivFlexValueSetId.index();
    public static final int DIVISION = AttributesEnum.Division.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int NOTE = AttributesEnum.Note.index();
    public static final int OBJECTVERSIONNUMBER = AttributesEnum.ObjectVersionNumber.index();
    public static final int PREPAREDBY = AttributesEnum.PreparedBy.index();
    public static final int PREPAREDON = AttributesEnum.PreparedOn.index();
    public static final int PROJECTID = AttributesEnum.ProjectId.index();
    public static final int REQUESTID = AttributesEnum.RequestId.index();
    public static final int REQUESTNUMBER = AttributesEnum.RequestNumber.index();
    public static final int REQUESTSTATUS = AttributesEnum.RequestStatus.index();
    public static final int REQUESTTYPE = AttributesEnum.RequestType.index();
    public static final int REQUESTEDDATE = AttributesEnum.RequestedDate.index();
    public static final int REQUESTORBUID = AttributesEnum.RequestorBuId.index();
    public static final int REQUESTORID = AttributesEnum.RequestorId.index();
    public static final int SITEUSEID = AttributesEnum.SiteUseId.index();
    public static final int SOURCEBUID = AttributesEnum.SourceBuId.index();
    public static final int SRCDIVFLEXVALSETID = AttributesEnum.SrcDivFlexValSetId.index();
    public static final int SRCDIVFLEXVALUEID = AttributesEnum.SrcDivFlexValueId.index();
    public static final int SRCDIVISION = AttributesEnum.SrcDivision.index();
    public static final int SUBMITTEDBY = AttributesEnum.SubmittedBy.index();
    public static final int SUBMITTEDDATE = AttributesEnum.SubmittedDate.index();
    public static final int TRANSREQUESTERBUNAME = AttributesEnum.TransRequesterBuName.index();
    public static final int TRANSSOURCEBUNAME = AttributesEnum.TransSourceBuName.index();
    public static final int TRANSSTATUS = AttributesEnum.TransStatus.index();
    public static final int TRANSCUSTOMERTYPE = AttributesEnum.TransCustomerType.index();
    public static final int TRANSCUSTNAME = AttributesEnum.TransCustName.index();
    public static final int TRANSCUSTSITENAME = AttributesEnum.TransCustSiteName.index();
    public static final int TRANSPROJECT = AttributesEnum.TransProject.index();
    public static final int TRANSREQUESTNUMBER = AttributesEnum.TransRequestNumber.index();

    /**
     * This is the default constructor (do not remove).
     */
    public AssetRequestSearchVORowImpl() {
    }

    /**
     * Gets XxadsAssetRequestEO entity object.
     * @return the XxadsAssetRequestEO
     */
    public XxadsAssetRequestEOImpl getXxadsAssetRequestEO() {
        return (XxadsAssetRequestEOImpl) getEntity(ENTITY_XXADSASSETREQUESTEO);
    }

    /**
     * Gets the attribute value for APPROVED_DATE using the alias name ApprovedDate.
     * @return the APPROVED_DATE
     */
    public Date getApprovedDate() {
        return (Date) getAttributeInternal(APPROVEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for APPROVED_DATE using the alias name ApprovedDate.
     * @param value value to set the APPROVED_DATE
     */
    public void setApprovedDate(Date value) {
        setAttributeInternal(APPROVEDDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for CUST_SITE_ID using the alias name CustSiteId.
     * @return the CUST_SITE_ID
     */
    public Number getCustSiteId() {
        return (Number) getAttributeInternal(CUSTSITEID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUST_SITE_ID using the alias name CustSiteId.
     * @param value value to set the CUST_SITE_ID
     */
    public void setCustSiteId(Number value) {
        setAttributeInternal(CUSTSITEID, value);
    }

    /**
     * Gets the attribute value for CUSTOMER_ID using the alias name CustomerId.
     * @return the CUSTOMER_ID
     */
    public Number getCustomerId() {
        return (Number) getAttributeInternal(CUSTOMERID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMER_ID using the alias name CustomerId.
     * @param value value to set the CUSTOMER_ID
     */
    public void setCustomerId(Number value) {
        setAttributeInternal(CUSTOMERID, value);
    }

    /**
     * Gets the attribute value for CUSTOMER_TYPE using the alias name CustomerType.
     * @return the CUSTOMER_TYPE
     */
    public String getCustomerType() {
        return (String) getAttributeInternal(CUSTOMERTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMER_TYPE using the alias name CustomerType.
     * @param value value to set the CUSTOMER_TYPE
     */
    public void setCustomerType(String value) {
        setAttributeInternal(CUSTOMERTYPE, value);
    }

    /**
     * Gets the attribute value for DEPARTMENT_CODE using the alias name DepartmentCode.
     * @return the DEPARTMENT_CODE
     */
    public String getDepartmentCode() {
        return (String) getAttributeInternal(DEPARTMENTCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPARTMENT_CODE using the alias name DepartmentCode.
     * @param value value to set the DEPARTMENT_CODE
     */
    public void setDepartmentCode(String value) {
        setAttributeInternal(DEPARTMENTCODE, value);
    }

    /**
     * Gets the attribute value for DEPARTMENT_NAME using the alias name DepartmentName.
     * @return the DEPARTMENT_NAME
     */
    public String getDepartmentName() {
        return (String) getAttributeInternal(DEPARTMENTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPARTMENT_NAME using the alias name DepartmentName.
     * @param value value to set the DEPARTMENT_NAME
     */
    public void setDepartmentName(String value) {
        setAttributeInternal(DEPARTMENTNAME, value);
    }

    /**
     * Gets the attribute value for DEPT_FLEX_VALUE_ID using the alias name DeptFlexValueId.
     * @return the DEPT_FLEX_VALUE_ID
     */
    public Number getDeptFlexValueId() {
        return (Number) getAttributeInternal(DEPTFLEXVALUEID);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPT_FLEX_VALUE_ID using the alias name DeptFlexValueId.
     * @param value value to set the DEPT_FLEX_VALUE_ID
     */
    public void setDeptFlexValueId(Number value) {
        setAttributeInternal(DEPTFLEXVALUEID, value);
    }

    /**
     * Gets the attribute value for DEPT_FLEX_VALUE_SET_ID using the alias name DeptFlexValueSetId.
     * @return the DEPT_FLEX_VALUE_SET_ID
     */
    public Number getDeptFlexValueSetId() {
        return (Number) getAttributeInternal(DEPTFLEXVALUESETID);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPT_FLEX_VALUE_SET_ID using the alias name DeptFlexValueSetId.
     * @param value value to set the DEPT_FLEX_VALUE_SET_ID
     */
    public void setDeptFlexValueSetId(Number value) {
        setAttributeInternal(DEPTFLEXVALUESETID, value);
    }

    /**
     * Gets the attribute value for DIV_FLEX_VALUE_ID using the alias name DivFlexValueId.
     * @return the DIV_FLEX_VALUE_ID
     */
    public Number getDivFlexValueId() {
        return (Number) getAttributeInternal(DIVFLEXVALUEID);
    }

    /**
     * Sets <code>value</code> as attribute value for DIV_FLEX_VALUE_ID using the alias name DivFlexValueId.
     * @param value value to set the DIV_FLEX_VALUE_ID
     */
    public void setDivFlexValueId(Number value) {
        setAttributeInternal(DIVFLEXVALUEID, value);
    }

    /**
     * Gets the attribute value for DIV_FLEX_VALUE_SET_ID using the alias name DivFlexValueSetId.
     * @return the DIV_FLEX_VALUE_SET_ID
     */
    public Number getDivFlexValueSetId() {
        return (Number) getAttributeInternal(DIVFLEXVALUESETID);
    }

    /**
     * Sets <code>value</code> as attribute value for DIV_FLEX_VALUE_SET_ID using the alias name DivFlexValueSetId.
     * @param value value to set the DIV_FLEX_VALUE_SET_ID
     */
    public void setDivFlexValueSetId(Number value) {
        setAttributeInternal(DIVFLEXVALUESETID, value);
    }

    /**
     * Gets the attribute value for DIVISION using the alias name Division.
     * @return the DIVISION
     */
    public String getDivision() {
        return (String) getAttributeInternal(DIVISION);
    }

    /**
     * Sets <code>value</code> as attribute value for DIVISION using the alias name Division.
     * @param value value to set the DIVISION
     */
    public void setDivision(String value) {
        setAttributeInternal(DIVISION, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Gets the attribute value for NOTE using the alias name Note.
     * @return the NOTE
     */
    public String getNote() {
        return (String) getAttributeInternal(NOTE);
    }

    /**
     * Sets <code>value</code> as attribute value for NOTE using the alias name Note.
     * @param value value to set the NOTE
     */
    public void setNote(String value) {
        setAttributeInternal(NOTE, value);
    }

    /**
     * Gets the attribute value for OBJECT_VERSION_NUMBER using the alias name ObjectVersionNumber.
     * @return the OBJECT_VERSION_NUMBER
     */
    public Number getObjectVersionNumber() {
        return (Number) getAttributeInternal(OBJECTVERSIONNUMBER);
    }

    /**
     * Gets the attribute value for PREPARED_BY using the alias name PreparedBy.
     * @return the PREPARED_BY
     */
    public String getPreparedBy() {
        return (String) getAttributeInternal(PREPAREDBY);
    }


    /**
     * Gets the attribute value for PREPARED_ON using the alias name PreparedOn.
     * @return the PREPARED_ON
     */
    public Date getPreparedOn() {
        return (Date) getAttributeInternal(PREPAREDON);
    }


    /**
     * Gets the attribute value for PROJECT_ID using the alias name ProjectId.
     * @return the PROJECT_ID
     */
    public Number getProjectId() {
        return (Number) getAttributeInternal(PROJECTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROJECT_ID using the alias name ProjectId.
     * @param value value to set the PROJECT_ID
     */
    public void setProjectId(Number value) {
        setAttributeInternal(PROJECTID, value);
    }

    /**
     * Gets the attribute value for REQUEST_ID using the alias name RequestId.
     * @return the REQUEST_ID
     */
    public Number getRequestId() {
        return (Number) getAttributeInternal(REQUESTID);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUEST_ID using the alias name RequestId.
     * @param value value to set the REQUEST_ID
     */
    public void setRequestId(Number value) {
        setAttributeInternal(REQUESTID, value);
    }

    /**
     * Gets the attribute value for REQUEST_NUMBER using the alias name RequestNumber.
     * @return the REQUEST_NUMBER
     */
    public String getRequestNumber() {
        return (String) getAttributeInternal(REQUESTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUEST_NUMBER using the alias name RequestNumber.
     * @param value value to set the REQUEST_NUMBER
     */
    public void setRequestNumber(String value) {
        setAttributeInternal(REQUESTNUMBER, value);
    }

    /**
     * Gets the attribute value for REQUEST_STATUS using the alias name RequestStatus.
     * @return the REQUEST_STATUS
     */
    public String getRequestStatus() {
        return (String) getAttributeInternal(REQUESTSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUEST_STATUS using the alias name RequestStatus.
     * @param value value to set the REQUEST_STATUS
     */
    public void setRequestStatus(String value) {
        setAttributeInternal(REQUESTSTATUS, value);
    }

    /**
     * Gets the attribute value for REQUEST_TYPE using the alias name RequestType.
     * @return the REQUEST_TYPE
     */
    public String getRequestType() {
        return (String) getAttributeInternal(REQUESTTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUEST_TYPE using the alias name RequestType.
     * @param value value to set the REQUEST_TYPE
     */
    public void setRequestType(String value) {
        setAttributeInternal(REQUESTTYPE, value);
    }

    /**
     * Gets the attribute value for REQUESTED_DATE using the alias name RequestedDate.
     * @return the REQUESTED_DATE
     */
    public Date getRequestedDate() {
        return (Date) getAttributeInternal(REQUESTEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUESTED_DATE using the alias name RequestedDate.
     * @param value value to set the REQUESTED_DATE
     */
    public void setRequestedDate(Date value) {
        setAttributeInternal(REQUESTEDDATE, value);
    }

    /**
     * Gets the attribute value for REQUESTOR_BU_ID using the alias name RequestorBuId.
     * @return the REQUESTOR_BU_ID
     */
    public Number getRequestorBuId() {
        return (Number) getAttributeInternal(REQUESTORBUID);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUESTOR_BU_ID using the alias name RequestorBuId.
     * @param value value to set the REQUESTOR_BU_ID
     */
    public void setRequestorBuId(Number value) {
        setAttributeInternal(REQUESTORBUID, value);
    }

    /**
     * Gets the attribute value for REQUESTOR_ID using the alias name RequestorId.
     * @return the REQUESTOR_ID
     */
    public Number getRequestorId() {
        return (Number) getAttributeInternal(REQUESTORID);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUESTOR_ID using the alias name RequestorId.
     * @param value value to set the REQUESTOR_ID
     */
    public void setRequestorId(Number value) {
        setAttributeInternal(REQUESTORID, value);
    }

    /**
     * Gets the attribute value for SITE_USE_ID using the alias name SiteUseId.
     * @return the SITE_USE_ID
     */
    public Number getSiteUseId() {
        return (Number) getAttributeInternal(SITEUSEID);
    }

    /**
     * Sets <code>value</code> as attribute value for SITE_USE_ID using the alias name SiteUseId.
     * @param value value to set the SITE_USE_ID
     */
    public void setSiteUseId(Number value) {
        setAttributeInternal(SITEUSEID, value);
    }

    /**
     * Gets the attribute value for SOURCE_BU_ID using the alias name SourceBuId.
     * @return the SOURCE_BU_ID
     */
    public Number getSourceBuId() {
        return (Number) getAttributeInternal(SOURCEBUID);
    }

    /**
     * Sets <code>value</code> as attribute value for SOURCE_BU_ID using the alias name SourceBuId.
     * @param value value to set the SOURCE_BU_ID
     */
    public void setSourceBuId(Number value) {
        setAttributeInternal(SOURCEBUID, value);
    }

    /**
     * Gets the attribute value for SRC_DIV_FLEX_VAL_SET_ID using the alias name SrcDivFlexValSetId.
     * @return the SRC_DIV_FLEX_VAL_SET_ID
     */
    public Number getSrcDivFlexValSetId() {
        return (Number) getAttributeInternal(SRCDIVFLEXVALSETID);
    }

    /**
     * Sets <code>value</code> as attribute value for SRC_DIV_FLEX_VAL_SET_ID using the alias name SrcDivFlexValSetId.
     * @param value value to set the SRC_DIV_FLEX_VAL_SET_ID
     */
    public void setSrcDivFlexValSetId(Number value) {
        setAttributeInternal(SRCDIVFLEXVALSETID, value);
    }

    /**
     * Gets the attribute value for SRC_DIV_FLEX_VALUE_ID using the alias name SrcDivFlexValueId.
     * @return the SRC_DIV_FLEX_VALUE_ID
     */
    public Number getSrcDivFlexValueId() {
        return (Number) getAttributeInternal(SRCDIVFLEXVALUEID);
    }

    /**
     * Sets <code>value</code> as attribute value for SRC_DIV_FLEX_VALUE_ID using the alias name SrcDivFlexValueId.
     * @param value value to set the SRC_DIV_FLEX_VALUE_ID
     */
    public void setSrcDivFlexValueId(Number value) {
        setAttributeInternal(SRCDIVFLEXVALUEID, value);
    }

    /**
     * Gets the attribute value for SRC_DIVISION using the alias name SrcDivision.
     * @return the SRC_DIVISION
     */
    public String getSrcDivision() {
        return (String) getAttributeInternal(SRCDIVISION);
    }

    /**
     * Sets <code>value</code> as attribute value for SRC_DIVISION using the alias name SrcDivision.
     * @param value value to set the SRC_DIVISION
     */
    public void setSrcDivision(String value) {
        setAttributeInternal(SRCDIVISION, value);
    }

    /**
     * Gets the attribute value for SUBMITTED_BY using the alias name SubmittedBy.
     * @return the SUBMITTED_BY
     */
    public String getSubmittedBy() {
        return (String) getAttributeInternal(SUBMITTEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for SUBMITTED_BY using the alias name SubmittedBy.
     * @param value value to set the SUBMITTED_BY
     */
    public void setSubmittedBy(String value) {
        setAttributeInternal(SUBMITTEDBY, value);
    }

    /**
     * Gets the attribute value for SUBMITTED_DATE using the alias name SubmittedDate.
     * @return the SUBMITTED_DATE
     */
    public Date getSubmittedDate() {
        return (Date) getAttributeInternal(SUBMITTEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for SUBMITTED_DATE using the alias name SubmittedDate.
     * @param value value to set the SUBMITTED_DATE
     */
    public void setSubmittedDate(Date value) {
        setAttributeInternal(SUBMITTEDDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransRequestorBuName.
     * @return the TransRequestorBuName
     */
    public String getTransRequesterBuName() {
        return (String) getAttributeInternal(TRANSREQUESTERBUNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransRequestorBuName.
     * @param value value to set the  TransRequestorBuName
     */
    public void setTransRequesterBuName(String value) {
        setAttributeInternal(TRANSREQUESTERBUNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransSourceBuName.
     * @return the TransSourceBuName
     */
    public String getTransSourceBuName() {
        return (String) getAttributeInternal(TRANSSOURCEBUNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransSourceBuName.
     * @param value value to set the  TransSourceBuName
     */
    public void setTransSourceBuName(String value) {
        setAttributeInternal(TRANSSOURCEBUNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransStatus.
     * @return the TransStatus
     */
    public String getTransStatus() {
        return (String) getAttributeInternal(TRANSSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransStatus.
     * @param value value to set the  TransStatus
     */
    public void setTransStatus(String value) {
        setAttributeInternal(TRANSSTATUS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransCustomerType.
     * @return the TransCustomerType
     */
    public String getTransCustomerType() {
        return (String) getAttributeInternal(TRANSCUSTOMERTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransCustomerType.
     * @param value value to set the  TransCustomerType
     */
    public void setTransCustomerType(String value) {
        setAttributeInternal(TRANSCUSTOMERTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransCustName.
     * @return the TransCustName
     */
    public String getTransCustName() {
        return (String) getAttributeInternal(TRANSCUSTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransCustName.
     * @param value value to set the  TransCustName
     */
    public void setTransCustName(String value) {
        setAttributeInternal(TRANSCUSTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransCustSiteName.
     * @return the TransCustSiteName
     */
    public String getTransCustSiteName() {
        return (String) getAttributeInternal(TRANSCUSTSITENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransCustSiteName.
     * @param value value to set the  TransCustSiteName
     */
    public void setTransCustSiteName(String value) {
        setAttributeInternal(TRANSCUSTSITENAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransProject.
     * @return the TransProject
     */
    public String getTransProject() {
        return (String) getAttributeInternal(TRANSPROJECT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransProject.
     * @param value value to set the  TransProject
     */
    public void setTransProject(String value) {
        setAttributeInternal(TRANSPROJECT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransRequestNumber.
     * @return the TransRequestNumber
     */
    public Number getTransRequestNumber() {
        return (Number) getAttributeInternal(TRANSREQUESTNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransRequestNumber.
     * @param value value to set the  TransRequestNumber
     */
    public void setTransRequestNumber(Number value) {
        setAttributeInternal(TRANSREQUESTNUMBER, value);
    }


}

