package model.searchview;

import java.math.BigDecimal;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 27 09:35:31 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UserRolesVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        RoleCommonName,
        RoleId,
        RoleName,
        UserId,
        UserName;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ROLECOMMONNAME = AttributesEnum.RoleCommonName.index();
    public static final int ROLEID = AttributesEnum.RoleId.index();
    public static final int ROLENAME = AttributesEnum.RoleName.index();
    public static final int USERID = AttributesEnum.UserId.index();
    public static final int USERNAME = AttributesEnum.UserName.index();

    /**
     * This is the default constructor (do not remove).
     */
    public UserRolesVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute RoleCommonName.
     * @return the RoleCommonName
     */
    public String getRoleCommonName() {
        return (String) getAttributeInternal(ROLECOMMONNAME);
    }

    /**
     * Gets the attribute value for the calculated attribute RoleId.
     * @return the RoleId
     */
    public oracle.jbo.domain.Number getRoleId() {
        return (oracle.jbo.domain.Number) getAttributeInternal(ROLEID);
    }

    /**
     * Gets the attribute value for the calculated attribute RoleName.
     * @return the RoleName
     */
    public String getRoleName() {
        return (String) getAttributeInternal(ROLENAME);
    }

    /**
     * Gets the attribute value for the calculated attribute UserId.
     * @return the UserId
     */
    public Number getUserId() {
        return (Number) getAttributeInternal(USERID);
    }

    /**
     * Gets the attribute value for the calculated attribute UserName.
     * @return the UserName
     */
    public String getUserName() {
        return (String) getAttributeInternal(USERNAME);
    }
}

