package model.entity;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;

import oracle.jbo.Key;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 28 11:07:42 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AssetDepReceiptMobilizationEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        DrMobilizationId,
        DrLineId,
        DrId,
        DoMobilizationId,
        DoLineId,
        AssetId,
        MobilizationAssetId,
        TripDate,
        CreationDate,
        CreatedBy,
        LastUpdateDate,
        LastUpdatedBy,
        ObjectVersionNumber;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        SequenceImpl seq = new SequenceImpl("XXADS_DR_MOBILIZATION_S",getDBTransaction());
        setDrMobilizationId(seq.getSequenceNumber());
    }
    
    private static final byte USERNAME_HISTORY_TYPE =13;
    
    @Override
    protected Object getHistoryContextForAttribute(AttributeDefImpl attr) {
    if (attr.getHistoryKind() == USERNAME_HISTORY_TYPE) {
       // Custom History type logic goes here
      return (String) ((Map)ADFContext.getCurrent().getSessionScope().get("userMap")).get("UserName");
    }
    return super.getHistoryContextForAttribute(attr);
    }

    public static final int DRMOBILIZATIONID = AttributesEnum.DrMobilizationId.index();
    public static final int DRLINEID = AttributesEnum.DrLineId.index();
    public static final int DRID = AttributesEnum.DrId.index();
    public static final int DOMOBILIZATIONID = AttributesEnum.DoMobilizationId.index();
    public static final int DOLINEID = AttributesEnum.DoLineId.index();
    public static final int ASSETID = AttributesEnum.AssetId.index();
    public static final int MOBILIZATIONASSETID = AttributesEnum.MobilizationAssetId.index();
    public static final int TRIPDATE = AttributesEnum.TripDate.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int OBJECTVERSIONNUMBER = AttributesEnum.ObjectVersionNumber.index();

    /**
     * This is the default constructor (do not remove).
     */
    public AssetDepReceiptMobilizationEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.entity.AssetDepReceiptMobilizationEO");
    }

    /**
     * Gets the attribute value for DrMobilizationId, using the alias name DrMobilizationId.
     * @return the value of DrMobilizationId
     */
    public Number getDrMobilizationId() {
        return (Number) getAttributeInternal(DRMOBILIZATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DrMobilizationId.
     * @param value value to set the DrMobilizationId
     */
    public void setDrMobilizationId(Number value) {
        setAttributeInternal(DRMOBILIZATIONID, value);
    }

    /**
     * Gets the attribute value for DrLineId, using the alias name DrLineId.
     * @return the value of DrLineId
     */
    public Number getDrLineId() {
        return (Number) getAttributeInternal(DRLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DrLineId.
     * @param value value to set the DrLineId
     */
    public void setDrLineId(Number value) {
        setAttributeInternal(DRLINEID, value);
    }

    /**
     * Gets the attribute value for DrId, using the alias name DrId.
     * @return the value of DrId
     */
    public Number getDrId() {
        return (Number) getAttributeInternal(DRID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DrId.
     * @param value value to set the DrId
     */
    public void setDrId(Number value) {
        setAttributeInternal(DRID, value);
    }

    /**
     * Gets the attribute value for DoMobilizationId, using the alias name DoMobilizationId.
     * @return the value of DoMobilizationId
     */
    public Number getDoMobilizationId() {
        return (Number) getAttributeInternal(DOMOBILIZATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DoMobilizationId.
     * @param value value to set the DoMobilizationId
     */
    public void setDoMobilizationId(Number value) {
        setAttributeInternal(DOMOBILIZATIONID, value);
    }

    /**
     * Gets the attribute value for DoLineId, using the alias name DoLineId.
     * @return the value of DoLineId
     */
    public Number getDoLineId() {
        return (Number) getAttributeInternal(DOLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DoLineId.
     * @param value value to set the DoLineId
     */
    public void setDoLineId(Number value) {
        setAttributeInternal(DOLINEID, value);
    }

    /**
     * Gets the attribute value for AssetId, using the alias name AssetId.
     * @return the value of AssetId
     */
    public Number getAssetId() {
        return (Number) getAttributeInternal(ASSETID);
    }

    /**
     * Sets <code>value</code> as the attribute value for AssetId.
     * @param value value to set the AssetId
     */
    public void setAssetId(Number value) {
        setAttributeInternal(ASSETID, value);
    }

    /**
     * Gets the attribute value for MobilizationAssetId, using the alias name MobilizationAssetId.
     * @return the value of MobilizationAssetId
     */
    public Number getMobilizationAssetId() {
        return (Number) getAttributeInternal(MOBILIZATIONASSETID);
    }

    /**
     * Sets <code>value</code> as the attribute value for MobilizationAssetId.
     * @param value value to set the MobilizationAssetId
     */
    public void setMobilizationAssetId(Number value) {
        setAttributeInternal(MOBILIZATIONASSETID, value);
    }

    /**
     * Gets the attribute value for TripDate, using the alias name TripDate.
     * @return the value of TripDate
     */
    public Date getTripDate() {
        return (Date) getAttributeInternal(TRIPDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TripDate.
     * @param value value to set the TripDate
     */
    public void setTripDate(Date value) {
        setAttributeInternal(TRIPDATE, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }


    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }


    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the value of LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }


    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }


    /**
     * Gets the attribute value for ObjectVersionNumber, using the alias name ObjectVersionNumber.
     * @return the value of ObjectVersionNumber
     */
    public Number getObjectVersionNumber() {
        return (Number) getAttributeInternal(OBJECTVERSIONNUMBER);
    }

    /**
     * @param drMobilizationId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number drMobilizationId) {
        return new Key(new Object[] { drMobilizationId });
    }


}

