package model.entity;

import java.math.BigDecimal;

import java.sql.Timestamp;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.NClobDomain;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 31 09:42:56 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxadsBillingAddlChargesEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        AddlChargeId,
        HeaderId,
        ContractChargeId,
        AssetCategoryId,
        RentalType,
        ChargeType,
        Billing,
        Amount,
        ParentContractChargeId,
        MasterContractChargeId,
        CreationDate,
        CreatedBy,
        LastUpdateDate,
        LastUpdatedBy,
        ObjectVersionNumber,
        TaxRateCode,
        VatTaxAmount,
        TaxRateId,
        TaxRatePercent,
        TaskId,
        TaskNumber,
        TaskName,
        ExpenditureTypeId,
        ExpenditureTypeName,
        Description,
        XxadsBillingHdrEO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ADDLCHARGEID = AttributesEnum.AddlChargeId.index();
    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int CONTRACTCHARGEID = AttributesEnum.ContractChargeId.index();
    public static final int ASSETCATEGORYID = AttributesEnum.AssetCategoryId.index();
    public static final int RENTALTYPE = AttributesEnum.RentalType.index();
    public static final int CHARGETYPE = AttributesEnum.ChargeType.index();
    public static final int BILLING = AttributesEnum.Billing.index();
    public static final int AMOUNT = AttributesEnum.Amount.index();
    public static final int PARENTCONTRACTCHARGEID = AttributesEnum.ParentContractChargeId.index();
    public static final int MASTERCONTRACTCHARGEID = AttributesEnum.MasterContractChargeId.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int OBJECTVERSIONNUMBER = AttributesEnum.ObjectVersionNumber.index();
    public static final int TAXRATECODE = AttributesEnum.TaxRateCode.index();
    public static final int VATTAXAMOUNT = AttributesEnum.VatTaxAmount.index();
    public static final int TAXRATEID = AttributesEnum.TaxRateId.index();
    public static final int TAXRATEPERCENT = AttributesEnum.TaxRatePercent.index();
    public static final int TASKID = AttributesEnum.TaskId.index();
    public static final int TASKNUMBER = AttributesEnum.TaskNumber.index();
    public static final int TASKNAME = AttributesEnum.TaskName.index();
    public static final int EXPENDITURETYPEID = AttributesEnum.ExpenditureTypeId.index();
    public static final int EXPENDITURETYPENAME = AttributesEnum.ExpenditureTypeName.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int XXADSBILLINGHDREO = AttributesEnum.XxadsBillingHdrEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxadsBillingAddlChargesEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.entity.XxadsBillingAddlChargesEO");
    }


    /**
     * Gets the attribute value for AddlChargeId, using the alias name AddlChargeId.
     * @return the value of AddlChargeId
     */
    public oracle.jbo.domain.Number getAddlChargeId() {
        return (oracle.jbo.domain.Number) getAttributeInternal(ADDLCHARGEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for AddlChargeId.
     * @param value value to set the AddlChargeId
     */
    public void setAddlChargeId(oracle.jbo.domain.Number value) {
        setAttributeInternal(ADDLCHARGEID, value);
    }

    /**
     * Gets the attribute value for HeaderId, using the alias name HeaderId.
     * @return the value of HeaderId
     */
    public Number getHeaderId() {
        return (Number) getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for HeaderId.
     * @param value value to set the HeaderId
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for ContractChargeId, using the alias name ContractChargeId.
     * @return the value of ContractChargeId
     */
    public Number getContractChargeId() {
        return (Number) getAttributeInternal(CONTRACTCHARGEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContractChargeId.
     * @param value value to set the ContractChargeId
     */
    public void setContractChargeId(Number value) {
        setAttributeInternal(CONTRACTCHARGEID, value);
    }

    /**
     * Gets the attribute value for AssetCategoryId, using the alias name AssetCategoryId.
     * @return the value of AssetCategoryId
     */
    public Number getAssetCategoryId() {
        return (Number) getAttributeInternal(ASSETCATEGORYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for AssetCategoryId.
     * @param value value to set the AssetCategoryId
     */
    public void setAssetCategoryId(Number value) {
        setAttributeInternal(ASSETCATEGORYID, value);
    }

    /**
     * Gets the attribute value for RentalType, using the alias name RentalType.
     * @return the value of RentalType
     */
    public String getRentalType() {
        return (String) getAttributeInternal(RENTALTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for RentalType.
     * @param value value to set the RentalType
     */
    public void setRentalType(String value) {
        setAttributeInternal(RENTALTYPE, value);
    }

    /**
     * Gets the attribute value for ChargeType, using the alias name ChargeType.
     * @return the value of ChargeType
     */
    public String getChargeType() {
        return (String) getAttributeInternal(CHARGETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ChargeType.
     * @param value value to set the ChargeType
     */
    public void setChargeType(String value) {
        setAttributeInternal(CHARGETYPE, value);
    }

    /**
     * Gets the attribute value for Billing, using the alias name Billing.
     * @return the value of Billing
     */
    public String getBilling() {
        return (String) getAttributeInternal(BILLING);
    }

    /**
     * Sets <code>value</code> as the attribute value for Billing.
     * @param value value to set the Billing
     */
    public void setBilling(String value) {
        setAttributeInternal(BILLING, value);
    }

    /**
     * Gets the attribute value for Amount, using the alias name Amount.
     * @return the value of Amount
     */
    public Number getAmount() {
        return (Number) getAttributeInternal(AMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Amount.
     * @param value value to set the Amount
     */
    public void setAmount(Number value) {
        setAttributeInternal(AMOUNT, value);
    }

    /**
     * Gets the attribute value for ParentContractChargeId, using the alias name ParentContractChargeId.
     * @return the value of ParentContractChargeId
     */
    public Number getParentContractChargeId() {
        return (Number) getAttributeInternal(PARENTCONTRACTCHARGEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParentContractChargeId.
     * @param value value to set the ParentContractChargeId
     */
    public void setParentContractChargeId(Number value) {
        setAttributeInternal(PARENTCONTRACTCHARGEID, value);
    }

    /**
     * Gets the attribute value for MasterContractChargeId, using the alias name MasterContractChargeId.
     * @return the value of MasterContractChargeId
     */
    public Number getMasterContractChargeId() {
        return (Number) getAttributeInternal(MASTERCONTRACTCHARGEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for MasterContractChargeId.
     * @param value value to set the MasterContractChargeId
     */
    public void setMasterContractChargeId(Number value) {
        setAttributeInternal(MASTERCONTRACTCHARGEID, value);
    }


    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }


    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }


    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the value of LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }


    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }


    /**
     * Gets the attribute value for ObjectVersionNumber, using the alias name ObjectVersionNumber.
     * @return the value of ObjectVersionNumber
     */
    public Number getObjectVersionNumber() {
        return (Number) getAttributeInternal(OBJECTVERSIONNUMBER);
    }


    /**
     * Gets the attribute value for TaxRateCode, using the alias name TaxRateCode.
     * @return the value of TaxRateCode
     */
    public String getTaxRateCode() {
        return (String) getAttributeInternal(TAXRATECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TaxRateCode.
     * @param value value to set the TaxRateCode
     */
    public void setTaxRateCode(String value) {
        setAttributeInternal(TAXRATECODE, value);
    }

    /**
     * Gets the attribute value for VatTaxAmount, using the alias name VatTaxAmount.
     * @return the value of VatTaxAmount
     */
    public Number getVatTaxAmount() {
        return (Number) getAttributeInternal(VATTAXAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for VatTaxAmount.
     * @param value value to set the VatTaxAmount
     */
    public void setVatTaxAmount(Number value) {
        setAttributeInternal(VATTAXAMOUNT, value);
    }

    /**
     * Gets the attribute value for TaxRateId, using the alias name TaxRateId.
     * @return the value of TaxRateId
     */
    public Number getTaxRateId() {
        return (Number) getAttributeInternal(TAXRATEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for TaxRateId.
     * @param value value to set the TaxRateId
     */
    public void setTaxRateId(Number value) {
        setAttributeInternal(TAXRATEID, value);
    }

    /**
     * Gets the attribute value for TaxRatePercent, using the alias name TaxRatePercent.
     * @return the value of TaxRatePercent
     */
    public Number getTaxRatePercent() {
        return (Number) getAttributeInternal(TAXRATEPERCENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for TaxRatePercent.
     * @param value value to set the TaxRatePercent
     */
    public void setTaxRatePercent(Number value) {
        setAttributeInternal(TAXRATEPERCENT, value);
    }

    /**
     * Gets the attribute value for TaskId, using the alias name TaskId.
     * @return the value of TaskId
     */
    public Number getTaskId() {
        return (Number) getAttributeInternal(TASKID);
    }

    /**
     * Sets <code>value</code> as the attribute value for TaskId.
     * @param value value to set the TaskId
     */
    public void setTaskId(Number value) {
        setAttributeInternal(TASKID, value);
    }

    /**
     * Gets the attribute value for TaskNumber, using the alias name TaskNumber.
     * @return the value of TaskNumber
     */
    public String getTaskNumber() {
        return (String) getAttributeInternal(TASKNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for TaskNumber.
     * @param value value to set the TaskNumber
     */
    public void setTaskNumber(String value) {
        setAttributeInternal(TASKNUMBER, value);
    }

    /**
     * Gets the attribute value for TaskName, using the alias name TaskName.
     * @return the value of TaskName
     */
    public String getTaskName() {
        return (String) getAttributeInternal(TASKNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for TaskName.
     * @param value value to set the TaskName
     */
    public void setTaskName(String value) {
        setAttributeInternal(TASKNAME, value);
    }

    /**
     * Gets the attribute value for ExpenditureTypeId, using the alias name ExpenditureTypeId.
     * @return the value of ExpenditureTypeId
     */
    public Number getExpenditureTypeId() {
        return (Number) getAttributeInternal(EXPENDITURETYPEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExpenditureTypeId.
     * @param value value to set the ExpenditureTypeId
     */
    public void setExpenditureTypeId(Number value) {
        setAttributeInternal(EXPENDITURETYPEID, value);
    }

    /**
     * Gets the attribute value for ExpenditureTypeName, using the alias name ExpenditureTypeName.
     * @return the value of ExpenditureTypeName
     */
    public String getExpenditureTypeName() {
        return (String) getAttributeInternal(EXPENDITURETYPENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExpenditureTypeName.
     * @param value value to set the ExpenditureTypeName
     */
    public void setExpenditureTypeName(String value) {
        setAttributeInternal(EXPENDITURETYPENAME, value);
    }

    /**
     * Gets the attribute value for Description, using the alias name Description.
     * @return the value of Description
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Description.
     * @param value value to set the Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * @return the associated entity XxadsBillingHdrEOImpl.
     */
    public XxadsBillingHdrEOImpl getXxadsBillingHdrEO() {
        return (XxadsBillingHdrEOImpl) getAttributeInternal(XXADSBILLINGHDREO);
    }

    /**
     * Sets <code>value</code> as the associated entity XxadsBillingHdrEOImpl.
     */
    public void setXxadsBillingHdrEO(XxadsBillingHdrEOImpl value) {
        setAttributeInternal(XXADSBILLINGHDREO, value);
    }


    /**
     * @param addlChargeId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number addlChargeId) {
        return new Key(new Object[] { addlChargeId });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        SequenceImpl seq = new SequenceImpl("XXADS_BILLING_ADDL_CHARGES_S",getDBTransaction());
        setAddlChargeId(seq.getSequenceNumber());
    }
    
    private static final byte USERNAME_HISTORY_TYPE =13;
    
    @Override
    protected Object getHistoryContextForAttribute(AttributeDefImpl attr) {
        if (attr.getHistoryKind() == USERNAME_HISTORY_TYPE) {
            // Custom History type logic goes here
            return (String) ((Map)ADFContext.getCurrent().getSessionScope().get("userMap")).get("UserName");
        }
        return super.getHistoryContextForAttribute(attr);
    }
}

