package model.entity;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 27 12:38:54 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxadsDoMobilizationEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        DoMobilizationId,
        DoLineId,
        DoId,
        AssetId,
        MobilizationAssetId,
        TripDate,
        CreationDate,
        CreatedBy,
        LastUpdateDate,
        LastUpdatedBy,
        ObjectVersionNumber,
        MobilizationType,
        ExternalMobAsset,
        OperatorId,
        ExternalOperator,
        ContactNumber;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DOMOBILIZATIONID = AttributesEnum.DoMobilizationId.index();
    public static final int DOLINEID = AttributesEnum.DoLineId.index();
    public static final int DOID = AttributesEnum.DoId.index();
    public static final int ASSETID = AttributesEnum.AssetId.index();
    public static final int MOBILIZATIONASSETID = AttributesEnum.MobilizationAssetId.index();
    public static final int TRIPDATE = AttributesEnum.TripDate.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int OBJECTVERSIONNUMBER = AttributesEnum.ObjectVersionNumber.index();
    public static final int MOBILIZATIONTYPE = AttributesEnum.MobilizationType.index();
    public static final int EXTERNALMOBASSET = AttributesEnum.ExternalMobAsset.index();
    public static final int OPERATORID = AttributesEnum.OperatorId.index();
    public static final int EXTERNALOPERATOR = AttributesEnum.ExternalOperator.index();
    public static final int CONTACTNUMBER = AttributesEnum.ContactNumber.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxadsDoMobilizationEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.entity.XxadsDoMobilizationEO");
    }


    /**
     * Gets the attribute value for DoMobilizationId, using the alias name DoMobilizationId.
     * @return the value of DoMobilizationId
     */
    public oracle.jbo.domain.Number getDoMobilizationId() {
        return (oracle.jbo.domain.Number) getAttributeInternal(DOMOBILIZATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DoMobilizationId.
     * @param value value to set the DoMobilizationId
     */
    public void setDoMobilizationId(oracle.jbo.domain.Number value) {
        setAttributeInternal(DOMOBILIZATIONID, value);
    }

    /**
     * Gets the attribute value for DoLineId, using the alias name DoLineId.
     * @return the value of DoLineId
     */
    public Number getDoLineId() {
        return (Number) getAttributeInternal(DOLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DoLineId.
     * @param value value to set the DoLineId
     */
    public void setDoLineId(Number value) {
        setAttributeInternal(DOLINEID, value);
    }

    /**
     * Gets the attribute value for DoId, using the alias name DoId.
     * @return the value of DoId
     */
    public Number getDoId() {
        return (Number) getAttributeInternal(DOID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DoId.
     * @param value value to set the DoId
     */
    public void setDoId(Number value) {
        setAttributeInternal(DOID, value);
    }

    /**
     * Gets the attribute value for AssetId, using the alias name AssetId.
     * @return the value of AssetId
     */
    public Number getAssetId() {
        return (Number) getAttributeInternal(ASSETID);
    }

    /**
     * Sets <code>value</code> as the attribute value for AssetId.
     * @param value value to set the AssetId
     */
    public void setAssetId(Number value) {
        setAttributeInternal(ASSETID, value);
    }

    /**
     * Gets the attribute value for MobilizationAssetId, using the alias name MobilizationAssetId.
     * @return the value of MobilizationAssetId
     */
    public Number getMobilizationAssetId() {
        return (Number) getAttributeInternal(MOBILIZATIONASSETID);
    }

    /**
     * Sets <code>value</code> as the attribute value for MobilizationAssetId.
     * @param value value to set the MobilizationAssetId
     */
    public void setMobilizationAssetId(Number value) {
        setAttributeInternal(MOBILIZATIONASSETID, value);
    }

    /**
     * Gets the attribute value for TripDate, using the alias name TripDate.
     * @return the value of TripDate
     */
    public Date getTripDate() {
        return (Date) getAttributeInternal(TRIPDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TripDate.
     * @param value value to set the TripDate
     */
    public void setTripDate(Date value) {
        setAttributeInternal(TRIPDATE, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }


    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }


    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the value of LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }


    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }


    /**
     * Gets the attribute value for ObjectVersionNumber, using the alias name ObjectVersionNumber.
     * @return the value of ObjectVersionNumber
     */
    public Number getObjectVersionNumber() {
        return (Number) getAttributeInternal(OBJECTVERSIONNUMBER);
    }


    /**
     * Gets the attribute value for MobilizationType, using the alias name MobilizationType.
     * @return the value of MobilizationType
     */
    public String getMobilizationType() {
        return (String) getAttributeInternal(MOBILIZATIONTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for MobilizationType.
     * @param value value to set the MobilizationType
     */
    public void setMobilizationType(String value) {
        setAttributeInternal(MOBILIZATIONTYPE, value);
    }

    /**
     * Gets the attribute value for ExternalMobAsset, using the alias name ExternalMobAsset.
     * @return the value of ExternalMobAsset
     */
    public String getExternalMobAsset() {
        return (String) getAttributeInternal(EXTERNALMOBASSET);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExternalMobAsset.
     * @param value value to set the ExternalMobAsset
     */
    public void setExternalMobAsset(String value) {
        setAttributeInternal(EXTERNALMOBASSET, value);
    }

    /**
     * Gets the attribute value for OperatorId, using the alias name OperatorId.
     * @return the value of OperatorId
     */
    public Number getOperatorId() {
        return (Number) getAttributeInternal(OPERATORID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OperatorId.
     * @param value value to set the OperatorId
     */
    public void setOperatorId(Number value) {
        setAttributeInternal(OPERATORID, value);
    }

    /**
     * Gets the attribute value for ExternalOperator, using the alias name ExternalOperator.
     * @return the value of ExternalOperator
     */
    public String getExternalOperator() {
        return (String) getAttributeInternal(EXTERNALOPERATOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExternalOperator.
     * @param value value to set the ExternalOperator
     */
    public void setExternalOperator(String value) {
        setAttributeInternal(EXTERNALOPERATOR, value);
    }

    /**
     * Gets the attribute value for ContactNumber, using the alias name ContactNumber.
     * @return the value of ContactNumber
     */
    public String getContactNumber() {
        return (String) getAttributeInternal(CONTACTNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContactNumber.
     * @param value value to set the ContactNumber
     */
    public void setContactNumber(String value) {
        setAttributeInternal(CONTACTNUMBER, value);
    }


    /**
     * @param doMobilizationId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number doMobilizationId) {
        return new Key(new Object[] { doMobilizationId });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    SequenceImpl seq = new SequenceImpl("XXADS_DO_MOBILIZATION_S",getDBTransaction());
    setDoMobilizationId(seq.getSequenceNumber());
    }
    
    private static final byte USERNAME_HISTORY_TYPE =13;
    
    @Override
    protected Object getHistoryContextForAttribute(AttributeDefImpl attr) {
    if (attr.getHistoryKind() == USERNAME_HISTORY_TYPE) {
        // Custom History type logic goes here
        return (String) ((Map)ADFContext.getCurrent().getSessionScope().get("userMap")).get("UserName");
    }
    return super.getHistoryContextForAttribute(attr);
    }
}

