package model.progview;

import java.util.ArrayList;
import java.util.Collection;

import java.util.HashMap;

import oracle.jbo.Key;
import oracle.jbo.RangePagingDataFilter;
import oracle.jbo.ScrollableDataFilter;
import oracle.jbo.server.ProgrammaticViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Feb 10 16:19:57 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TransTemplateVOImpl extends ProgrammaticViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public TransTemplateVOImpl() {
    }

    /**
     * getRangePagingData - for custom java data source support.
     */
    public Collection<Object> getRangePagingData(RangePagingDataFilter filter) {
        Collection<Object> value = super.getRangePagingData(filter);
        return value;
    }

    /**
     * retrieveDataByKey - for custom java data source support.
     */
    public Collection<Object> retrieveDataByKey(Key key, int size) {
        Collection<Object> value = super.retrieveDataByKey(key, size);
        return value;
    }

    /**
     * getScrollableData - for custom java data source support.
     */
    public Collection<Object> getScrollableData(ScrollableDataFilter filter) {
        ArrayList<Object> rows = new ArrayList<Object>();
        HashMap<Object, Object> row = new HashMap<Object, Object>();
        row.put("TransTemplateName", null);
        row.put("TransTemplateId", null);
        row.put("TransCreatedBy", null);
        row.put("TransCreationDate", null);
        row.put("TransActiveFlag", null);
        row.put("TransActiveTemplateName", null);
        row.put("TransAciveTemplateInfo", null);
        row.put("TransBuName", null);
        row.put("TransBuId", null);
        row.put("TransDivision", null);
        row.put("TransDivisionRequired", null);
        row.put("TransDivSegment", null);
        row.put("TransDivFlexValueId", null);
        
        return rows;
    }
}

