package model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 12 15:50:10 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AssetAttributeVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AssetAttributeVOImpl() {
    }
}

