package model.view;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 13 17:03:39 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AssetAttributeValidateVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AssetAttributeValidateVOImpl() {
    }
}

