package model.view;

import java.math.BigDecimal;

import model.entity.XxadsDoLinesEOImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 27 12:36:36 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DeploymentOrderLinesVORowImpl extends ViewRowImpl {


    public static final int ENTITY_XXADSDOLINESEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        AllocationId,
        AllocationLineId,
        AssetId,
        ContractId,
        ContractLineId,
        CreatedBy,
        CreationDate,
        DeploymentDate,
        DoId,
        DoLineId,
        DoLineNum,
        EmployeeId,
        EmployeeType,
        LastUpdateDate,
        LastUpdatedBy,
        MasterContractId,
        MasterContractLineId,
        MeterReading,
        ObjectVersionNumber,
        TransAssetType,
        TransAssetNumber,
        TransPlateNumber,
        TransAssetDesc,
        TransShift,
        TransEmpNumber,
        TransEmpName,
        TransEmpType,
        TransSrcBuId,
        RentalType,
        TransRentalType,
        AllocationDetailId,
        TransOperatorRequired,
        DeploymentOrderAccessoriesVO,
        DeploymentOrderMobilizationVO,
        DeploymentOrderInspectionVO,
        LookupsLOV1,
        DOEmployeeLOV1,
        TsAssetOperatorLovVO1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ALLOCATIONID = AttributesEnum.AllocationId.index();
    public static final int ALLOCATIONLINEID = AttributesEnum.AllocationLineId.index();
    public static final int ASSETID = AttributesEnum.AssetId.index();
    public static final int CONTRACTID = AttributesEnum.ContractId.index();
    public static final int CONTRACTLINEID = AttributesEnum.ContractLineId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int DEPLOYMENTDATE = AttributesEnum.DeploymentDate.index();
    public static final int DOID = AttributesEnum.DoId.index();
    public static final int DOLINEID = AttributesEnum.DoLineId.index();
    public static final int DOLINENUM = AttributesEnum.DoLineNum.index();
    public static final int EMPLOYEEID = AttributesEnum.EmployeeId.index();
    public static final int EMPLOYEETYPE = AttributesEnum.EmployeeType.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int MASTERCONTRACTID = AttributesEnum.MasterContractId.index();
    public static final int MASTERCONTRACTLINEID = AttributesEnum.MasterContractLineId.index();
    public static final int METERREADING = AttributesEnum.MeterReading.index();
    public static final int OBJECTVERSIONNUMBER = AttributesEnum.ObjectVersionNumber.index();
    public static final int TRANSASSETTYPE = AttributesEnum.TransAssetType.index();
    public static final int TRANSASSETNUMBER = AttributesEnum.TransAssetNumber.index();
    public static final int TRANSPLATENUMBER = AttributesEnum.TransPlateNumber.index();
    public static final int TRANSASSETDESC = AttributesEnum.TransAssetDesc.index();
    public static final int TRANSSHIFT = AttributesEnum.TransShift.index();
    public static final int TRANSEMPNUMBER = AttributesEnum.TransEmpNumber.index();
    public static final int TRANSEMPNAME = AttributesEnum.TransEmpName.index();
    public static final int TRANSEMPTYPE = AttributesEnum.TransEmpType.index();
    public static final int TRANSSRCBUID = AttributesEnum.TransSrcBuId.index();
    public static final int RENTALTYPE = AttributesEnum.RentalType.index();
    public static final int TRANSRENTALTYPE = AttributesEnum.TransRentalType.index();
    public static final int ALLOCATIONDETAILID = AttributesEnum.AllocationDetailId.index();
    public static final int TRANSOPERATORREQUIRED = AttributesEnum.TransOperatorRequired.index();
    public static final int DEPLOYMENTORDERACCESSORIESVO = AttributesEnum.DeploymentOrderAccessoriesVO.index();
    public static final int DEPLOYMENTORDERMOBILIZATIONVO = AttributesEnum.DeploymentOrderMobilizationVO.index();
    public static final int DEPLOYMENTORDERINSPECTIONVO = AttributesEnum.DeploymentOrderInspectionVO.index();
    public static final int LOOKUPSLOV1 = AttributesEnum.LookupsLOV1.index();
    public static final int DOEMPLOYEELOV1 = AttributesEnum.DOEmployeeLOV1.index();
    public static final int TSASSETOPERATORLOVVO1 = AttributesEnum.TsAssetOperatorLovVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DeploymentOrderLinesVORowImpl() {
    }

    /**
     * Gets XxadsDoLinesEO entity object.
     * @return the XxadsDoLinesEO
     */
    public XxadsDoLinesEOImpl getXxadsDoLinesEO() {
        return (XxadsDoLinesEOImpl) getEntity(ENTITY_XXADSDOLINESEO);
    }

    /**
     * Gets the attribute value for ALLOCATION_ID using the alias name AllocationId.
     * @return the ALLOCATION_ID
     */
    public Number getAllocationId() {
        return (Number) getAttributeInternal(ALLOCATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for ALLOCATION_ID using the alias name AllocationId.
     * @param value value to set the ALLOCATION_ID
     */
    public void setAllocationId(Number value) {
        setAttributeInternal(ALLOCATIONID, value);
    }

    /**
     * Gets the attribute value for ALLOCATION_LINE_ID using the alias name AllocationLineId.
     * @return the ALLOCATION_LINE_ID
     */
    public Number getAllocationLineId() {
        return (Number) getAttributeInternal(ALLOCATIONLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for ALLOCATION_LINE_ID using the alias name AllocationLineId.
     * @param value value to set the ALLOCATION_LINE_ID
     */
    public void setAllocationLineId(Number value) {
        setAttributeInternal(ALLOCATIONLINEID, value);
    }

    /**
     * Gets the attribute value for ASSET_ID using the alias name AssetId.
     * @return the ASSET_ID
     */
    public Number getAssetId() {
        return (Number) getAttributeInternal(ASSETID);
    }

    /**
     * Sets <code>value</code> as attribute value for ASSET_ID using the alias name AssetId.
     * @param value value to set the ASSET_ID
     */
    public void setAssetId(Number value) {
        setAttributeInternal(ASSETID, value);
    }

    /**
     * Gets the attribute value for CONTRACT_ID using the alias name ContractId.
     * @return the CONTRACT_ID
     */
    public Number getContractId() {
        return (Number) getAttributeInternal(CONTRACTID);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_ID using the alias name ContractId.
     * @param value value to set the CONTRACT_ID
     */
    public void setContractId(Number value) {
        setAttributeInternal(CONTRACTID, value);
    }

    /**
     * Gets the attribute value for CONTRACT_LINE_ID using the alias name ContractLineId.
     * @return the CONTRACT_LINE_ID
     */
    public Number getContractLineId() {
        return (Number) getAttributeInternal(CONTRACTLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_LINE_ID using the alias name ContractLineId.
     * @param value value to set the CONTRACT_LINE_ID
     */
    public void setContractLineId(Number value) {
        setAttributeInternal(CONTRACTLINEID, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for DEPLOYMENT_DATE using the alias name DeploymentDate.
     * @return the DEPLOYMENT_DATE
     */
    public Date getDeploymentDate() {
        return (Date) getAttributeInternal(DEPLOYMENTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPLOYMENT_DATE using the alias name DeploymentDate.
     * @param value value to set the DEPLOYMENT_DATE
     */
    public void setDeploymentDate(Date value) {
        setAttributeInternal(DEPLOYMENTDATE, value);
    }

    /**
     * Gets the attribute value for DO_ID using the alias name DoId.
     * @return the DO_ID
     */
    public Number getDoId() {
        return (Number) getAttributeInternal(DOID);
    }

    /**
     * Sets <code>value</code> as attribute value for DO_ID using the alias name DoId.
     * @param value value to set the DO_ID
     */
    public void setDoId(Number value) {
        setAttributeInternal(DOID, value);
    }

    /**
     * Gets the attribute value for DO_LINE_ID using the alias name DoLineId.
     * @return the DO_LINE_ID
     */
    public Number getDoLineId() {
        return (Number) getAttributeInternal(DOLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for DO_LINE_ID using the alias name DoLineId.
     * @param value value to set the DO_LINE_ID
     */
    public void setDoLineId(Number value) {
        setAttributeInternal(DOLINEID, value);
    }

    /**
     * Gets the attribute value for DO_LINE_NUM using the alias name DoLineNum.
     * @return the DO_LINE_NUM
     */
    public Number getDoLineNum() {
        return (Number) getAttributeInternal(DOLINENUM);
    }

    /**
     * Sets <code>value</code> as attribute value for DO_LINE_NUM using the alias name DoLineNum.
     * @param value value to set the DO_LINE_NUM
     */
    public void setDoLineNum(Number value) {
        setAttributeInternal(DOLINENUM, value);
    }

    /**
     * Gets the attribute value for EMPLOYEE_ID using the alias name EmployeeId.
     * @return the EMPLOYEE_ID
     */
    public Number getEmployeeId() {
        return (Number) getAttributeInternal(EMPLOYEEID);
    }

    /**
     * Sets <code>value</code> as attribute value for EMPLOYEE_ID using the alias name EmployeeId.
     * @param value value to set the EMPLOYEE_ID
     */
    public void setEmployeeId(Number value) {
        setAttributeInternal(EMPLOYEEID, value);
    }

    /**
     * Gets the attribute value for EMPLOYEE_TYPE using the alias name EmployeeType.
     * @return the EMPLOYEE_TYPE
     */
    public String getEmployeeType() {
        return (String) getAttributeInternal(EMPLOYEETYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for EMPLOYEE_TYPE using the alias name EmployeeType.
     * @param value value to set the EMPLOYEE_TYPE
     */
    public void setEmployeeType(String value) {
        setAttributeInternal(EMPLOYEETYPE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for MASTER_CONTRACT_ID using the alias name MasterContractId.
     * @return the MASTER_CONTRACT_ID
     */
    public Number getMasterContractId() {
        return (Number) getAttributeInternal(MASTERCONTRACTID);
    }

    /**
     * Sets <code>value</code> as attribute value for MASTER_CONTRACT_ID using the alias name MasterContractId.
     * @param value value to set the MASTER_CONTRACT_ID
     */
    public void setMasterContractId(Number value) {
        setAttributeInternal(MASTERCONTRACTID, value);
    }

    /**
     * Gets the attribute value for MASTER_CONTRACT_LINE_ID using the alias name MasterContractLineId.
     * @return the MASTER_CONTRACT_LINE_ID
     */
    public Number getMasterContractLineId() {
        return (Number) getAttributeInternal(MASTERCONTRACTLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for MASTER_CONTRACT_LINE_ID using the alias name MasterContractLineId.
     * @param value value to set the MASTER_CONTRACT_LINE_ID
     */
    public void setMasterContractLineId(Number value) {
        setAttributeInternal(MASTERCONTRACTLINEID, value);
    }

    /**
     * Gets the attribute value for METER_READING using the alias name MeterReading.
     * @return the METER_READING
     */
    public Number getMeterReading() {
        return (Number) getAttributeInternal(METERREADING);
    }

    /**
     * Sets <code>value</code> as attribute value for METER_READING using the alias name MeterReading.
     * @param value value to set the METER_READING
     */
    public void setMeterReading(Number value) {
        setAttributeInternal(METERREADING, value);
    }

    /**
     * Gets the attribute value for OBJECT_VERSION_NUMBER using the alias name ObjectVersionNumber.
     * @return the OBJECT_VERSION_NUMBER
     */
    public Number getObjectVersionNumber() {
        return (Number) getAttributeInternal(OBJECTVERSIONNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for OBJECT_VERSION_NUMBER using the alias name ObjectVersionNumber.
     * @param value value to set the OBJECT_VERSION_NUMBER
     */
    public void setObjectVersionNumber(Number value) {
        setAttributeInternal(OBJECTVERSIONNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransAssetType.
     * @return the TransAssetType
     */
    public String getTransAssetType() {
        return (String) getAttributeInternal(TRANSASSETTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransAssetType.
     * @param value value to set the  TransAssetType
     */
    public void setTransAssetType(String value) {
        setAttributeInternal(TRANSASSETTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransAssetNumber.
     * @return the TransAssetNumber
     */
    public String getTransAssetNumber() {
        return (String) getAttributeInternal(TRANSASSETNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransAssetNumber.
     * @param value value to set the  TransAssetNumber
     */
    public void setTransAssetNumber(String value) {
        setAttributeInternal(TRANSASSETNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransPlateNumber.
     * @return the TransPlateNumber
     */
    public String getTransPlateNumber() {
        return (String) getAttributeInternal(TRANSPLATENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransPlateNumber.
     * @param value value to set the  TransPlateNumber
     */
    public void setTransPlateNumber(String value) {
        setAttributeInternal(TRANSPLATENUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransAssetDesc.
     * @return the TransAssetDesc
     */
    public String getTransAssetDesc() {
        return (String) getAttributeInternal(TRANSASSETDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransAssetDesc.
     * @param value value to set the  TransAssetDesc
     */
    public void setTransAssetDesc(String value) {
        setAttributeInternal(TRANSASSETDESC, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransShift.
     * @return the TransShift
     */
    public String getTransShift() {
        return (String) getAttributeInternal(TRANSSHIFT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransShift.
     * @param value value to set the  TransShift
     */
    public void setTransShift(String value) {
        setAttributeInternal(TRANSSHIFT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransEmpNumber.
     * @return the TransEmpNumber
     */
    public String getTransEmpNumber() {
        return (String) getAttributeInternal(TRANSEMPNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransEmpNumber.
     * @param value value to set the  TransEmpNumber
     */
    public void setTransEmpNumber(String value) {
        setAttributeInternal(TRANSEMPNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransEmpName.
     * @return the TransEmpName
     */
    public String getTransEmpName() {
        return (String) getAttributeInternal(TRANSEMPNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransEmpName.
     * @param value value to set the  TransEmpName
     */
    public void setTransEmpName(String value) {
        setAttributeInternal(TRANSEMPNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransEmpType.
     * @return the TransEmpType
     */
    public String getTransEmpType() {
        return (String) getAttributeInternal(TRANSEMPTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransEmpType.
     * @param value value to set the  TransEmpType
     */
    public void setTransEmpType(String value) {
        setAttributeInternal(TRANSEMPTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransSrcBuId.
     * @return the TransSrcBuId
     */
    public Number getTransSrcBuId() {
        return (Number) getAttributeInternal(TRANSSRCBUID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransSrcBuId.
     * @param value value to set the  TransSrcBuId
     */
    public void setTransSrcBuId(Number value) {
        setAttributeInternal(TRANSSRCBUID, value);
    }

    /**
     * Gets the attribute value for RENTAL_TYPE using the alias name RentalType.
     * @return the RENTAL_TYPE
     */
    public String getRentalType() {
        return (String) getAttributeInternal(RENTALTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for RENTAL_TYPE using the alias name RentalType.
     * @param value value to set the RENTAL_TYPE
     */
    public void setRentalType(String value) {
        setAttributeInternal(RENTALTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransRentalType.
     * @return the TransRentalType
     */
    public String getTransRentalType() {
        return (String) getAttributeInternal(TRANSRENTALTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransRentalType.
     * @param value value to set the  TransRentalType
     */
    public void setTransRentalType(String value) {
        setAttributeInternal(TRANSRENTALTYPE, value);
    }

    /**
     * Gets the attribute value for ALLOCATION_DETAIL_ID using the alias name AllocationDetailId.
     * @return the ALLOCATION_DETAIL_ID
     */
    public Number getAllocationDetailId() {
        return (Number) getAttributeInternal(ALLOCATIONDETAILID);
    }

    /**
     * Sets <code>value</code> as attribute value for ALLOCATION_DETAIL_ID using the alias name AllocationDetailId.
     * @param value value to set the ALLOCATION_DETAIL_ID
     */
    public void setAllocationDetailId(Number value) {
        setAttributeInternal(ALLOCATIONDETAILID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransOperatorRequired.
     * @return the TransOperatorRequired
     */
    public String getTransOperatorRequired() {
        return (String) getAttributeInternal(TRANSOPERATORREQUIRED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransOperatorRequired.
     * @param value value to set the  TransOperatorRequired
     */
    public void setTransOperatorRequired(String value) {
        setAttributeInternal(TRANSOPERATORREQUIRED, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link DeploymentOrderAccessoriesVO.
     */
    public RowIterator getDeploymentOrderAccessoriesVO() {
        return (RowIterator) getAttributeInternal(DEPLOYMENTORDERACCESSORIESVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link DeploymentOrderMobilizationVO.
     */
    public RowIterator getDeploymentOrderMobilizationVO() {
        return (RowIterator) getAttributeInternal(DEPLOYMENTORDERMOBILIZATIONVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link DeploymentOrderInspectionVO.
     */
    public RowIterator getDeploymentOrderInspectionVO() {
        return (RowIterator) getAttributeInternal(DEPLOYMENTORDERINSPECTIONVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LookupsLOV1.
     */
    public RowSet getLookupsLOV1() {
        return (RowSet) getAttributeInternal(LOOKUPSLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DOEmployeeLOV1.
     */
    public RowSet getDOEmployeeLOV1() {
        return (RowSet) getAttributeInternal(DOEMPLOYEELOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> TsAssetOperatorLovVO1.
     */
    public RowSet getTsAssetOperatorLovVO1() {
        return (RowSet) getAttributeInternal(TSASSETOPERATORLOVVO1);
    }
}

