package model.view;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.domain.ClobDomain;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 06 12:14:46 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class QuoteReportHdrVORowImpl extends ViewRowImpl {


    public static final int ENTITY_XXADSQUOTATIONREPORTHDR = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        CurrencyCode,
        CustTrnNo,
        CustomerName,
        MobilizationValue,
        Note,
        QuotationId,
        QuoteDate,
        QuoteNumber,
        Ref,
        Remarks,
        SalesPerson,
        ScopeOfWork,
        SiteContactPerson,
        SiteContactPersonEmail,
        SiteContactPersonNumber,
        TermsConditions,
        SalesPersonPhone,
        QuoteReportLinesVO;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CURRENCYCODE = AttributesEnum.CurrencyCode.index();
    public static final int CUSTTRNNO = AttributesEnum.CustTrnNo.index();
    public static final int CUSTOMERNAME = AttributesEnum.CustomerName.index();
    public static final int MOBILIZATIONVALUE = AttributesEnum.MobilizationValue.index();
    public static final int NOTE = AttributesEnum.Note.index();
    public static final int QUOTATIONID = AttributesEnum.QuotationId.index();
    public static final int QUOTEDATE = AttributesEnum.QuoteDate.index();
    public static final int QUOTENUMBER = AttributesEnum.QuoteNumber.index();
    public static final int REF = AttributesEnum.Ref.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int SALESPERSON = AttributesEnum.SalesPerson.index();
    public static final int SCOPEOFWORK = AttributesEnum.ScopeOfWork.index();
    public static final int SITECONTACTPERSON = AttributesEnum.SiteContactPerson.index();
    public static final int SITECONTACTPERSONEMAIL = AttributesEnum.SiteContactPersonEmail.index();
    public static final int SITECONTACTPERSONNUMBER = AttributesEnum.SiteContactPersonNumber.index();
    public static final int TERMSCONDITIONS = AttributesEnum.TermsConditions.index();
    public static final int SALESPERSONPHONE = AttributesEnum.SalesPersonPhone.index();
    public static final int QUOTEREPORTLINESVO = AttributesEnum.QuoteReportLinesVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public QuoteReportHdrVORowImpl() {
    }
}

