package model.view;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.RowIterator;
import oracle.jbo.domain.ClobDomain;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 25 15:30:08 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RentalContractPrintHdrVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ContractId,
        ContractNumber,
        CustomerName,
        SiteContactPerson,
        Address,
        ContactEmail,
        ContactNumber,
        ContractDate,
        Tenure,
        QuoteNumber,
        QuoteDate,
        Lpo,
        Name,
        DueDays,
        TermsConditions,
        SiteLocation,
        CurrencyCode,
        RentalContractPrintLinesVO,
        ContractDeployAssetsPrintVO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CONTRACTID = AttributesEnum.ContractId.index();
    public static final int CONTRACTNUMBER = AttributesEnum.ContractNumber.index();
    public static final int CUSTOMERNAME = AttributesEnum.CustomerName.index();
    public static final int SITECONTACTPERSON = AttributesEnum.SiteContactPerson.index();
    public static final int ADDRESS = AttributesEnum.Address.index();
    public static final int CONTACTEMAIL = AttributesEnum.ContactEmail.index();
    public static final int CONTACTNUMBER = AttributesEnum.ContactNumber.index();
    public static final int CONTRACTDATE = AttributesEnum.ContractDate.index();
    public static final int TENURE = AttributesEnum.Tenure.index();
    public static final int QUOTENUMBER = AttributesEnum.QuoteNumber.index();
    public static final int QUOTEDATE = AttributesEnum.QuoteDate.index();
    public static final int LPO = AttributesEnum.Lpo.index();
    public static final int NAME = AttributesEnum.Name.index();
    public static final int DUEDAYS = AttributesEnum.DueDays.index();
    public static final int TERMSCONDITIONS = AttributesEnum.TermsConditions.index();
    public static final int SITELOCATION = AttributesEnum.SiteLocation.index();
    public static final int CURRENCYCODE = AttributesEnum.CurrencyCode.index();
    public static final int RENTALCONTRACTPRINTLINESVO = AttributesEnum.RentalContractPrintLinesVO.index();
    public static final int CONTRACTDEPLOYASSETSPRINTVO = AttributesEnum.ContractDeployAssetsPrintVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public RentalContractPrintHdrVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute ContractId.
     * @return the ContractId
     */
    public Number getContractId() {
        return (Number) getAttributeInternal(CONTRACTID);
    }

    /**
     * Gets the attribute value for the calculated attribute ContractNumber.
     * @return the ContractNumber
     */
    public String getContractNumber() {
        return (String) getAttributeInternal(CONTRACTNUMBER);
    }

    /**
     * Gets the attribute value for the calculated attribute CustomerName.
     * @return the CustomerName
     */
    public String getCustomerName() {
        return (String) getAttributeInternal(CUSTOMERNAME);
    }

    /**
     * Gets the attribute value for the calculated attribute SiteContactPerson.
     * @return the SiteContactPerson
     */
    public String getSiteContactPerson() {
        return (String) getAttributeInternal(SITECONTACTPERSON);
    }

    /**
     * Gets the attribute value for the calculated attribute Address.
     * @return the Address
     */
    public String getAddress() {
        return (String) getAttributeInternal(ADDRESS);
    }

    /**
     * Gets the attribute value for the calculated attribute ContactEmail.
     * @return the ContactEmail
     */
    public String getContactEmail() {
        return (String) getAttributeInternal(CONTACTEMAIL);
    }

    /**
     * Gets the attribute value for the calculated attribute ContactNumber.
     * @return the ContactNumber
     */
    public String getContactNumber() {
        return (String) getAttributeInternal(CONTACTNUMBER);
    }

    /**
     * Gets the attribute value for the calculated attribute ContractDate.
     * @return the ContractDate
     */
    public Date getContractDate() {
        return (Date) getAttributeInternal(CONTRACTDATE);
    }

    /**
     * Gets the attribute value for the calculated attribute Tenure.
     * @return the Tenure
     */
    public Number getTenure() {
        return (Number) getAttributeInternal(TENURE);
    }

    /**
     * Gets the attribute value for the calculated attribute QuoteNumber.
     * @return the QuoteNumber
     */
    public String getQuoteNumber() {
        return (String) getAttributeInternal(QUOTENUMBER);
    }

    /**
     * Gets the attribute value for the calculated attribute QuoteDate.
     * @return the QuoteDate
     */
    public Date getQuoteDate() {
        return (Date) getAttributeInternal(QUOTEDATE);
    }

    /**
     * Gets the attribute value for the calculated attribute Lpo.
     * @return the Lpo
     */
    public String getLpo() {
        return (String) getAttributeInternal(LPO);
    }

    /**
     * Gets the attribute value for the calculated attribute Name.
     * @return the Name
     */
    public String getName() {
        return (String) getAttributeInternal(NAME);
    }

    /**
     * Gets the attribute value for the calculated attribute DueDays.
     * @return the DueDays
     */
    public Number getDueDays() {
        return (Number) getAttributeInternal(DUEDAYS);
    }

    /**
     * Gets the attribute value for the calculated attribute TermsConditions.
     * @return the TermsConditions
     */
    public ClobDomain getTermsConditions() {
        return (ClobDomain) getAttributeInternal(TERMSCONDITIONS);
    }

    /**
     * Gets the attribute value for the calculated attribute SiteLocation.
     * @return the SiteLocation
     */
    public String getSiteLocation() {
        return (String) getAttributeInternal(SITELOCATION);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrencyCode.
     * @return the CurrencyCode
     */
    public String getCurrencyCode() {
        return (String) getAttributeInternal(CURRENCYCODE);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link RentalContractPrintLinesVO.
     */
    public RowIterator getRentalContractPrintLinesVO() {
        return (RowIterator) getAttributeInternal(RENTALCONTRACTPRINTLINESVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ContractDeployAssetsPrintVO.
     */
    public RowIterator getContractDeployAssetsPrintVO() {
        return (RowIterator) getAttributeInternal(CONTRACTDEPLOYASSETSPRINTVO);
    }
}

