package model.view;

import model.entity.XxadsRentalQuoteEOImpl;
import model.entity.XxadsRentalQuoteLinesEOImpl;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 11 16:44:20 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RentalQuoteLinesVORowImpl extends ViewRowImpl {


    public static final int ENTITY_XXADSRENTALQUOTELINESEO = 0;
    public static final int ENTITY_XXADSRENTALQUOTEEO = 1;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ActiveFlag,
        CategoryId,
        CreatedBy,
        CreationDate,
        FuelOption,
        HiringBasisRuleId,
        LastUpdateDate,
        LastUpdatedBy,
        LineNum,
        LineValue,
        MarginPercentage,
        MasterQuotationId,
        MasterQuoteLineId,
        MinChargeUnit,
        MinChargeValue,
        MobilizationRequired,
        ObjectVersionNumber,
        OffHireDate,
        OnHireDate,
        OperatorOption,
        Ot1Rate,
        Ot2Rate,
        ParentQuotationId,
        ParentQuoteLineId,
        Quantity,
        QuotationId,
        QuoteLineId,
        Remarks,
        RentalType,
        RequestId,
        RequestLineId,
        RequestLineNum,
        Shift,
        StandardRate,
        TransAssetRequestNum,
        TransRentalType,
        TransAssetCategory,
        TransAssetDescription,
        TransHiringBasis,
        TransFixedVariable,
        TransOperatorOption,
        TransFuelOption,
        TransMobilizationRequired,
        TransShift,
        BuId,
        QuotationId1,
        CustomerId,
        DeptFlexValueId,
        DivFlexValueId,
        ProjectId,
        CustomerType,
        ReqBuId,
        SrcDivFlexValId,
        SiteUseId,
        TransHdrBuId,
        TransHdrSrcDivFlexValId,
        TransHdrReqBuId,
        TransHdrCustType,
        TransHdrProjectId,
        TransHdrDivFlexValueId,
        TransHdrDeptFlexValueId,
        TransHdrCustomerId,
        TransHdrSiteUseId,
        TransMinChargeUnit,
        UnitRate,
        TransNoofDays,
        TransStandardHours,
        TaxRateId,
        TaxRatePercent,
        VatTaxAmount,
        TaxRateCode,
        TransNetAmount,
        CategoryDescription,
        QuoteAssetRequestLovVO1,
        LookupsLOV1,
        RentalTypeBasedCategoryLOV1,
        HiringBasisLOVVO1,
        OptionsLOVVO1,
        OptionsLOVVO2,
        LookupsLOV2,
        QuoteAssetRequestLinesLovVO1,
        QuoteChargeableUnitLovVO1,
        LookupsLOV3,
        TaxCodesLOV1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return RentalQuoteLinesVORowImpl.AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return RentalQuoteLinesVORowImpl.AttributesEnum.firstIndex() + RentalQuoteLinesVORowImpl.AttributesEnum
                                                                                                    .staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = RentalQuoteLinesVORowImpl.AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ACTIVEFLAG = AttributesEnum.ActiveFlag.index();
    public static final int CATEGORYID = AttributesEnum.CategoryId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int FUELOPTION = AttributesEnum.FuelOption.index();
    public static final int HIRINGBASISRULEID = AttributesEnum.HiringBasisRuleId.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LINENUM = AttributesEnum.LineNum.index();
    public static final int LINEVALUE = AttributesEnum.LineValue.index();
    public static final int MARGINPERCENTAGE = AttributesEnum.MarginPercentage.index();
    public static final int MASTERQUOTATIONID = AttributesEnum.MasterQuotationId.index();
    public static final int MASTERQUOTELINEID = AttributesEnum.MasterQuoteLineId.index();
    public static final int MINCHARGEUNIT = AttributesEnum.MinChargeUnit.index();
    public static final int MINCHARGEVALUE = AttributesEnum.MinChargeValue.index();
    public static final int MOBILIZATIONREQUIRED = AttributesEnum.MobilizationRequired.index();
    public static final int OBJECTVERSIONNUMBER = AttributesEnum.ObjectVersionNumber.index();
    public static final int OFFHIREDATE = AttributesEnum.OffHireDate.index();
    public static final int ONHIREDATE = AttributesEnum.OnHireDate.index();
    public static final int OPERATOROPTION = AttributesEnum.OperatorOption.index();
    public static final int OT1RATE = AttributesEnum.Ot1Rate.index();
    public static final int OT2RATE = AttributesEnum.Ot2Rate.index();
    public static final int PARENTQUOTATIONID = AttributesEnum.ParentQuotationId.index();
    public static final int PARENTQUOTELINEID = AttributesEnum.ParentQuoteLineId.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int QUOTATIONID = AttributesEnum.QuotationId.index();
    public static final int QUOTELINEID = AttributesEnum.QuoteLineId.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int RENTALTYPE = AttributesEnum.RentalType.index();
    public static final int REQUESTID = AttributesEnum.RequestId.index();
    public static final int REQUESTLINEID = AttributesEnum.RequestLineId.index();
    public static final int REQUESTLINENUM = AttributesEnum.RequestLineNum.index();
    public static final int SHIFT = AttributesEnum.Shift.index();
    public static final int STANDARDRATE = AttributesEnum.StandardRate.index();
    public static final int TRANSASSETREQUESTNUM = AttributesEnum.TransAssetRequestNum.index();
    public static final int TRANSRENTALTYPE = AttributesEnum.TransRentalType.index();
    public static final int TRANSASSETCATEGORY = AttributesEnum.TransAssetCategory.index();
    public static final int TRANSASSETDESCRIPTION = AttributesEnum.TransAssetDescription.index();
    public static final int TRANSHIRINGBASIS = AttributesEnum.TransHiringBasis.index();
    public static final int TRANSFIXEDVARIABLE = AttributesEnum.TransFixedVariable.index();
    public static final int TRANSOPERATOROPTION = AttributesEnum.TransOperatorOption.index();
    public static final int TRANSFUELOPTION = AttributesEnum.TransFuelOption.index();
    public static final int TRANSMOBILIZATIONREQUIRED = AttributesEnum.TransMobilizationRequired.index();
    public static final int TRANSSHIFT = AttributesEnum.TransShift.index();
    public static final int BUID = AttributesEnum.BuId.index();
    public static final int QUOTATIONID1 = AttributesEnum.QuotationId1.index();
    public static final int CUSTOMERID = AttributesEnum.CustomerId.index();
    public static final int DEPTFLEXVALUEID = AttributesEnum.DeptFlexValueId.index();
    public static final int DIVFLEXVALUEID = AttributesEnum.DivFlexValueId.index();
    public static final int PROJECTID = AttributesEnum.ProjectId.index();
    public static final int CUSTOMERTYPE = AttributesEnum.CustomerType.index();
    public static final int REQBUID = AttributesEnum.ReqBuId.index();
    public static final int SRCDIVFLEXVALID = AttributesEnum.SrcDivFlexValId.index();
    public static final int SITEUSEID = AttributesEnum.SiteUseId.index();
    public static final int TRANSHDRBUID = AttributesEnum.TransHdrBuId.index();
    public static final int TRANSHDRSRCDIVFLEXVALID = AttributesEnum.TransHdrSrcDivFlexValId.index();
    public static final int TRANSHDRREQBUID = AttributesEnum.TransHdrReqBuId.index();
    public static final int TRANSHDRCUSTTYPE = AttributesEnum.TransHdrCustType.index();
    public static final int TRANSHDRPROJECTID = AttributesEnum.TransHdrProjectId.index();
    public static final int TRANSHDRDIVFLEXVALUEID = AttributesEnum.TransHdrDivFlexValueId.index();
    public static final int TRANSHDRDEPTFLEXVALUEID = AttributesEnum.TransHdrDeptFlexValueId.index();
    public static final int TRANSHDRCUSTOMERID = AttributesEnum.TransHdrCustomerId.index();
    public static final int TRANSHDRSITEUSEID = AttributesEnum.TransHdrSiteUseId.index();
    public static final int TRANSMINCHARGEUNIT = AttributesEnum.TransMinChargeUnit.index();
    public static final int UNITRATE = AttributesEnum.UnitRate.index();
    public static final int TRANSNOOFDAYS = AttributesEnum.TransNoofDays.index();
    public static final int TRANSSTANDARDHOURS = AttributesEnum.TransStandardHours.index();
    public static final int TAXRATEID = AttributesEnum.TaxRateId.index();
    public static final int TAXRATEPERCENT = AttributesEnum.TaxRatePercent.index();
    public static final int VATTAXAMOUNT = AttributesEnum.VatTaxAmount.index();
    public static final int TAXRATECODE = AttributesEnum.TaxRateCode.index();
    public static final int TRANSNETAMOUNT = AttributesEnum.TransNetAmount.index();
    public static final int CATEGORYDESCRIPTION = AttributesEnum.CategoryDescription.index();
    public static final int QUOTEASSETREQUESTLOVVO1 = AttributesEnum.QuoteAssetRequestLovVO1.index();
    public static final int LOOKUPSLOV1 = AttributesEnum.LookupsLOV1.index();
    public static final int RENTALTYPEBASEDCATEGORYLOV1 = AttributesEnum.RentalTypeBasedCategoryLOV1.index();
    public static final int HIRINGBASISLOVVO1 = AttributesEnum.HiringBasisLOVVO1.index();
    public static final int OPTIONSLOVVO1 = AttributesEnum.OptionsLOVVO1.index();
    public static final int OPTIONSLOVVO2 = AttributesEnum.OptionsLOVVO2.index();
    public static final int LOOKUPSLOV2 = AttributesEnum.LookupsLOV2.index();
    public static final int QUOTEASSETREQUESTLINESLOVVO1 = AttributesEnum.QuoteAssetRequestLinesLovVO1.index();
    public static final int QUOTECHARGEABLEUNITLOVVO1 = AttributesEnum.QuoteChargeableUnitLovVO1.index();
    public static final int LOOKUPSLOV3 = AttributesEnum.LookupsLOV3.index();
    public static final int TAXCODESLOV1 = AttributesEnum.TaxCodesLOV1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public RentalQuoteLinesVORowImpl() {
    }

    /**
     * Gets XxadsRentalQuoteLinesEO entity object.
     * @return the XxadsRentalQuoteLinesEO
     */
    public XxadsRentalQuoteLinesEOImpl getXxadsRentalQuoteLinesEO() {
        return (XxadsRentalQuoteLinesEOImpl) getEntity(ENTITY_XXADSRENTALQUOTELINESEO);
    }

    /**
     * Gets XxadsRentalQuoteEO entity object.
     * @return the XxadsRentalQuoteEO
     */
    public XxadsRentalQuoteEOImpl getXxadsRentalQuoteEO() {
        return (XxadsRentalQuoteEOImpl) getEntity(ENTITY_XXADSRENTALQUOTEEO);
    }

    /**
     * Gets the attribute value for ACTIVE_FLAG using the alias name ActiveFlag.
     * @return the ACTIVE_FLAG
     */
    public String getActiveFlag() {
        return (String) getAttributeInternal(ACTIVEFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTIVE_FLAG using the alias name ActiveFlag.
     * @param value value to set the ACTIVE_FLAG
     */
    public void setActiveFlag(String value) {
        setAttributeInternal(ACTIVEFLAG, value);
    }

    /**
     * Gets the attribute value for CATEGORY_ID using the alias name CategoryId.
     * @return the CATEGORY_ID
     */
    public Number getCategoryId() {
        return (Number) getAttributeInternal(CATEGORYID);
    }

    /**
     * Sets <code>value</code> as attribute value for CATEGORY_ID using the alias name CategoryId.
     * @param value value to set the CATEGORY_ID
     */
    public void setCategoryId(Number value) {
        setAttributeInternal(CATEGORYID, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for FUEL_OPTION using the alias name FuelOption.
     * @return the FUEL_OPTION
     */
    public String getFuelOption() {
        return (String) getAttributeInternal(FUELOPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for FUEL_OPTION using the alias name FuelOption.
     * @param value value to set the FUEL_OPTION
     */
    public void setFuelOption(String value) {
        setAttributeInternal(FUELOPTION, value);
    }

    /**
     * Gets the attribute value for HIRING_BASIS_RULE_ID using the alias name HiringBasisRuleId.
     * @return the HIRING_BASIS_RULE_ID
     */
    public Number getHiringBasisRuleId() {
        return (Number) getAttributeInternal(HIRINGBASISRULEID);
    }

    /**
     * Sets <code>value</code> as attribute value for HIRING_BASIS_RULE_ID using the alias name HiringBasisRuleId.
     * @param value value to set the HIRING_BASIS_RULE_ID
     */
    public void setHiringBasisRuleId(Number value) {
        setAttributeInternal(HIRINGBASISRULEID, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Gets the attribute value for LINE_NUM using the alias name LineNum.
     * @return the LINE_NUM
     */
    public Number getLineNum() {
        return (Number) getAttributeInternal(LINENUM);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_NUM using the alias name LineNum.
     * @param value value to set the LINE_NUM
     */
    public void setLineNum(Number value) {
        setAttributeInternal(LINENUM, value);
    }

    /**
     * Gets the attribute value for LINE_VALUE using the alias name LineValue.
     * @return the LINE_VALUE
     */
    public Number getLineValue() {
        return (Number) getAttributeInternal(LINEVALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_VALUE using the alias name LineValue.
     * @param value value to set the LINE_VALUE
     */
    public void setLineValue(Number value) {
        oracle.jbo.domain.Number zero = new oracle.jbo.domain.Number(0);
        Long days = 0L;
        if(getOnHireDate()!= null && getOffHireDate()!= null){
            days = (getOffHireDate().getValue().getTime() - getOnHireDate().getValue().getTime())/(1000*24*60*60);
            days = days + 1L;
        }
        
        oracle.jbo.domain.Number val = ((((getUnitRate() != null ? getUnitRate(): zero))
                                            .multiply((getQuantity() != null ? getQuantity(): zero))
                                        )
                                            .divide((getTransNoofDays() != null && getTransNoofDays() != zero ? getTransNoofDays(): new Number(1)))
                                       )
                                            .multiply(days);
//        oracle.jbo.domain.Number val = ((getUnitRate() != null ? getUnitRate(): zero))
//                                            .multiply((getQuantity() != null ? getQuantity(): zero));
        setAttributeInternal(LINEVALUE, val);
        setVatTaxAmount(new oracle.jbo.domain.Number(0));
    }

    /**
     * Gets the attribute value for MARGIN_PERCENTAGE using the alias name MarginPercentage.
     * @return the MARGIN_PERCENTAGE
     */
    public Number getMarginPercentage() {
        return (Number) getAttributeInternal(MARGINPERCENTAGE);
    }

    /**
     * Sets <code>value</code> as attribute value for MARGIN_PERCENTAGE using the alias name MarginPercentage.
     * @param value value to set the MARGIN_PERCENTAGE
     */
    public void setMarginPercentage(Number value) {
        setAttributeInternal(MARGINPERCENTAGE, value);
    }

    /**
     * Gets the attribute value for MASTER_QUOTATION_ID using the alias name MasterQuotationId.
     * @return the MASTER_QUOTATION_ID
     */
    public Number getMasterQuotationId() {
        return (Number) getAttributeInternal(MASTERQUOTATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for MASTER_QUOTATION_ID using the alias name MasterQuotationId.
     * @param value value to set the MASTER_QUOTATION_ID
     */
    public void setMasterQuotationId(Number value) {
        setAttributeInternal(MASTERQUOTATIONID, value);
    }

    /**
     * Gets the attribute value for MASTER_QUOTE_LINE_ID using the alias name MasterQuoteLineId.
     * @return the MASTER_QUOTE_LINE_ID
     */
    public Number getMasterQuoteLineId() {
        return (Number) getAttributeInternal(MASTERQUOTELINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for MASTER_QUOTE_LINE_ID using the alias name MasterQuoteLineId.
     * @param value value to set the MASTER_QUOTE_LINE_ID
     */
    public void setMasterQuoteLineId(Number value) {
        setAttributeInternal(MASTERQUOTELINEID, value);
    }

    /**
     * Gets the attribute value for MIN_CHARGE_UNIT using the alias name MinChargeUnit.
     * @return the MIN_CHARGE_UNIT
     */
    public String getMinChargeUnit() {
        return (String) getAttributeInternal(MINCHARGEUNIT);
    }

    /**
     * Sets <code>value</code> as attribute value for MIN_CHARGE_UNIT using the alias name MinChargeUnit.
     * @param value value to set the MIN_CHARGE_UNIT
     */
    public void setMinChargeUnit(String value) {
        setAttributeInternal(MINCHARGEUNIT, value);
    }

    /**
     * Gets the attribute value for MIN_CHARGE_VALUE using the alias name MinChargeValue.
     * @return the MIN_CHARGE_VALUE
     */
    public Number getMinChargeValue() {
        return (Number) getAttributeInternal(MINCHARGEVALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for MIN_CHARGE_VALUE using the alias name MinChargeValue.
     * @param value value to set the MIN_CHARGE_VALUE
     */
    public void setMinChargeValue(Number value) {
        setAttributeInternal(MINCHARGEVALUE, value);
    }

    /**
     * Gets the attribute value for MOBILIZATION_REQUIRED using the alias name MobilizationRequired.
     * @return the MOBILIZATION_REQUIRED
     */
    public String getMobilizationRequired() {
        return (String) getAttributeInternal(MOBILIZATIONREQUIRED);
    }

    /**
     * Sets <code>value</code> as attribute value for MOBILIZATION_REQUIRED using the alias name MobilizationRequired.
     * @param value value to set the MOBILIZATION_REQUIRED
     */
    public void setMobilizationRequired(String value) {
        setAttributeInternal(MOBILIZATIONREQUIRED, value);
    }

    /**
     * Gets the attribute value for OBJECT_VERSION_NUMBER using the alias name ObjectVersionNumber.
     * @return the OBJECT_VERSION_NUMBER
     */
    public Number getObjectVersionNumber() {
        return (Number) getAttributeInternal(OBJECTVERSIONNUMBER);
    }

    /**
     * Gets the attribute value for OFF_HIRE_DATE using the alias name OffHireDate.
     * @return the OFF_HIRE_DATE
     */
    public Date getOffHireDate() {
        return (Date) getAttributeInternal(OFFHIREDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for OFF_HIRE_DATE using the alias name OffHireDate.
     * @param value value to set the OFF_HIRE_DATE
     */
    public void setOffHireDate(Date value) {
        setAttributeInternal(OFFHIREDATE, value);
        setLineValue(new oracle.jbo.domain.Number(0));
    }

    /**
     * Gets the attribute value for ON_HIRE_DATE using the alias name OnHireDate.
     * @return the ON_HIRE_DATE
     */
    public Date getOnHireDate() {
        return (Date) getAttributeInternal(ONHIREDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for ON_HIRE_DATE using the alias name OnHireDate.
     * @param value value to set the ON_HIRE_DATE
     */
    public void setOnHireDate(Date value) {
        setAttributeInternal(ONHIREDATE, value);
        setLineValue(new oracle.jbo.domain.Number(0));
    }

    /**
     * Gets the attribute value for OPERATOR_OPTION using the alias name OperatorOption.
     * @return the OPERATOR_OPTION
     */
    public String getOperatorOption() {
        return (String) getAttributeInternal(OPERATOROPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for OPERATOR_OPTION using the alias name OperatorOption.
     * @param value value to set the OPERATOR_OPTION
     */
    public void setOperatorOption(String value) {
        setAttributeInternal(OPERATOROPTION, value);
    }

    /**
     * Gets the attribute value for OT1_RATE using the alias name Ot1Rate.
     * @return the OT1_RATE
     */
    public Number getOt1Rate() {
        return (Number) getAttributeInternal(OT1RATE);
    }

    /**
     * Sets <code>value</code> as attribute value for OT1_RATE using the alias name Ot1Rate.
     * @param value value to set the OT1_RATE
     */
    public void setOt1Rate(Number value) {
        setAttributeInternal(OT1RATE, value);
    }

    /**
     * Gets the attribute value for OT2_RATE using the alias name Ot2Rate.
     * @return the OT2_RATE
     */
    public Number getOt2Rate() {
        return (Number) getAttributeInternal(OT2RATE);
    }

    /**
     * Sets <code>value</code> as attribute value for OT2_RATE using the alias name Ot2Rate.
     * @param value value to set the OT2_RATE
     */
    public void setOt2Rate(Number value) {
        setAttributeInternal(OT2RATE, value);
    }

    /**
     * Gets the attribute value for PARENT_QUOTATION_ID using the alias name ParentQuotationId.
     * @return the PARENT_QUOTATION_ID
     */
    public Number getParentQuotationId() {
        return (Number) getAttributeInternal(PARENTQUOTATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for PARENT_QUOTATION_ID using the alias name ParentQuotationId.
     * @param value value to set the PARENT_QUOTATION_ID
     */
    public void setParentQuotationId(Number value) {
        setAttributeInternal(PARENTQUOTATIONID, value);
    }

    /**
     * Gets the attribute value for PARENT_QUOTE_LINE_ID using the alias name ParentQuoteLineId.
     * @return the PARENT_QUOTE_LINE_ID
     */
    public Number getParentQuoteLineId() {
        return (Number) getAttributeInternal(PARENTQUOTELINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for PARENT_QUOTE_LINE_ID using the alias name ParentQuoteLineId.
     * @param value value to set the PARENT_QUOTE_LINE_ID
     */
    public void setParentQuoteLineId(Number value) {
        setAttributeInternal(PARENTQUOTELINEID, value);
    }

    /**
     * Gets the attribute value for QUANTITY using the alias name Quantity.
     * @return the QUANTITY
     */
    public Number getQuantity() {
        return (Number) getAttributeInternal(QUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for QUANTITY using the alias name Quantity.
     * @param value value to set the QUANTITY
     */
    public void setQuantity(Number value) {        
        setAttributeInternal(QUANTITY, value);
        setLineValue(new oracle.jbo.domain.Number(0));
    }

    /**
     * Gets the attribute value for QUOTATION_ID using the alias name QuotationId.
     * @return the QUOTATION_ID
     */
    public Number getQuotationId() {
        return (Number) getAttributeInternal(QUOTATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for QUOTATION_ID using the alias name QuotationId.
     * @param value value to set the QUOTATION_ID
     */
    public void setQuotationId(Number value) {
        setAttributeInternal(QUOTATIONID, value);
    }

    /**
     * Gets the attribute value for QUOTE_LINE_ID using the alias name QuoteLineId.
     * @return the QUOTE_LINE_ID
     */
    public Number getQuoteLineId() {
        return (Number) getAttributeInternal(QUOTELINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for QUOTE_LINE_ID using the alias name QuoteLineId.
     * @param value value to set the QUOTE_LINE_ID
     */
    public void setQuoteLineId(Number value) {
        setAttributeInternal(QUOTELINEID, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for RENTAL_TYPE using the alias name RentalType.
     * @return the RENTAL_TYPE
     */
    public String getRentalType() {
        return (String) getAttributeInternal(RENTALTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for RENTAL_TYPE using the alias name RentalType.
     * @param value value to set the RENTAL_TYPE
     */
    public void setRentalType(String value) {
        setAttributeInternal(RENTALTYPE, value);
    }

    /**
     * Gets the attribute value for REQUEST_ID using the alias name RequestId.
     * @return the REQUEST_ID
     */
    public Number getRequestId() {
        return (Number) getAttributeInternal(REQUESTID);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUEST_ID using the alias name RequestId.
     * @param value value to set the REQUEST_ID
     */
    public void setRequestId(Number value) {
        setAttributeInternal(REQUESTID, value);
    }

    /**
     * Gets the attribute value for REQUEST_LINE_ID using the alias name RequestLineId.
     * @return the REQUEST_LINE_ID
     */
    public Number getRequestLineId() {
        return (Number) getAttributeInternal(REQUESTLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUEST_LINE_ID using the alias name RequestLineId.
     * @param value value to set the REQUEST_LINE_ID
     */
    public void setRequestLineId(Number value) {
        setAttributeInternal(REQUESTLINEID, value);
    }

    /**
     * Gets the attribute value for REQUEST_LINE_NUM using the alias name RequestLineNum.
     * @return the REQUEST_LINE_NUM
     */
    public Number getRequestLineNum() {
        return (Number) getAttributeInternal(REQUESTLINENUM);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUEST_LINE_NUM using the alias name RequestLineNum.
     * @param value value to set the REQUEST_LINE_NUM
     */
    public void setRequestLineNum(Number value) {
        setAttributeInternal(REQUESTLINENUM, value);
    }

    /**
     * Gets the attribute value for SHIFT using the alias name Shift.
     * @return the SHIFT
     */
    public String getShift() {
        return (String) getAttributeInternal(SHIFT);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIFT using the alias name Shift.
     * @param value value to set the SHIFT
     */
    public void setShift(String value) {
        setAttributeInternal(SHIFT, value);
    }

    /**
     * Gets the attribute value for STANDARD_RATE using the alias name StandardRate.
     * @return the STANDARD_RATE
     */
    public Number getStandardRate() {
        return (Number) getAttributeInternal(STANDARDRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for STANDARD_RATE using the alias name StandardRate.
     * @param value value to set the STANDARD_RATE
     */
    public void setStandardRate(Number value) {
        setAttributeInternal(STANDARDRATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransAssetRequestNum.
     * @return the TransAssetRequestNum
     */
    public String getTransAssetRequestNum() {
        return (String) getAttributeInternal(TRANSASSETREQUESTNUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransAssetRequestNum.
     * @param value value to set the  TransAssetRequestNum
     */
    public void setTransAssetRequestNum(String value) {
        setAttributeInternal(TRANSASSETREQUESTNUM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransRentalType.
     * @return the TransRentalType
     */
    public String getTransRentalType() {
        return (String) getAttributeInternal(TRANSRENTALTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransRentalType.
     * @param value value to set the  TransRentalType
     */
    public void setTransRentalType(String value) {
        setAttributeInternal(TRANSRENTALTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransAssetCategory.
     * @return the TransAssetCategory
     */
    public String getTransAssetCategory() {
        return (String) getAttributeInternal(TRANSASSETCATEGORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransAssetCategory.
     * @param value value to set the  TransAssetCategory
     */
    public void setTransAssetCategory(String value) {
        setAttributeInternal(TRANSASSETCATEGORY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransAssetDescription.
     * @return the TransAssetDescription
     */
    public String getTransAssetDescription() {
        return (String) getAttributeInternal(TRANSASSETDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransAssetDescription.
     * @param value value to set the  TransAssetDescription
     */
    public void setTransAssetDescription(String value) {
        setAttributeInternal(TRANSASSETDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransHiringBasis.
     * @return the TransHiringBasis
     */
    public String getTransHiringBasis() {
        return (String) getAttributeInternal(TRANSHIRINGBASIS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransHiringBasis.
     * @param value value to set the  TransHiringBasis
     */
    public void setTransHiringBasis(String value) {
        setAttributeInternal(TRANSHIRINGBASIS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransFixedVariable.
     * @return the TransFixedVariable
     */
    public String getTransFixedVariable() {
        return (String) getAttributeInternal(TRANSFIXEDVARIABLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransFixedVariable.
     * @param value value to set the  TransFixedVariable
     */
    public void setTransFixedVariable(String value) {
        setAttributeInternal(TRANSFIXEDVARIABLE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransOperatorOption.
     * @return the TransOperatorOption
     */
    public String getTransOperatorOption() {
        return (String) getAttributeInternal(TRANSOPERATOROPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransOperatorOption.
     * @param value value to set the  TransOperatorOption
     */
    public void setTransOperatorOption(String value) {
        setAttributeInternal(TRANSOPERATOROPTION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransFuelOption.
     * @return the TransFuelOption
     */
    public String getTransFuelOption() {
        return (String) getAttributeInternal(TRANSFUELOPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransFuelOption.
     * @param value value to set the  TransFuelOption
     */
    public void setTransFuelOption(String value) {
        setAttributeInternal(TRANSFUELOPTION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransMobilizationRequired.
     * @return the TransMobilizationRequired
     */
    public String getTransMobilizationRequired() {
        return (String) getAttributeInternal(TRANSMOBILIZATIONREQUIRED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransMobilizationRequired.
     * @param value value to set the  TransMobilizationRequired
     */
    public void setTransMobilizationRequired(String value) {
        setAttributeInternal(TRANSMOBILIZATIONREQUIRED, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransShift.
     * @return the TransShift
     */
    public String getTransShift() {
        return (String) getAttributeInternal(TRANSSHIFT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransShift.
     * @param value value to set the  TransShift
     */
    public void setTransShift(String value) {
        setAttributeInternal(TRANSSHIFT, value);
    }

    /**
     * Gets the attribute value for BU_ID using the alias name BuId.
     * @return the BU_ID
     */
    public Number getBuId() {
        return (Number) getAttributeInternal(BUID);
    }

    /**
     * Sets <code>value</code> as attribute value for BU_ID using the alias name BuId.
     * @param value value to set the BU_ID
     */
    public void setBuId(Number value) {
        setAttributeInternal(BUID, value);
    }

    /**
     * Gets the attribute value for QUOTATION_ID using the alias name QuotationId1.
     * @return the QUOTATION_ID
     */
    public Number getQuotationId1() {
        return (Number) getAttributeInternal(QUOTATIONID1);
    }

    /**
     * Sets <code>value</code> as attribute value for QUOTATION_ID using the alias name QuotationId1.
     * @param value value to set the QUOTATION_ID
     */
    public void setQuotationId1(Number value) {
        setAttributeInternal(QUOTATIONID1, value);
    }

    /**
     * Gets the attribute value for CUSTOMER_ID using the alias name CustomerId.
     * @return the CUSTOMER_ID
     */
    public Number getCustomerId() {
        return (Number) getAttributeInternal(CUSTOMERID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMER_ID using the alias name CustomerId.
     * @param value value to set the CUSTOMER_ID
     */
    public void setCustomerId(Number value) {
        setAttributeInternal(CUSTOMERID, value);
    }

    /**
     * Gets the attribute value for DEPT_FLEX_VALUE_ID using the alias name DeptFlexValueId.
     * @return the DEPT_FLEX_VALUE_ID
     */
    public Number getDeptFlexValueId() {
        return (Number) getAttributeInternal(DEPTFLEXVALUEID);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPT_FLEX_VALUE_ID using the alias name DeptFlexValueId.
     * @param value value to set the DEPT_FLEX_VALUE_ID
     */
    public void setDeptFlexValueId(Number value) {
        setAttributeInternal(DEPTFLEXVALUEID, value);
    }

    /**
     * Gets the attribute value for DIV_FLEX_VALUE_ID using the alias name DivFlexValueId.
     * @return the DIV_FLEX_VALUE_ID
     */
    public Number getDivFlexValueId() {
        return (Number) getAttributeInternal(DIVFLEXVALUEID);
    }

    /**
     * Sets <code>value</code> as attribute value for DIV_FLEX_VALUE_ID using the alias name DivFlexValueId.
     * @param value value to set the DIV_FLEX_VALUE_ID
     */
    public void setDivFlexValueId(Number value) {
        setAttributeInternal(DIVFLEXVALUEID, value);
    }

    /**
     * Gets the attribute value for PROJECT_ID using the alias name ProjectId.
     * @return the PROJECT_ID
     */
    public Number getProjectId() {
        return (Number) getAttributeInternal(PROJECTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROJECT_ID using the alias name ProjectId.
     * @param value value to set the PROJECT_ID
     */
    public void setProjectId(Number value) {
        setAttributeInternal(PROJECTID, value);
    }

    /**
     * Gets the attribute value for CUSTOMER_TYPE using the alias name CustomerType.
     * @return the CUSTOMER_TYPE
     */
    public String getCustomerType() {
        return (String) getAttributeInternal(CUSTOMERTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMER_TYPE using the alias name CustomerType.
     * @param value value to set the CUSTOMER_TYPE
     */
    public void setCustomerType(String value) {
        setAttributeInternal(CUSTOMERTYPE, value);
    }

    /**
     * Gets the attribute value for REQ_BU_ID using the alias name ReqBuId.
     * @return the REQ_BU_ID
     */
    public Number getReqBuId() {
        return (Number) getAttributeInternal(REQBUID);
    }

    /**
     * Sets <code>value</code> as attribute value for REQ_BU_ID using the alias name ReqBuId.
     * @param value value to set the REQ_BU_ID
     */
    public void setReqBuId(Number value) {
        setAttributeInternal(REQBUID, value);
    }

    /**
     * Gets the attribute value for SRC_DIV_FLEX_VAL_ID using the alias name SrcDivFlexValId.
     * @return the SRC_DIV_FLEX_VAL_ID
     */
    public Number getSrcDivFlexValId() {
        return (Number) getAttributeInternal(SRCDIVFLEXVALID);
    }

    /**
     * Sets <code>value</code> as attribute value for SRC_DIV_FLEX_VAL_ID using the alias name SrcDivFlexValId.
     * @param value value to set the SRC_DIV_FLEX_VAL_ID
     */
    public void setSrcDivFlexValId(Number value) {
        setAttributeInternal(SRCDIVFLEXVALID, value);
    }

    /**
     * Gets the attribute value for SITE_USE_ID using the alias name SiteUseId.
     * @return the SITE_USE_ID
     */
    public Number getSiteUseId() {
        return (Number) getAttributeInternal(SITEUSEID);
    }

    /**
     * Sets <code>value</code> as attribute value for SITE_USE_ID using the alias name SiteUseId.
     * @param value value to set the SITE_USE_ID
     */
    public void setSiteUseId(Number value) {
        setAttributeInternal(SITEUSEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransHdrBuId.
     * @return the TransHdrBuId
     */
    public Number getTransHdrBuId() {
        if(getBuId()!= null){
            return getBuId();
        }
        return (Number) getAttributeInternal(TRANSHDRBUID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransHdrBuId.
     * @param value value to set the  TransHdrBuId
     */
    public void setTransHdrBuId(Number value) {
        setAttributeInternal(TRANSHDRBUID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransHdrSrcDivFlexValId.
     * @return the TransHdrSrcDivFlexValId
     */
    public Number getTransHdrSrcDivFlexValId() {
        if(getSrcDivFlexValId()!= null){
            return getSrcDivFlexValId();
        }
        return (Number) getAttributeInternal(TRANSHDRSRCDIVFLEXVALID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransHdrSrcDivFlexValId.
     * @param value value to set the  TransHdrSrcDivFlexValId
     */
    public void setTransHdrSrcDivFlexValId(Number value) {
        setAttributeInternal(TRANSHDRSRCDIVFLEXVALID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransHdrReqBuId.
     * @return the TransHdrReqBuId
     */
    public Number getTransHdrReqBuId() {
        if(getReqBuId() != null){
            return getReqBuId();
        }
        return (Number) getAttributeInternal(TRANSHDRREQBUID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransHdrReqBuId.
     * @param value value to set the  TransHdrReqBuId
     */
    public void setTransHdrReqBuId(Number value) {
        setAttributeInternal(TRANSHDRREQBUID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransHdrCustType.
     * @return the TransHdrCustType
     */
    public String getTransHdrCustType() {
        if(getCustomerType() != null){
            return getCustomerType();
        }
        return (String) getAttributeInternal(TRANSHDRCUSTTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransHdrCustType.
     * @param value value to set the  TransHdrCustType
     */
    public void setTransHdrCustType(String value) {
        setAttributeInternal(TRANSHDRCUSTTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransHdrProjectId.
     * @return the TransHdrProjectId
     */
    public Number getTransHdrProjectId() {
        if(getProjectId()!= null){
            return getProjectId();
        }
        return (Number) getAttributeInternal(TRANSHDRPROJECTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransHdrProjectId.
     * @param value value to set the  TransHdrProjectId
     */
    public void setTransHdrProjectId(Number value) {
        setAttributeInternal(TRANSHDRPROJECTID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransHdrDivFlexValueId.
     * @return the TransHdrDivFlexValueId
     */
    public Number getTransHdrDivFlexValueId() {
        if(getDivFlexValueId() != null){
            return getDivFlexValueId();
        }
        return (Number) getAttributeInternal(TRANSHDRDIVFLEXVALUEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransHdrDivFlexValueId.
     * @param value value to set the  TransHdrDivFlexValueId
     */
    public void setTransHdrDivFlexValueId(Number value) {
        setAttributeInternal(TRANSHDRDIVFLEXVALUEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransHdrDeptFlexValueId.
     * @return the TransHdrDeptFlexValueId
     */
    public Number getTransHdrDeptFlexValueId() {
        if(getDeptFlexValueId()!= null){
            return getDeptFlexValueId();
        }
        return (Number) getAttributeInternal(TRANSHDRDEPTFLEXVALUEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransHdrDeptFlexValueId.
     * @param value value to set the  TransHdrDeptFlexValueId
     */
    public void setTransHdrDeptFlexValueId(Number value) {
        setAttributeInternal(TRANSHDRDEPTFLEXVALUEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransHdrCustomerId.
     * @return the TransHdrCustomerId
     */
    public Number getTransHdrCustomerId() {
        if(getCustomerId() != null){
            return getCustomerId();
        }
        return (Number) getAttributeInternal(TRANSHDRCUSTOMERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransHdrCustomerId.
     * @param value value to set the  TransHdrCustomerId
     */
    public void setTransHdrCustomerId(Number value) {
        setAttributeInternal(TRANSHDRCUSTOMERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransHdrSiteUseId.
     * @return the TransHdrSiteUseId
     */
    public Number getTransHdrSiteUseId() {
        if(getSiteUseId()!= null){
            return getSiteUseId();
        }
        return (Number) getAttributeInternal(TRANSHDRSITEUSEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransHdrSiteUseId.
     * @param value value to set the  TransHdrSiteUseId
     */
    public void setTransHdrSiteUseId(Number value) {
        setAttributeInternal(TRANSHDRSITEUSEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransMinChargeUnit.
     * @return the TransMinChargeUnit
     */
    public String getTransMinChargeUnit() {
        return (String) getAttributeInternal(TRANSMINCHARGEUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransMinChargeUnit.
     * @param value value to set the  TransMinChargeUnit
     */
    public void setTransMinChargeUnit(String value) {
        setAttributeInternal(TRANSMINCHARGEUNIT, value);
    }

    /**
     * Gets the attribute value for UNIT_RATE using the alias name UnitRate.
     * @return the UNIT_RATE
     */
    public Number getUnitRate() {
        return (Number) getAttributeInternal(UNITRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for UNIT_RATE using the alias name UnitRate.
     * @param value value to set the UNIT_RATE
     */
    public void setUnitRate(Number value) {
        setAttributeInternal(UNITRATE, value);
        setLineValue(new oracle.jbo.domain.Number(0));
    }

    /**
     * Gets the attribute value for the calculated attribute TransNoofDays.
     * @return the TransNoofDays
     */
    public Number getTransNoofDays() {
        return (Number) getAttributeInternal(TRANSNOOFDAYS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransNoofDays.
     * @param value value to set the  TransNoofDays
     */
    public void setTransNoofDays(Number value) {
        setAttributeInternal(TRANSNOOFDAYS, value);
        setLineValue(new oracle.jbo.domain.Number(0));
    }

    /**
     * Gets the attribute value for the calculated attribute TransStandardHours.
     * @return the TransStandardHours
     */
    public Number getTransStandardHours() {
        return (Number) getAttributeInternal(TRANSSTANDARDHOURS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransStandardHours.
     * @param value value to set the  TransStandardHours
     */
    public void setTransStandardHours(Number value) {
        setAttributeInternal(TRANSSTANDARDHOURS, value);
    }

    /**
     * Gets the attribute value for TAX_RATE_ID using the alias name TaxRateId.
     * @return the TAX_RATE_ID
     */
    public Number getTaxRateId() {
        return (Number) getAttributeInternal(TAXRATEID);
    }

    /**
     * Sets <code>value</code> as attribute value for TAX_RATE_ID using the alias name TaxRateId.
     * @param value value to set the TAX_RATE_ID
     */
    public void setTaxRateId(Number value) {
        setAttributeInternal(TAXRATEID, value);
    }

    /**
     * Gets the attribute value for TAX_RATE_PERCENT using the alias name TaxRatePercent.
     * @return the TAX_RATE_PERCENT
     */
    public Number getTaxRatePercent() {
        return (Number) getAttributeInternal(TAXRATEPERCENT);
    }

    /**
     * Sets <code>value</code> as attribute value for TAX_RATE_PERCENT using the alias name TaxRatePercent.
     * @param value value to set the TAX_RATE_PERCENT
     */
    public void setTaxRatePercent(Number value) {        
        setAttributeInternal(TAXRATEPERCENT, value);
        setVatTaxAmount(new oracle.jbo.domain.Number(0));
    }

    /**
     * Gets the attribute value for VAT_TAX_AMOUNT using the alias name VatTaxAmount.
     * @return the VAT_TAX_AMOUNT
     */
    public Number getVatTaxAmount() {
        return (Number) getAttributeInternal(VATTAXAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for VAT_TAX_AMOUNT using the alias name VatTaxAmount.
     * @param value value to set the VAT_TAX_AMOUNT
     */
    public void setVatTaxAmount(Number value) {
        oracle.jbo.domain.Number zero = new oracle.jbo.domain.Number(0);
        oracle.jbo.domain.Number val = ((getTaxRatePercent() != null ? getTaxRatePercent(): zero).divide(100)
                                            .multiply(getLineValue() != null ? getLineValue(): zero));
        setAttributeInternal(VATTAXAMOUNT, val);
    }

    /**
     * Gets the attribute value for TAX_RATE_CODE using the alias name TaxRateCode.
     * @return the TAX_RATE_CODE
     */
    public String getTaxRateCode() {
        return (String) getAttributeInternal(TAXRATECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for TAX_RATE_CODE using the alias name TaxRateCode.
     * @param value value to set the TAX_RATE_CODE
     */
    public void setTaxRateCode(String value) {
        setAttributeInternal(TAXRATECODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransNetAmount.
     * @return the TransNetAmount
     */
    public Number getTransNetAmount() {
        return (Number) getAttributeInternal(TRANSNETAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransNetAmount.
     * @param value value to set the  TransNetAmount
     */
    public void setTransNetAmount(Number value) {
        setAttributeInternal(TRANSNETAMOUNT, value);
    }

    /**
     * Gets the attribute value for CATEGORY_DESCRIPTION using the alias name CategoryDescription.
     * @return the CATEGORY_DESCRIPTION
     */
    public String getCategoryDescription() {
        return (String) getAttributeInternal(CATEGORYDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for CATEGORY_DESCRIPTION using the alias name CategoryDescription.
     * @param value value to set the CATEGORY_DESCRIPTION
     */
    public void setCategoryDescription(String value) {
        setAttributeInternal(CATEGORYDESCRIPTION, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> QuoteAssetRequestLovVO1.
     */
    public RowSet getQuoteAssetRequestLovVO1() {
        return (RowSet) getAttributeInternal(QUOTEASSETREQUESTLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LookupsLOV1.
     */
    public RowSet getLookupsLOV1() {
        return (RowSet) getAttributeInternal(LOOKUPSLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> RentalTypeBasedCategoryLOV1.
     */
    public RowSet getRentalTypeBasedCategoryLOV1() {
        return (RowSet) getAttributeInternal(RENTALTYPEBASEDCATEGORYLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> HiringBasisLOVVO1.
     */
    public RowSet getHiringBasisLOVVO1() {
        return (RowSet) getAttributeInternal(HIRINGBASISLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> OptionsLOVVO1.
     */
    public RowSet getOptionsLOVVO1() {
        return (RowSet) getAttributeInternal(OPTIONSLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> OptionsLOVVO2.
     */
    public RowSet getOptionsLOVVO2() {
        return (RowSet) getAttributeInternal(OPTIONSLOVVO2);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LookupsLOV2.
     */
    public RowSet getLookupsLOV2() {
        return (RowSet) getAttributeInternal(LOOKUPSLOV2);
    }

    /**
     * Gets the view accessor <code>RowSet</code> QuoteAssetRequestLinesLovVO1.
     */
    public RowSet getQuoteAssetRequestLinesLovVO1() {
        return (RowSet) getAttributeInternal(QUOTEASSETREQUESTLINESLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> QuoteChargeableUnitLovVO1.
     */
    public RowSet getQuoteChargeableUnitLovVO1() {
        return (RowSet) getAttributeInternal(QUOTECHARGEABLEUNITLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LookupsLOV3.
     */
    public RowSet getLookupsLOV3() {
        return (RowSet) getAttributeInternal(LOOKUPSLOV3);
    }

    /**
     * Gets the view accessor <code>RowSet</code> TaxCodesLOV1.
     */
    public RowSet getTaxCodesLOV1() {
        return (RowSet) getAttributeInternal(TAXCODESLOV1);
    }
}

